### ISSUE TITLE
[bug] state() called before manage() 

### ISSUE THREAD

**Issue by Akmot9** [tauri-apps/tauri#10230]
### Describe the bug

The Tauri application experiences a panic when attempting to access the managed state. it display this error message : state not managed for field `state` on command `get_matrice`. You must call `.manage()` before using this command

### Reproduction

https://github.com/Akmot9/state_before_manage

### Expected behavior

pressing the togle button should stop the threads form adding new values. 

### Full `tauri info` output

```text
> state_befor_manage@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.44.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.81.0-nightly (35b658fb1 2024-07-08)
    ✔ cargo: 1.81.0-nightly (154fdac39 2024-07-07)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 20.15.1
    - pnpm: 8.10.2
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 2.0.0-beta.15
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

```text
thread '<unnamed>' panicked at /home/erdt-cyber/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.7.1/src/lib.rs:902:8:
state() called before manage() for given type
stack backtrace:
   0:     0x560957b501e5 - std::backtrace_rs::backtrace::libunwind::trace::h34f4ddc27ab52380
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x560957b501e5 - std::backtrace_rs::backtrace::trace_unsynchronized::hcc726b9dedee9644
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560957b501e5 - std::sys::backtrace::_print_fmt::h13423a8422f58734
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/backtrace.rs:68:5
   3:     0x560957b501e5 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h92682b27a087a29b
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/backtrace.rs:44:22
   4:     0x560957b7f82b - core::fmt::rt::Argument::fmt::hded6d8a1542504a9
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/fmt/rt.rs:173:76
   5:     0x560957b7f82b - core::fmt::write::h69c9cb1b95b4dde6
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/fmt/mod.rs:1174:21
   6:     0x560957b4b92f - std::io::Write::write_fmt::hbcc79fb10ca26c0a
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/io/mod.rs:1835:15
   7:     0x560957b4ffbe - std::sys::backtrace::_print::h6dfec6fd7cb06bdf
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/backtrace.rs:47:5
   8:     0x560957b4ffbe - std::sys::backtrace::print::hbab33d07aee591cc
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/backtrace.rs:34:9
   9:     0x560957b51409 - std::panicking::default_hook::{{closure}}::hd8c4e5ab36fc9bff
  10:     0x560957b511ac - std::panicking::default_hook::hcd5b28786e200ce6
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panicking.rs:292:9
  11:     0x560957b519e1 - std::panicking::rust_panic_with_hook::hc632527a1e12e7b9
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panicking.rs:796:13
  12:     0x560957b51847 - std::panicking::begin_panic_handler::{{closure}}::h3c20ec48bea6be58
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panicking.rs:670:13
  13:     0x560957b506a9 - std::sys::backtrace::__rust_end_short_backtrace::h552299e169b30c2d
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/backtrace.rs:171:18
  14:     0x560957b51524 - rust_begin_unwind
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panicking.rs:661:5
  15:     0x560957b7c683 - core::panicking::panic_fmt::hb93f18924ac04e67
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/panicking.rs:74:14
  16:     0x560957b7c5cb - core::panicking::panic_display::h536207085bf47ab5
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/panicking.rs:264:5
  17:     0x560957b7c5cb - core::option::expect_failed::h2ad3d5c73adc8888
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/option.rs:2023:5
  18:     0x560956505942 - core::option::Option<T>::expect::h28b7eb79679015d4
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/option.rs:926:21
  19:     0x560956508df9 - tauri::Manager::state::hda9d94fa052c1e25
                               at /home/erdt-cyber/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.7.1/src/lib.rs:897:5
  20:     0x5609565609b1 - sonar_desktop_app::sniff::capture_packet::capture_packets::he3d7dd989605578c
                               at /home/erdt-cyber/Documents/gitHub/Sonar_desktop_app/src-tauri/src/sniff/capture_packet/mod.rs:159:37
  21:     0x560956521d71 - sonar_desktop_app::sniff::capture_packet::all_interfaces::{{closure}}::h7a07592e0bdff302
                               at /home/erdt-cyber/Documents/gitHub/Sonar_desktop_app/src-tauri/src/sniff/capture_packet/mod.rs:68:17
  22:     0x560956521986 - std::sys::backtrace::__rust_begin_short_backtrace::h5090e8c3d423b17e
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/backtrace.rs:155:18
  23:     0x5609565209f0 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h2c939765a3a32448
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/thread/mod.rs:542:17
  24:     0x560956521964 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hefa7d69a08a1d668
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/panic/unwind_safe.rs:272:9
  25:     0x560956521514 - std::panicking::try::do_call::h2a62ea405a7c26d9
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panicking.rs:553:40
  26:     0x56095652187b - __rust_try
  27:     0x560956521478 - std::panicking::try::he6f574d207fc8c30
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panicking.rs:517:19
  28:     0x5609565207b7 - std::panic::catch_unwind::h85386d03c35b3070
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/panic.rs:350:14
  29:     0x5609565207b7 - std::thread::Builder::spawn_unchecked_::{{closure}}::hd708822534ef6be8
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/thread/mod.rs:541:30
  30:     0x56095656d4cf - core::ops::function::FnOnce::call_once{{vtable.shim}}::h58e0c70474288df1
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/core/src/ops/function.rs:250:5
  31:     0x560957b57e3b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4f003967ca538f8e
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/alloc/src/boxed.rs:2064:9
  32:     0x560957b57e3b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf2b2bd253c157c7
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/alloc/src/boxed.rs:2064:9
  33:     0x560957b57e3b - std::sys::pal::unix::thread::Thread::new::thread_start::h213ae956040b9629
                               at /rustc/6868c831a1eb45c5150ff623cef5e42a8b8946d0/library/std/src/sys/pal/unix/thread.rs:108:17
  34:     0x77b6ede94ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  35:     0x77b6edf26850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  36:                0x0 - <unknown>
```

**Comment by FabianLars** [comment]
`SonarState::new()` already returns Arc<Mutex> and you wrap it again into Arc<Mutex> in the manage call so you'll end up with `Arc<Mutex<Arc<Mutex<SonarState>`. You reqeust the state later as if you managed `Arc<Mutex<SonarState>>` though.

**Comment by anuradhawick** [comment]
@FabianLars I might be mistaken, but without wrapping in an Arc<Mutex<>> we cannot run a background thread. What is the workaround for these cases?

**Comment by anuradhawick** [comment]
@Akmot9 did you find a solution? 

I am having a similar poblem in Tauri V2. Mainly because app.app_handle() is now a reference and requires cloning. This does seem to affect how it works. Although in V1, it worked as expected.

**Comment by FabianLars** [comment]
@anuradhawick 

> I might be mistaken, but without wrapping in an Arc<Mutex<>> we cannot run a background thread. What is the workaround for these cases?

Arc<Mutex<>> is one way to make this work, yes. What i typically recommend is just moving around `AppHandle`s and use that to get the state in the scopes it's actually needed. Judging by your second method i assume you knew that already.

> I am having a similar poblem in Tauri V2. Mainly because app.app_handle() is now a reference and requires cloning. This does seem to affect how it works. Although in V1, it worked as expected.

Just clone it 🤷 That's what Tauri did for you in v1 so you're not losing anything really if you just clone it as much as you want/need.

**Comment by anuradhawick** [comment]
@FabianLars thanks for getting back on this.

This is what I have in V1

```rust
.setup(|app| {
    // register watcher state
    let watcher = ClipboardWatcher::new(app.app_handle());
    app.manage(watcher);
```

watcher is an `Arc<Mutex<Self>>` and my commands capture it correctly with 

```rust
pub fn pause_clipboard_watcher(state: State<Arc<Mutex<ClipboardWatcher>>>)
```

The same code when I migrated to v2 breaks and give the error `state() called before manage()`.

The changes I did were

```rust
.setup(|app| {
    // register watcher state
    let watcher = ClipboardWatcher::new(app.app_handle().clone());
    app.manage(watcher);
```

I thought may be this was due to the cloning. I will give this another try.

Keep it up, super keen to use Tauri on some interesting projects.
