### ISSUE TITLE
[bug] Bug in Tauri v2 beta: Tokio spawn in Window Listener Causes Panic

### ISSUE THREAD

**Issue by ThisSeanZhang** [tauri-apps/tauri#10289]
### Describe the bug

In Tauri v1, it was possible to use `tokio::spawn` to create asynchronous tasks within a window listener on Windows. However, in Tauri v2, this causes a panic with the following error:
```text
thread 'main' panicked at src/main.rs:20:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[0715/061654.932:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

### Reproduction

1. Create a Tauri application using ***yarn create tauri-app --beta***
2. Replace Or you can find here [https://github.com/ThisSeanZhang/tauri-illustrate-20240715](https://github.com/ThisSeanZhang/tauri-illustrate-20240715)
  ```rust
  // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
  #[tauri::command]
  fn greet(name: &str) -> String {
      format!("Hello, {}! You've been greeted from Rust!", name)
  }
  ```
  to
  ```rust
  use std::time::Duration;
  
  use tauri::{async_runtime, Listener, Window};
  #[derive(Debug, serde::Serialize)]
  enum MyError {
      FooError,
  }
  
  // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
  #[tauri::command(async)]
  async fn greet(window: Window, name: &str) -> Result<String, MyError> {
      tokio::spawn(async move {
          tokio::time::sleep(Duration::from_secs(1)).await;
      });
      tokio::time::sleep(Duration::from_secs(1)).await;
      window.listen("test", move |_event| {
          // 👇👇👇 not work 👇👇👇
          tokio::spawn(async move {
              tokio::time::sleep(Duration::from_secs(1)).await;
          });
          // 👆👆👆
  
          // 👇👇👇 works 👇👇👇
          // async_runtime::spawn(async move {
          //     tokio::time::sleep(Duration::from_secs(1)).await;
          // });
          // 👆👆👆
      });
      Ok(format!("Hello, {}! You've been greeted from Rust!", name))
  }
  
  ```
```vue
<script setup lang="ts">
import { ref } from "vue";
import { invoke } from "@tauri-apps/api/core";

const greetMsg = ref("");
const name = ref("");

async function greet() {
  // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
  greetMsg.value = await invoke("greet", { name: name.value });
}
</script>

```

to 

```vue
<script setup lang="ts">
import { ref } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { getCurrentWindow } from '@tauri-apps/api/window';

const greetMsg = ref("");
const name = ref("");

async function greet() {
  // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
  greetMsg.value = await invoke("greet", { name: name.value });

  const window = getCurrentWindow();
  window.emit("test")
}
</script>
```
5. Run the application on Windows.

### Expected behavior

The program will not exit

### Full `tauri info` output

```text
# Windows

PS D:\tauri-test\tauri-app-v2> npm run tauri info

> tauri-app-v2@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 126.0.2592.102
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.79.0-nightly (3a36386dc 2024-04-25)
    ✔ cargo: 1.79.0-nightly (c93926759 2024-04-23)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 9.5.0
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19   
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/      
    - framework: Vue.js
    - bundler: Vite

# Linux
```text
yarn run v1.22.22
$ tauri info

[✔] Environment
    - OS: Manjaro 24.0.2 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.58.1
    ✔ rustc: 1.80.0-nightly (1fffb2a35 2024-04-28)
    ✔ cargo: 1.80.0-nightly (b60a15551 2024-04-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 22.2.0
    - pnpm: 8.15.5
    - yarn: 1.22.22

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
Done in 31.76s.
```
```


### Stack trace

```text
# Stack in Linux

thread 'main' panicked at src/main.rs:20:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/panicking.rs:263:5
   3: tokio::task::spawn::spawn_inner::panic_cold_display
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/panic.rs:99:13
   4: tokio::task::spawn::spawn_inner
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/task/spawn.rs:203:23
   5: tokio::task::spawn::spawn
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/task/spawn.rs:174:13
   6: tauri_test_cmd::greet::{{closure}}::{{closure}}
             at ./src/main.rs:20:9
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/alloc/src/boxed.rs:2036:9
   8: tauri::event::listener::Listeners::emit_filter
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/event/listener.rs:207:13
   9: tauri::event::listener::Listeners::emit
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/event/listener.rs:222:5
  10: tauri::manager::AppManager<R>::emit
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/manager/mod.rs:503:5
  11: <tauri::app::AppHandle<R> as tauri::Emitter<R>>::emit
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/app.rs:896:9
  12: tauri::event::plugin::emit
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/event/plugin.rs:92:3
  13: tauri::event::plugin::init::{{closure}}
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/event/plugin.rs:86:1
  14: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/alloc/src/boxed.rs:2036:9
  15: <tauri::plugin::TauriPlugin<R,C> as tauri::plugin::Plugin<R>>::extend_api
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/plugin.rs:724:5
  16: tauri::plugin::PluginStore<R>::extend_api
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/plugin.rs:855:16
  17: tauri::manager::AppManager<R>::extend_api
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/manager/mod.rs:442:5
  18: tauri::webview::Webview<R>::on_message
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/webview/mod.rs:1258:25
  19: tauri::ipc::protocol::handle_ipc_message
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/ipc/protocol.rs:276:9
  20: tauri::ipc::protocol::message_handler::{{closure}}
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/ipc/protocol.rs:27:36
  21: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/alloc/src/boxed.rs:2036:9
  22: tauri_runtime_wry::create_ipc_handler::{{closure}}
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-2.0.0-beta.20/src/lib.rs:4169:7
  23: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/alloc/src/boxed.rs:2036:9
  24: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/alloc/src/boxed.rs:2036:9
  25: wry::webkitgtk::InnerWebView::attach_ipc_handler::{{closure}}
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wry-0.41.0/src/webkitgtk/mod.rs:527:11
  26: webkit2gtk::auto::user_content_manager::UserContentManagerExt::connect_script_message_received::script_message_received_trampoline
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webkit2gtk-2.0.1/src/auto/user_content_manager.rs:229:7
  27: g_closure_invoke
  28: <unknown>
  29: <unknown>
  30: g_signal_emit_valist
  31: g_signal_emit
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: g_main_context_iteration
  44: gtk_main_iteration_do
  45: gtk::auto::functions::main_iteration_do
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.18.1/src/auto/functions.rs:392:24
  46: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/platform_impl/linux/event_loop.rs:1034:11
  47: glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/main_context.rs:154:12
  48: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/platform_impl/linux/event_loop.rs:932:5
  49: tao::platform_impl::platform::event_loop::EventLoop<T>::run
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/platform_impl/linux/event_loop.rs:886:21
  50: tao::event_loop::EventLoop<T>::run
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/event_loop.rs:211:5
  51: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-2.0.0-beta.20/src/lib.rs:2579:5
  52: tauri::app::App<R>::run
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/app.rs:1059:5
  53: tauri::app::Builder<R>::run
             at /home/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/app.rs:1864:5
  54: tauri_test_cmd::main
             at ./src/main.rs:28:5
  55: core::ops::function::FnOnce::call_once
             at /rustc/1fffb2a355dfee65bf6aa5a9db35f33d3ee93aec/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

In v2, using `async_runtime::spawn` works as expected, but using `tokio::spawn` does not.

Please let me know if you need any additional information or if there are any other tests I can run to help diagnose this issue.

Thank you!

**Comment by amrbashir** [comment]
`tauri::async_runtime::spawn` is the recommended way to spawn tasks because it does ensure that the runtime is initialized and running.
