### ISSUE TITLE
[bug] Crash when a second instance of a tauri app is executed

### ISSUE THREAD

**Issue by vlabo** [tauri-apps/tauri#10387]
### Describe the bug

When an app is running and a second instance of the same app is executed the second instance crashes.
If I change the `"identifier"` (so both instances have different identifiers) in the config the second runs with no issues.

Our use case does not require two instances but we like to have way to notify the first instance so it can take focus.

### Reproduction

Run second instance in the same time while the first is still running

### Expected behavior

The second instance to not crash.

### Full `tauri info` output

```text
cargo tauri info
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Fedora 40 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.5.1
    - pnpm: 9.0.5
    - yarn: 1.22.21
    - npm: 10.8.1
    - bun: 1.1.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../../angular/dist/tauri-builtin
    - devUrl: http://localhost:4100/
```

### Stack trace

```text
RUST_BACKTRACE=full cargo run
   Compiling app v0.1.0 (/home/vladimir/Dev/Safing/portmaster/desktop/tauri/src-tauri)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 19.26s
     Running `target/debug/app`
thread 'main' panicked at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdk-0.18.0/src/auto/display.rs:301:9:
GDK has not been initialized. Call `gdk::init` or `gtk::init` first.
stack backtrace:
   0:     0x55c5701223e5 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x55c5701223e5 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c5701223e5 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55c5701223e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55c5701516bb - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:     0x55c5701516bb - core::fmt::write::hc090a2ffd6b28c4a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:     0x55c57011de9f - std::io::Write::write_fmt::h8898bac6ff039a23
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:     0x55c5701221be - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55c5701221be - std::sys_common::backtrace::print::ha96650907276675e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55c570123849 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
  10:     0x55c57012358d - std::panicking::default_hook::h207342be97478370
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
  11:     0x55c570123ce3 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:795:13
  12:     0x55c570123b8b - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:656:13
  13:     0x55c5701228a9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55c5701238f7 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  15:     0x55c56dccf033 - core::panicking::panic_fmt::hdc63834ffaaefae5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  16:     0x55c56f9bba5c - gdk::auto::display::Display::default::hbaee7119145aff26
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdk-0.18.0/src/rt.rs:22:17
  17:     0x55c56dd233ed - tao::platform_impl::platform::event_loop::EventLoop<T>::new_gtk::hf9fcad376cd521ca
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/platform_impl/linux/event_loop.rs:215:19
  18:     0x55c56dd22e5e - tao::platform_impl::platform::event_loop::EventLoop<T>::new::{{closure}}::h5d30496987807d19
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/platform_impl/linux/event_loop.rs:189:9
  19:     0x55c56e334590 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h275744d5b26e4cde
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/main_context.rs:154:12
  20:     0x55c56dd22da9 - tao::platform_impl::platform::event_loop::EventLoop<T>::new::h88876197475c3b56
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/platform_impl/linux/event_loop.rs:187:5
  21:     0x55c56e68c0b3 - tao::event_loop::EventLoopBuilder<T>::build::habc53cc639602d59
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.28.1/src/event_loop.rs:112:19
  22:     0x55c56e7c1525 - tauri_runtime_wry::Wry<T>::init_with_builder::h4a6a92f62797719e
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-2.0.0-beta.20/src/lib.rs:2268:16
  23:     0x55c56e7ccd4c - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::new_any_thread::h419631d4c494fa5b
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-2.0.0-beta.20/src/lib.rs:2325:5
  24:     0x55c56e43381a - tauri::app::Builder<R>::build::h5fbc4fff8a974605
                               at /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/app.rs:1742:7
  25:     0x55c56e3f4f7d - app::main::h14c16ff122cd013c
                               at /home/vladimir/Dev/Safing/portmaster/desktop/tauri/src-tauri/src/main.rs:117:15
  26:     0x55c56de352bb - core::ops::function::FnOnce::call_once::h8d1eb25dfd59159e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  27:     0x55c56e24e49e - std::sys_common::backtrace::__rust_begin_short_backtrace::he08e8893179fa072
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  28:     0x55c56dfb0631 - std::rt::lang_start::{{closure}}::ha952f9d41cbdb298
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
  29:     0x55c5701156d0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6abeee5a7794ceb5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
  30:     0x55c5701156d0 - std::panicking::try::do_call::hd6e966bb06877057
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  31:     0x55c5701156d0 - std::panicking::try::hc9b3807f5768cb19
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  32:     0x55c5701156d0 - std::panic::catch_unwind::h94a757c154076c6e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  33:     0x55c5701156d0 - std::rt::lang_start_internal::{{closure}}::hc5223fb36050c743
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
  34:     0x55c5701156d0 - std::panicking::try::do_call::hddf7b4e1ebeb3f69
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  35:     0x55c5701156d0 - std::panicking::try::h1842860a1f941a31
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  36:     0x55c5701156d0 - std::panic::catch_unwind::h009016ccf811d4c3
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  37:     0x55c5701156d0 - std::rt::lang_start_internal::h3ed4fe7b2f419135
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
  38:     0x55c56dfb060a - std::rt::lang_start::h05a0a2c5b1af1e1e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
  39:     0x55c56e3f900e - main
  40:     0x7f3be2a39088 - __libc_start_call_main
  41:     0x7f3be2a3914b - __libc_start_main_impl
  42:     0x55c56dccfaf5 - _start
  43:                0x0 - <unknown>

(process:384908): GLib-GIO-WARNING **: 18:30:42.171: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
```

### Additional context

I think this was not an issue on older versions of tauri but I cant say exactly which one.

**Comment by FabianLars** [comment]
Caused by https://github.com/tauri-apps/tauri/pull/9621 - we'll have to put that behind a config.

**Comment by vlabo** [comment]
I can create a PR for it. But I need more details about what is the expected solution.

Config that will enabling/disable setting of the gtk app id? 

Or is there a better way of handling this?  
There is a method [gtk::Application::is_remote()](https://gtk-rs.org/gtk-rs-core/stable/0.15/docs/gio/prelude/trait.ApplicationExt.html#tymethod.is_remote) that will tell if there is an instance with the same app_id is already running.

**Comment by FabianLars** [comment]
> Config that will enabling/disable setting of the gtk app id?

This is what i've had in mind, yes. Fancier/deeper integration with the gtk methods is imo not worth it.
