### ISSUE TITLE
[bug] pnpm tauri dev fails after creating a new project with cargo create-tauri-app --rc

### ISSUE THREAD

**Issue by Weshnaw** [tauri-apps/tauri#10473]
### Describe the bug

I saw that the tauri 2.0.0 RC0 came out and wanted to migrate my projects to it; though I noticed the cargo build failing with the message:
```
error: failed to run custom build command for `tauri v2.0.0-rc.0`

Caused by:
  process didn't exit successfully: `/media/bfall/B426314C263110BA/Code/Project-Book/project-book-htmx-rc/src-tauri/target/debug/build/tauri-4db2e1360184d76e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-check-cfg=cfg(custom_protocol)
  cargo:rustc-check-cfg=cfg(dev)
  cargo:rustc-cfg=dev
  cargo:dev=true
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)

  --- stderr
  thread 'main' panicked at /home/bfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-rc.0/build.rs:378:25:
  failed to define permissions for core:path: failed to write file: Invalid argument (os error 22)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

### Reproduction

- cargo create-tauri-app --rc
  - Project name (tauri-app) › foo
  - TypeScript / JavaScript
  - pnpm
  - Vanilla
  - TypeScript
- cd foo
- pnpm install
- pnpm tauri android init
- pnpm tauri dev
thread 'main' panicked at /home/bfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-rc.0/build.rs:378:25:
  failed to define permissions for core:path: failed to write file: Invalid argument (os error 22)

### Expected behavior

Tauri app to startup

### Full `tauri info` output

```text
❯ pnpm tauri info

> foo@0.0.0 tauri /media/bfall/B426314C263110BA/Code/Project-Book/foo
> tauri "info"


[✔] Environment
    - OS: Pop!_OS 22.04 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.82.0-nightly (fd8d6fbe5 2024-08-02)
    ✔ cargo: 1.82.0-nightly (257b72b8a 2024-07-30)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 20.16.0
    - pnpm: 9.6.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.0
    - tauri-build [RUST]: 2.0.0-rc.0
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
❯ $env.RUST_BACKTRACE = full ; pnpm tauri dev

> foo@0.0.0 tauri /media/bfall/B426314C263110BA/Code/Project-Book/foo
> tauri "dev"

    Running BeforeDevCommand (`pnpm dev`)

> foo@0.0.0 dev /media/bfall/B426314C263110BA/Code/Project-Book/foo
> vite


  VITE v5.3.5  ready in 190 ms

  ➜  Local:   http://localhost:1420/
    Info Watching /media/bfall/B426314C263110BA/Code/Project-Book/foo/src-tauri for changes...
   Compiling gio v0.18.4
   Compiling cairo-rs v0.18.5
   Compiling atk v0.18.0
   Compiling javascriptcore-rs v1.1.2
   Compiling tauri v2.0.0-rc.0
error: failed to run custom build command for `tauri v2.0.0-rc.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/media/bfall/B426314C263110BA/Code/Project-Book/foo/src-tauri/target/debug/build/tauri-4db2e1360184d76e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-check-cfg=cfg(custom_protocol)
  cargo:rustc-check-cfg=cfg(dev)
  cargo:rustc-cfg=dev
  cargo:dev=true
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)

  --- stderr
  thread 'main' panicked at /home/bfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-rc.0/build.rs:378:25:
  failed to define permissions for core:path: failed to write file: Invalid argument (os error 22)
  stack backtrace:
     0:     0x60569d880d2d - std::backtrace_rs::backtrace::libunwind::trace::h0517bc420c07aba1
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
     1:     0x60569d880d2d - std::backtrace_rs::backtrace::trace_unsynchronized::h9eb2bf97ded801f9
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x60569d880d2d - std::sys::backtrace::_print_fmt::h848403c9f6c6acd3
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/sys/backtrace.rs:66:9
     3:     0x60569d880d2d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h3e1aac30b48979f0
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/sys/backtrace.rs:39:26
     4:     0x60569d8a3c8b - core::fmt::rt::Argument::fmt::hfd5ab458b6b90810
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/core/src/fmt/rt.rs:173:76
     5:     0x60569d8a3c8b - core::fmt::write::h8d76617bdb457b1d
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/core/src/fmt/mod.rs:1178:21
     6:     0x60569d87e033 - std::io::Write::write_fmt::h91c0111a9511d003
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/io/mod.rs:1823:15
     7:     0x60569d881ee2 - std::sys::backtrace::BacktraceLock::print::h60bd8f4955f5674c
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/sys/backtrace.rs:42:9
     8:     0x60569d881ee2 - std::panicking::default_hook::{{closure}}::h9e25f8a6b9466506
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:266:22
     9:     0x60569d881b4e - std::panicking::default_hook::hac4d7c83a89e4985
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:293:9
    10:     0x60569d88278f - std::panicking::rust_panic_with_hook::hc0f61e6a3d8b1f35
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:797:13
    11:     0x60569d882477 - std::panicking::begin_panic_handler::{{closure}}::h52ee072755f4196d
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:671:13
    12:     0x60569d881219 - std::sys::backtrace::__rust_end_short_backtrace::h25ea4b4e004c5cc9
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/sys/backtrace.rs:170:18
    13:     0x60569d882104 - rust_begin_unwind
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:662:5
    14:     0x60569d8a25c3 - core::panicking::panic_fmt::hfbb4ee5366c530eb
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/core/src/panicking.rs:74:14
    15:     0x60569d6b01d9 - build_script_build::define_permissions::{{closure}}::h455f0454174abccd
    16:     0x60569d6aad51 - core::result::Result<T,E>::unwrap_or_else::h998648aa2f947269
    17:     0x60569d6afad0 - build_script_build::define_permissions::he9932be1c8b97c3b
    18:     0x60569d6aec83 - build_script_build::main::h30fc205701a05c38
    19:     0x60569d6a9813 - core::ops::function::FnOnce::call_once::h91bd4350d717f244
    20:     0x60569d6a8ed6 - std::sys::backtrace::__rust_begin_short_backtrace::h8e58523dabc2c5cc
    21:     0x60569d6a8d89 - std::rt::lang_start::{{closure}}::h27587fe9c702ddad
    22:     0x60569d87a310 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he4a68c67338aca40
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/core/src/ops/function.rs:284:13
    23:     0x60569d87a310 - std::panicking::try::do_call::hc500ab4b8aff7257
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:554:40
    24:     0x60569d87a310 - std::panicking::try::h1941c51233126404
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:518:19
    25:     0x60569d87a310 - std::panic::catch_unwind::habde33aad0e34c95
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panic.rs:345:14
    26:     0x60569d87a310 - std::rt::lang_start_internal::{{closure}}::hb3b9db7ec2da3dd8
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/rt.rs:143:48
    27:     0x60569d87a310 - std::panicking::try::do_call::h87fa9538e0b32847
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:554:40
    28:     0x60569d87a310 - std::panicking::try::h64cadd08c2ada699
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panicking.rs:518:19
    29:     0x60569d87a310 - std::panic::catch_unwind::hd393b3f9aae58f66
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/panic.rs:345:14
    30:     0x60569d87a310 - std::rt::lang_start_internal::he6f16cf89d2f7057
                                 at /rustc/fd8d6fbe505ecf913f5e2ca590c69a7da2789879/library/std/src/rt.rs:143:20
    31:     0x60569d6a8d67 - std::rt::lang_start::had4afb6ecb728339
    32:     0x60569d6b06e5 - main
    33:     0x7266bc629d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    34:     0x7266bc629e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    35:     0x60569d6a6c45 - _start
    36:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
 ELIFECYCLE  Command failed.
 ELIFECYCLE  Command failed with exit code 101.
```

### Additional context

I went so far as to `rm -r ~/.cargo/registry/` in case it was just some random bug in how cargo downloaded the package.

I have an older project which does not fail to build using 
```
[✔] Environment
    - OS: Pop!_OS 22.04 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.82.0-nightly (fd8d6fbe5 2024-08-02)
    ✔ cargo: 1.82.0-nightly (257b72b8a 2024-07-30)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.16.0
    - pnpm: 9.6.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by chippers** [comment]
Could not reproduce on `aarch64-apple-darwin`, will try in an aarch64 linux session, and see if i can get my hands on a x64 linux machine if i can't reproduce it on there.
Can you tell me the output of `cargo create-tauri-app --version`? I had `4.1.0`.
[![asciicast](https://asciinema.org/a/zzwYZBmajKwBxe1hTyzQDWaJm.svg)](https://asciinema.org/a/zzwYZBmajKwBxe1hTyzQDWaJm)

**Comment by chippers** [comment]
Unable to reproduce on `aarch64-unknown-linux-gnu`. I am traveling right now so only have my laptop. I can test on a x64 machine in a few days.

[![asciicast](https://asciinema.org/a/uecH2iFHFz6t5Uco5YDEvt7CP.svg)](https://asciinema.org/a/uecH2iFHFz6t5Uco5YDEvt7CP)

**Comment by chippers** [comment]
looking closer at your `tauri info` command, it looks like some packages are still using `beta`, make sure to update them to the latest.

Try the migrate command:
```
cargo install tauri-cli --version "^2.0.0-rc"
cargo tauri migrate
```

**Comment by Weshnaw** [comment]
❯ cargo create-tauri-app --version
4.1.0
After running 
cargo install tauri-cli --version "^2.0.0-rc"
cargo tauri migrate

on the fresh foo folder I created for the minimal reproduction I still receive the error


I do want to note that as far as I could tell the only ones with the beta dependencies are my original project that has not been updated and still works, but for the brand new one, and the one I created as a minimal reproduction 
```
❯ pnpm tauri info

> foo@0.0.0 tauri /media/bfall/B426314C263110BA/Code/Project-Book/foo
> tauri "info"


[✔] Environment
    - OS: Pop!_OS 22.04 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.82.0-nightly (fd8d6fbe5 2024-08-02)
    ✔ cargo: 1.82.0-nightly (257b72b8a 2024-07-30)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 20.16.0
    - pnpm: 9.6.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.0
    - tauri-build [RUST]: 2.0.0-rc.0
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

I don't see where the beta is still being used

**Comment by Weshnaw** [comment]
I did uncover that it may be due to me running the code under a linux mount, as when I tried a folder under my home directory it actually works, though I'm not sure how / why that would be effecting things, and why the beta works but the RC does not.

mount details
`/dev/nvme0n1p3 on /media/bfall/B426314C263110BA type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)`

**Comment by fu050409** [comment]
@Weshnaw Hi! Have you changed your linux permissions of the mount directory? I found that the error code is 22, this means there's must a path invalid error or permission error.

I looked up the source code of tauri, they only changed `permissions_out_dir` from:

```rust
// last beta version
let permissions_out_dir = out_dir.join("permissions").join(plugin);
let autogenerated =
  permissions_out_dir.join(tauri_utils::acl::build::AUTOGENERATED_FOLDER_NAME);
```

to:

```rust
// rc.0
let plugin_directory_name = plugin.strip_prefix("core:").unwrap_or(plugin);
let permissions_out_dir = out_dir.join("permissions").join(plugin_directory_name);
let autogenerated =
  permissions_out_dir.join(tauri_utils::acl::build::AUTOGENERATED_FOLDER_NAME);
```

The only change is to make sure `plugin_directory_name` not starts with `core:`, in other words I think this cannot cause any new exceptions or different work between beta version and release candidate version.

**Comment by Weshnaw** [comment]
I created the new tauri project in the same directory as the previous project, that also contains the beta version project, and I didnt mess with any of the permissions

**Comment by fu050409** [comment]
Ahh..It's odd. Are you root?

**Comment by lucasfernog** [comment]
I believe #10485 fixed this one. I'll trigger a new release.

**Comment by Weshnaw** [comment]
> Ahh..It's odd. Are you root?

My account has sudo access, but I was not running any commands as sudo or from root directly, but based on quickly comparing that PR that lucasfernog mentioned with the error message I feel like that file issue definitely looks like it should be the culprit, I'm not an expert on Linux but I could see it just being weird path issues with the mount type

**Comment by Weshnaw** [comment]
> I believe #10485 fixed this one. I'll trigger a new release.

sorry for the delayed response, I'm guessing this was the issue as updating to the latest RC resolves the issue!

Thank you
