### ISSUE TITLE
[docs] WebDriver (Selenium and WebdriverIO) e2e testing does not work.

### ISSUE THREAD

**Issue by ospfranco** [tauri-apps/tauri#10670]
I'm trying to setup end-to-end tests for Tauri. I've followed the [official documentation](https://tauri.app/v1/guides/testing/webdriver/example/selenium) but when I try to start my tests I get the following error:

```
** (pulsar:12894): WARNING **: 06:38:47.744: Disabled hardware acceleration because GTK failed to initialize GL: Unable to create a GL context.

** (pulsar:12894): WARNING **: 06:38:47.751: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (741ms)
  2 failing

  1) "before all" hook in "{root}":
     SessionNotCreatedError: Failed to match capabilities
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:514:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) "after all" hook in "{root}":
     TypeError: Cannot read properties of undefined (reading 'quit')
      at Context.<anonymous> (test/test.js:47:16)
      at process.processImmediate (node:internal/timers:483:21)
```

The application starts correctly when I launch it manually. But fails without a reason in the selenium test. Any idea what could be wrong or how can I get a more descriptive error? Are the docs up-to-date? Migration to v2 is not possible for us at the moment, just need to get the tests running, any help is much appreciated.

**Comment by ospfranco** [comment]
I decided to give webdriverio a test. Again following the official docs. This time it gets further. The app starts and there is some console output. But the tests never start running. Am I missing something?

![OSP 000215](https://github.com/user-attachments/assets/a2e337bc-9640-401e-93de-89912e93061a)
> My app starts and when I minimize it I see on the console nothing is running.

**Comment by ospfranco** [comment]
I have tried updating the wdio dependencies to the latest versions, but I get other errors.

Any feedback @FabianLars ?

![OSP 000251](https://github.com/user-attachments/assets/e92d7a4e-eb4a-4e47-bb62-c5abd30e4395)

**Comment by ospfranco** [comment]
When I leave the test running my linux vm hangs and dies. But I've manage to retrieve a log where there is a request failure:

```
debian@debian:~/Developer/pulsar/wdio$ yarn test

Execution of 1 workers started at 2024-08-24T12:59:11.703Z

2024-08-24T12:59:11.710Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-08-24T12:59:11.710Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-24T12:59:11.711Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2024-08-24T12:59:11.861Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in undefined - /test/specs/example.e2e.js
[0-0] 2024-08-24T12:59:11.902Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-08-24T12:59:11.919Z INFO webdriver: [POST] http://localhost:4444/session
[0-0] 2024-08-24T12:59:11.919Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { 'tauri:options': [Object] }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: {
[0-0]     'tauri:options': {
[0-0]       application: '../src-tauri/target/release/pulsar',
[0-0]       webviewOptions: {}
[0-0]     }
[0-0]   }
[0-0] }
[0-0] "/home/debian/Developer/pulsar/src-tauri/target/release/nebula/backends/llama_cpp/llama-cpp-sys/dist"
[0-0] libEGL warning: egl: failed to create dri2 screen
[0-0] 
[0-0] ** (pulsar:7355): WARNING **: 05:59:12.093: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
[0-0] libEGL warning: egl: failed to create dri2 screen
[0-0] [2024-08-24][12:59:12][INFO][a7@tauri://localhost/assets/index-BztbfkBh.js:43:675] [Model Manager] has no local models
[0-0] [2024-08-24][12:59:13][ERROR][a7@tauri://localhost/assets/index-BztbfkBh.js:43:675] [Updates] the platform `linux-aarch64` was not found on the response `platforms` object
[0-0] 2024-08-24T13:01:12.035Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2024-08-24T13:01:12.038Z INFO webdriver: Retrying 1/3
[0-0] 2024-08-24T13:01:12.038Z INFO webdriver: [POST] http://localhost:4444/session
[0-0] 2024-08-24T13:01:12.038Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { 'tauri:options': [Object] }, firstMatch: [ {} ] },
[0-0]   desiredCapabilities: {
[0-0]     'tauri:options': {
[0-0]       application: '../src-tauri/target/release/pulsar',
[0-0]       webviewOptions: {}
[0-0]     }
[0-0]   }
[0-0] }
[0-0] "/home/debian/Developer/pulsar/src-tauri/target/release/nebula/backends/llama_cpp/llama-cpp-sys/dist"
[0-0] libEGL warning: egl: failed to create dri2 screen
```

You can see there is a `Request timed out!` response. When I call the endpoint `http://localhost:4444/session` manually I do get a response:

```
debian@debian:~/Developer/pulsar/wdio$ curl -X POST http://localhost:4444/session -H "Content-Type: application/json" -d "{\"capabilities\":{\"alwaysMatch\":{\"tauri:options\":{}},\"
firstMatch\":[{}]},\"desiredCapabilities\":{\"tauri:options\":{\"application\":\"../src-tauri/target/release/pulsar\",\"webviewOptions\":{}}}}"
{"value":{"sessionId":"be344bce-7ba2-492a-923f-b39062057565","capabilities":{"browserName":"MiniBrowser","browserVersion":"2.44.2","platformName":"linux","acceptInsecureCerts":false,"strictFileInteractability":false,"setWindowRect":true,"unhandledPromptBehavior":"dismiss and notify","pageLoadStrategy":"normal","proxy":{},"timeouts":{"script":30000,"pageLoad":300000,"implicit":0}}}}
```

Maybe the script is missing permissions? I need another console?

**Comment by sjconstantin** [comment]
I am seeing similar behavior

**Comment by bukowa** [comment]
Here are capabilities that work for me without `tauri-driver` wrapper https://github.com/bukowa/tauri-e2e/blob/605a3ec1a3dbce14105d1a8576a1aa7f6fd34dfd/selenium/javascript/src/selenium/webkitgtk2.ts

**Comment by bicarlsen** [comment]
I'm running into issues here, too.

**Comment by sjconstantin** [comment]
It is working for me now in V2.  However I need to use the 7.9.X version of wdio.  It does not work with latest.

    "@wdio/cli": "^7.9.1",
    "@wdio/local-runner": "^7.9.1",
    "@wdio/mocha-framework": "^7.9.1",
    "@wdio/spec-reporter": "^7.9.0",

**Comment by bicarlsen** [comment]
With `wdio` version `^9.5` I was running into parsing errors with the options, which I fixed with PR #12383. After this fix I received the error
```
Error: Failed to create session.
WebDriverError: session not created: Microsoft Edge failed to start: crashed.
(session not created: DevToolsActivePort file doesn't exist)
```
To resolve this I set the `tauri:options > webviewOptions > userDataFolder` to a folder I controlled and added a `DevToolsActivePort` file as suggested by [this SO answer](https://stackoverflow.com/a/62545820/2961550).

When running, the app briefly opens, then closes and I get the error
```
win_util.cc(1295)] failed to set WebView dpi awareness of 2: The segment is already unlocked.
```
which I haven't been able to resolve.

---
With `wdio` versions `^7.9` I receive the error
```
@wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
```

**Comment by Haprog** [comment]
Here's my attempt to use WebDriverIO for testing a Tauri 2 app: https://github.com/Haprog/tauri-wdio-win-test/

I was able to get it somehow working locally but I was very unhappy about the complex setup and the need for a bunch of outdated dependencies to get around errors. Also I wanted to get this running in a Windows runner based GitHub Actions workflow, but ran into a problem that even if my test runs ok locally and webdriver seems to run even in CI, in the CI side it looks like the Tauri web view page is empty and it's very difficult to get any meaningful debug output or logs from the CI related to this.

I gave up with testing Tauri using a WebDriver.

Then for another testing approach I tried setting up Playwright over CDP (Chrome DevTools Protocol) and enabling CDP in the Tauri app and this actually seems to work very well and with a very simple setup (without ugly hacks or outdated dependencies).

The only downside is that (afaik) this only works on Windows where Tauri 2 uses Edge WebView2. However it woiuld be helpful to have this approach also documented on the Tauri site since the tauri-driver/WebDriver approach is a mess right now.

I setup two example repositories which demonstrate this simpler testing approach using CDP and Playwright if somebody wants to have a look.

- https://github.com/Haprog/tauri-cdp - Tauri 2 app template that has CDP enabled in debug builds on Windows
- https://github.com/Haprog/playwright-cdp - A simple Playwright test setup example which uses CDP to connect to a page that is already running (for example in a Tauri 2 web view on Windows). Has few simple tests that pass when run against the above app example.

**Comment by Haprog** [comment]
Looks like the Tauri [WebDriver example](https://github.com/tauri-apps/webdriver-example) and [documentation](https://v2.tauri.app/develop/tests/webdriver/example/webdriverio/) has been recently updated on 2025-08-11 (uses `wdio` v9 now)
See https://github.com/tauri-apps/tauri/issues/9203#issuecomment-3228684154

**Comment by duaneking** [comment]
Just want to add my voice to this ; The current web driver example is impossible to work with and does not work; And to be frank the fact that it's not simply using cargo commands and uses this stupid wrapper That seems designed to obfuscate how you get the driver to actually work just makes it worse.

**Comment by srsholmes** [comment]
For anyone landing here looking for an alternative — I built a Playwright-based testing setup for Tauri that doesn't rely on WebDriver or tauri-driver at all. It uses a Rust plugin that embeds a socket server in your app, so Playwright talks to the webview directly.

Three modes: browser (headless + mocked IPC), tauri (real app via socket bridge), and cdp (WebView2 on Windows).

https://github.com/srsholmes/tauri-playwright

Available on npm and crates.io. Hope it's useful to someone here!
