### ISSUE TITLE
[bug] [2.0] Can't build for Android - WryActivity.kt --> inferred type is String?

### ISSUE THREAD

**Issue by oddpxl** [tauri-apps/tauri#10720]
### Describe the bug

Build fail

### Reproduction

pnpm tauri android dev

..and I get this:

.../WryActivity.kt:43:24 Type mismatch: inferred type is String? but String was expected
.../WryActivity.kt:51:24 Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

### Expected behavior

Build as usual.

### Full `tauri info` output

```text
tauri-mobile-neo@0.0.0 tauri /Users/odd/Documents/odd_LLM_rust/frodd
> tauri "info"


[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.4.1
    - pnpm: 8.15.5
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.5
    - tauri-build [RUST]: 2.0.0-rc.5
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.1
    - tauri-cli [RUST]: 1.5.11
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-rc.4

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by oddpxl** [comment]
Just realised...

If before compile I edit WryActivity.kt at line 40...   I can get it to compile.
( obviously this file is re-generated so I have to do it for every compile lol )

 ```
  try {
                @Suppress("DEPRECATION")
                val info = packageManager.getPackageInfo(webViewPackage, 0)
                return info.versionName.toString()
            } catch (ex: Exception) {
                Logger.warn("Unable to get package info for '$webViewPackage'$ex")
            }

            try {
                @Suppress("DEPRECATION")
                val info = packageManager.getPackageInfo("com.android.webview", 0)
                return info.versionName.toString()
            } catch (ex: Exception) {
                Logger.warn("Unable to get package info for 'com.android.webview'$ex")
            }
            
            

```

**Comment by oddpxl** [comment]
When I try to build with Android studio I get panic at src/mobile/mod.rs:243:6...    ..which seems similar to https://github.com/tauri-apps/tauri/issues/10728


```
> tauri "android" "android-studio-script" "--target" "aarch64"

thread '<unnamed>' panicked at src/mobile/mod.rs:243:6:
failed to read CLI options: Error when opening the TCP socket: Connection refused (os error 61)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Error Tauri CLI unexpected panic
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by oddpxl** [comment]
Deleted my entire folder and cloned previous version - problem now gone.
