### ISSUE TITLE
[bug] WebviewWindow.getByLabel fails when none created

### ISSUE THREAD

**Issue by siler** [tauri-apps/tauri#11047]
### Describe the bug

In JS, calling `WebviewWindow.getByLabel` results in a TypeError.

### Reproduction

Create a new app and call `WebviewWindow.getByLabel(...)` from js.

### Expected behavior

The function should return null, or the WebviewWindow when it exists.

### Full `tauri info` output

```text
$ pnpm tauri info

> rxr@0.1.0 tauri D:\workspace\rxr
> tauri "info"


[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 128.0.2739.79
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.6.1
    - pnpm: 9.10.0
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.0-rc.15
    - tauri-build 🦀: 2.0.0-rc.12
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - @tauri-apps/api : 2.0.0-rc.0
    - @tauri-apps/cli : 2.0.0-rc.12

[-] Plugins
    - tauri-plugin-fs 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-dialog 🦀: 2.0.0-rc.7
    - @tauri-apps/plugin-dialog : 2.0.0-rc.1
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
webviewWindow.js:25  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at getAllWebviewWindows (webviewWindow.js:25:57)
    at _WebviewWindow.getByLabel (webviewWindow.js:84:31)
    at onClick (SourceLink.tsx?t=1726637165665:55:35)
    at overrideProps.<computed> (Slot.tsx:106:11)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
```

### Additional context

My permissions include: 
```
"core:webview:default",
"core:webview:allow-create-webview-window",
"core:webview:allow-get-all-webviews",
```

**Comment by FabianLars** [comment]
Try updating `@tauri-apps/api` to the latest rc version. tauri info says it's still on rc.0 which should be the issue here (your tauri rust crates are on their latest versions and there were updates to how the window apis work)

**Comment by siler** [comment]
That was it, thank you! I expected `pnpm upgrade` to deal with that for me but I guess it doesn't understand RC versions.
