### ISSUE TITLE
[bug] TAURI_ANDROID_PACKAGE_UNESCAPED not set

### ISSUE THREAD

**Issue by clouds56** [tauri-apps/tauri#11332]
### Describe the bug

update tauri to 2.0.3, run `yarn tauri android dev`, it failed to build with error
```sh
  --- stderr
  thread 'main' panicked at /home/clouds/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.3/build.rs:265:9:
  `TAURI_ANDROID_PACKAGE_UNESCAPED` is not set, which is needed to generate the kotlin files for android.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
     1: core::panicking::panic_fmt
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
     2: build_script_build::main::env_var::{{closure}}
               at ./build.rs:265:9
     3: core::result::Result<T,E>::unwrap_or_else
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1456:23
     4: build_script_build::main::env_var
               at ./build.rs:264:7
     5: build_script_build::main
               at ./build.rs:302:31
     6: core::ops::function::FnOnce::call_once
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Full `tauri info` output

```text
yarn run v1.22.22
$ tauri info

[✔] Environment
    - OS: Ubuntu 24.10.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.1
    ✔ rsvg2: 2.59.1
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.20.1
    - yarn: 1.22.22
    - npm: 9.2.0
    - bun: 1.1.7

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.0
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by clouds56** [comment]
update @tauri-apps/cli to 2.0.3 and fixed.

**Comment by JeftavanderHorst** [comment]
I'm still getting this issue on version 2.0.3 of @tauri-apps/cli (after upgrading from the RC versions), are there other steps I need to take?

**Comment by clouds56** [comment]
@JeftavanderHorst which command line do you use to run tauri?
`npm run tauri android dev/yarn tauri android dev`: this would use `@tauri-apps/cli`,
`tauri android dev`: if you use this, you might also like to upgrade tauri-cli via `cargo install --force tauri-cli`
