### ISSUE TITLE
[bug] Tauri + Dioxus App Crash on macos with 2.0

### ISSUE THREAD

**Issue by nandy007** [tauri-apps/tauri#11340]
### Describe the bug

running cargo tauri dev on mac and get error for：

thread 'main' panicked at /xxx/objc2-app-kit-0.2.2/src/generated/NSApplication.rs:325:1:
invalid message send to -[TaoApp activate]: method not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 13.6.9 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.10.0
    - yarn: 1.22.19
    - npm: 10.2.3

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.0
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

**Comment by huazaierli** [comment]
+1

**Comment by jaydanluo** [comment]
+1

**Comment by wangml-gitbub** [comment]
+1

**Comment by li-yu-tfs** [comment]
+ 1

**Comment by arek-e** [comment]
+1

**Comment by amrbashir** [comment]
Can you all please stop commenting `+1`? This is not gonna rush anything and only wastes my time when I check the notifications from this thread.


Helpful comments goes like this "Hey, I face the same problem and I managed to get this stack trace <insert stack trace>", or "I tried doing X and failed, here is the errors I got"

**Comment by li-yu-tfs** [comment]
Hey, I face the same problem and I managed to get this stack trace 

```
thread 'main' panicked at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-app-kit-0.2.2/src/generated/NSApplication.rs:325:1:
invalid message send to -[TaoApp activate]: method not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10547d334 - std::backtrace_rs::backtrace::libunwind::trace::hbebc8679d47bdc2c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x10547d334 - std::backtrace_rs::backtrace::trace_unsynchronized::h3a2e9637943241aa
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10547d334 - std::sys::backtrace::_print_fmt::he430849680584674
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:        0x10547d334 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:        0x10549f208 - core::fmt::rt::Argument::fmt::h0d339881c25f3c31
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:        0x10549f208 - core::fmt::write::hb3cfb8a30e72d7ff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:        0x105478cdc - std::io::Write::write_fmt::hfb2314975de9ecf1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:        0x10547e5b0 - std::sys::backtrace::BacktraceLock::print::he14461129ccbfef5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:        0x10547e5b0 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:        0x10547e1d4 - std::panicking::default_hook::hc62e60da3be2f352
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:        0x10547f074 - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:        0x10547e99c - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
  12:        0x10547d7c0 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:        0x10547e68c - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:        0x10550d2c4 - core::panicking::panic_nounwind_fmt::runtime::h5290ab2b4897aadc
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:112:18
  15:        0x10550d2c4 - core::panicking::panic_nounwind_fmt::h91ee161184879b56
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:122:5
  16:        0x10550d33c - core::panicking::panic_nounwind::heab7ebe7a6cd845c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:221:5
  17:        0x10550d4b4 - core::panicking::panic_cannot_unwind::hedc43d82620205bf
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:309:5
  18:        0x104b41a28 - tao::platform_impl::platform::app_delegate::did_finish_launching::hec7bc89767e23cb3
                               at /Users/liyu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.3/src/platform_impl/macos/app_delegate.rs:103:1
  19:        0x1ab3bb180 - <unknown>
  20:        0x1ab456eec - <unknown>
  21:        0x1ab456e34 - <unknown>
  22:        0x1ab38c4cc - <unknown>
  23:        0x1ac2ea8e4 - <unknown>
  24:        0x1ae5f2d90 - <unknown>
  25:        0x1ae5f2b40 - <unknown>
  26:        0x1ae5f0bdc - <unknown>
  27:        0x1ae5f07d8 - <unknown>
  28:        0x1ac314b54 - <unknown>
  29:        0x1ac3149b4 - <unknown>
thread caused non-unwinding panic. aborting.
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by amrbashir** [comment]
Are you all using a dioxus app created from `create-tauri-app` tool?

**Comment by nandy007** [comment]
> Are you all using a dioxus app created from `create-tauri-app` tool?

@amrbashir 

yes, i run the bash  with `sh <(curl https://create.tauri.app/sh)` and select rust for frontend language + dioxus framework

then, run `cargo tauri dev` and get the error

**Comment by amrbashir** [comment]
@nandy007 try again and see if it is fixed

**Comment by leonbeon** [comment]
I got this same error on MacOS 13.5 when trying to run my migrated Tauri 1 project. The codebase runs fine on Windows.

Error:
```
thread 'main' panicked at /Users/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-app-kit-0.2.2/src/generated/NSApplication.rs:325:1:
invalid message send to -[TaoApp activate]: method not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x1046e1dfc - std::backtrace_rs::backtrace::libunwind::trace::h1c3451b342542f10
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x1046e1dfc - std::backtrace_rs::backtrace::trace_unsynchronized::h3743cad8cc2d54de
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1046e1dfc - std::sys::backtrace::_print_fmt::h31ad576fee12d4ee
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:        0x1046e1dfc - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:        0x104703338 - core::fmt::rt::Argument::fmt::h54965d9b1ee82264
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:        0x104703338 - core::fmt::write::ha36a8060c13608ea
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:        0x1046ddac8 - std::io::Write::write_fmt::h431832c8ebcc85c9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:        0x1046e3110 - std::sys::backtrace::BacktraceLock::print::hd085ca0c3911e184
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:        0x1046e3110 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:        0x1046e2cc0 - std::panicking::default_hook::h4ebc6eb4ae179807
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:        0x1046e3b8c - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:        0x1046e3590 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:664:13
  12:        0x1046e22c0 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:        0x1046e3280 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:        0x10473eb7c - core::panicking::panic_nounwind_fmt::runtime::hed7cc75ebcf8d970
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:112:18
  15:        0x10473eb7c - core::panicking::panic_nounwind_fmt::hb2df5b6c3d6ab15b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:122:5
  16:        0x10473ebf4 - core::panicking::panic_nounwind::h6b53a509f430e184
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:221:5
  17:        0x10473ed6c - core::panicking::panic_cannot_unwind::hce6968fadcdebaaa
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:310:5
  18:        0x10418a8bc - tao::platform_impl::platform::app_delegate::did_finish_launching::hd8831dd5d7da39bf
                               at /Users/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.3/src/platform_impl/macos/app_delegate.rs:103:1
  19:        0x19840b180 - <unknown>
  20:        0x1984a6eec - <unknown>
  21:        0x1984a6e34 - <unknown>
  22:        0x1983dc4cc - <unknown>
  23:        0x19933a8e4 - <unknown>
  24:        0x19b642d90 - <unknown>
  25:        0x19b642b40 - <unknown>
  26:        0x19b640bdc - <unknown>
  27:        0x19b6407d8 - <unknown>
  28:        0x199364b54 - <unknown>
  29:        0x1993649b4 - <unknown>
thread caused non-unwinding panic. aborting.
```


`cargo tauri info`:
```
[✔] Environment
    - OS: Mac OS 13.5.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.6.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.0
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.3

[-] Plugins
    - tauri-plugin-store 🦀: 2.0.1
    - tauri-plugin-http 🦀: 2.0.1
    - tauri-plugin-os 🦀: 2.0.1
    - tauri-plugin-updater 🦀: 2.0.2
    - tauri-plugin-process 🦀: 2.0.1
    - tauri-plugin-persisted-scope 🦀: 2.0.1
    - tauri-plugin-shell 🦀: 2.0.1
    - tauri-plugin-dialog 🦀: 2.0.1
    - tauri-plugin-fs 🦀: 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
```

**Comment by amrbashir** [comment]
@leonbeon make sure to run `cargo update -p wry` in `src-tauri`

**Comment by nandy007** [comment]
> @nandy007 try again and see if it is fixed

@amrbashir yes, I successfully ran the project, thanks!
