### ISSUE TITLE
[bug] creating a project cause thread panic

### ISSUE THREAD

**Issue by Phaired** [tauri-apps/tauri#11615]
### Describe the bug

The problem is when creating a brand new project I got some issue to run it
```
> test@0.1.0 tauri /path/to/Developer/DofusFM2/test
> tauri "dev"

thread '<unnamed>' panicked at crates/tauri-cli/src/helpers/app_paths.rs:117:5:
Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json`, `tauri.conf.json5` or `Tauri.toml` file in any subfolder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed.
zsh: abort      pnpm tauri dev
```
```
pwd
/Users/name/Developer/FM2/test
```

Talked with @FabianLars on discord and it looked like forcing the cli version on both cargo and pnpm to tauri-cli 2.0.3 fix the issue

### Reproduction

```
pnpm create tauri-app
✔ Project name · test
✔ Identifier · com.test.app
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, deno, bun)
✔ Choose your package manager · pnpm
✔ Choose your UI template · React - (https://react.dev/)
✔ Choose your UI flavor · TypeScript

Template created! To get started, run:
  cd test
  pnpm install
  pnpm tauri android init
  pnpm tauri ios init

For Desktop development, run:
  pnpm tauri dev

For Android development, run:
  pnpm tauri android dev

For iOS development, run:
  pnpm tauri ios dev
```
```
cd test
pnpm i
 WARN  GET https://registry.npmjs.org/@tauri-apps%2Fcli error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
Packages: +71
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 119, reused 71, downloaded 0, added 71, done

dependencies:
+ @tauri-apps/api 2.0.3
+ @tauri-apps/plugin-shell 2.0.1
+ react 18.3.1
+ react-dom 18.3.1

devDependencies:
+ @tauri-apps/cli 2.0.4
+ @types/react 18.3.12
+ @types/react-dom 18.3.1
+ @vitejs/plugin-react 4.3.3
+ typescript 5.6.3
+ vite 5.4.10

Done in 14s
```
```
pnpm tauri dev

> test@0.1.0 tauri /path/to/Developer/DofusFM2/test
> tauri "dev"

thread '<unnamed>' panicked at crates/tauri-cli/src/helpers/app_paths.rs:117:5:
Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json`, `tauri.conf.json5` or `Tauri.toml` file in any subfolder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed.
zsh: abort      pnpm tauri dev
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.0.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.1
    - pnpm: 9.11.0
    - yarn: 1.22.22
    - npm: 10.2.4
    - bun: 1.1.34

[-] Packages
    - tauri-cli 🦀: 2.0.4
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins

[-] App
```

**Comment by amrbashir** [comment]
is this still an issue with latest tauri cli release?

**Comment by kerwin612** [comment]
> is this still an issue with latest tauri cli release?

same issue here too

```cmd
> tauri "info"


[✘] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 130.0.2849.56
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - pnpm: 8.15.4
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri-cli 🦀: 2.1.0
    - @tauri-apps/api : 2.1.0 (outdated, latest: 2.1.1)
    - @tauri-apps/cli : 2.1.0

[-] Plugins

[-] App

```  

```cmd
> tauri "dev"

thread '<unnamed>' panicked at crates\tauri-cli\src\helpers\app_paths.rs:119:5:
Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json`, `tauri.conf.json5` or `Tauri.toml` file in any subfolder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed with exit code 3221226505.
```

**Comment by amrbashir** [comment]
@kerwin612 can you share the project that has this issue?

**Comment by kerwin612** [comment]
> @kerwin612 can you share the project that has this issue?

sure, see: https://github.com/kerwin612/PortableRunner/tree/react

**Comment by amrbashir** [comment]
I can't reproduce, are you using `TAURI_APP_PATH` env variable?

**Comment by kerwin612** [comment]
> I can't reproduce, are you using `TAURI_APP_PATH` env variable?

no

**Comment by kerwin612** [comment]
What else can I provide for you to troubleshoot? I'm stuck on this issue and hope we can pinpoint the problem.

**Comment by kerwin612** [comment]
If necessary, I can grant you remote desktop access to my computer for any necessary operations.

**Comment by amrbashir** [comment]
try running with `-vvv` and post logs here, maybe I can spot anything

**Comment by kerwin612** [comment]
```cmd
> tauri "dev" "-vvv"

    Debug [ignore::gitignore] opened gitignore file: C:\.kerwin612\.home\AppData\Local\Temp\.gitignore
    Debug [globset] built glob set; 0 literals, 2 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
    Debug [ignore::gitignore] opened gitignore file: \\?\E:\.env\.gitignore
    Debug [globset] glob converted to regex: Glob { glob: "**/*", re: "(?-u)^(?:/?|.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: ".common/**/*", re: "(?-u)^\\.common(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('.'), Literal('c'), Literal('o'), Literal('m'), Literal('m'), Literal('o'), Literal('n'), RecursiveZeroOrMore, ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: ".linux/**/*", re: "(?-u)^\\.linux(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('.'), Literal('l'), Literal('i'), Literal('n'), Literal('u'), Literal('x'), RecursiveZeroOrMore, ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: ".win/**/*", re: "(?-u)^\\.win(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('.'), Literal('w'), Literal('i'), Literal('n'), RecursiveZeroOrMore, ZeroOrMore]) }     
    Debug [globset] built glob set; 0 literals, 4 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 4 regexes
    Debug [ignore::gitignore] opened gitignore file: \\?\E:\.env\.git\info\exclude   
    Debug [ignore::gitignore] opened gitignore file: \\?\E:\.env\.win\.gitignore     
    Debug [globset] glob converted to regex: Glob { glob: "**/*", re: "(?-u)^(?:/?|.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: ".vsc/**/*", re: "(?-u)^\\.vsc(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('.'), Literal('v'), Literal('s'), Literal('c'), RecursiveZeroOrMore, ZeroOrMore]) }     
    Debug [globset] glob converted to regex: Glob { glob: ".home/**/*", re: "(?-u)^\\.home(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('.'), Literal('h'), Literal('o'), Literal('m'), Literal('e'), RecursiveZeroOrMore, ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "ws/**/*", re: "(?-u)^ws(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('w'), Literal('s'), RecursiveZeroOrMore, ZeroOrMore]) }
    Debug [globset] built glob set; 0 literals, 4 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 4 regexes
    Debug [ignore::gitignore] opened gitignore file: \\?\E:\.env\.win\ws\.gitignore  
    Debug [globset] glob converted to regex: Glob { glob: "**/*", re: "(?-u)^(?:/?|.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, ZeroOrMore]) }
    Debug [globset] built glob set; 0 literals, 3 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
    Debug [ignore::gitignore] opened gitignore file: E:\.env\.win\ws\PortableDesktop\.gitignore
    Debug [globset] glob converted to regex: Glob { glob: "**/npm-debug.log*", re: "(?-u)^(?:/?|.*/)npm\\-debug\\.log[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: 
Tokens([RecursivePrefix, Literal('n'), Literal('p'), Literal('m'), Literal('-'), Literal('d'), Literal('e'), Literal('b'), Literal('u'), Literal('g'), Literal('.'), Literal('l'), Literal('o'), Literal('g'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/yarn-debug.log*", re: "(?-u)^(?:/?|.*/)yarn\\-debug\\.log[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('y'), Literal('a'), Literal('r'), Literal('n'), Literal('-'), Literal('d'), Literal('e'), Literal('b'), Literal('u'), Literal('g'), Literal('.'), Literal('l'), Literal('o'), Literal('g'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/yarn-error.log*", re: "(?-u)^(?:/?|.*/)yarn\\-error\\.log[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('y'), Literal('a'), Literal('r'), Literal('n'), Literal('-'), Literal('e'), Literal('r'), Literal('r'), Literal('o'), Literal('r'), Literal('.'), Literal('l'), Literal('o'), Literal('g'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/pnpm-debug.log*", re: "(?-u)^(?:/?|.*/)pnpm\\-debug\\.log[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('p'), Literal('n'), Literal('p'), Literal('m'), Literal('-'), Literal('d'), Literal('e'), Literal('b'), Literal('u'), Literal('g'), Literal('.'), Literal('l'), Literal('o'), Literal('g'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/lerna-debug.log*", re: 
"(?-u)^(?:/?|.*/)lerna\\-debug\\.log[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('l'), Literal('e'), Literal('r'), Literal('n'), 
Literal('a'), Literal('-'), Literal('d'), Literal('e'), Literal('b'), Literal('u'), Literal('g'), Literal('.'), Literal('l'), Literal('o'), Literal('g'), ZeroOrMore]) }  
    Debug [globset] glob converted to regex: Glob { glob: ".vscode/*", re: "(?-u)^\\.vscode/[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('.'), Literal('v'), Literal('s'), Literal('c'), Literal('o'), Literal('d'), Literal('e'), Literal('/'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/*.ntvs*", re: "(?-u)^(?:/?|.*/)[^/]*\\.ntvs[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, ZeroOrMore, Literal('.'), Literal('n'), Literal('t'), Literal('v'), Literal('s'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/*.sw?", re: "(?-u)^(?:/?|.*/)[^/]*\\.sw[^/]$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, ZeroOrMore, Literal('.'), Literal('s'), Literal('w'), Any]) }
    Debug [globset] built glob set; 1 literals, 6 basenames, 5 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 8 regexes
    Debug [ignore::gitignore] opened gitignore file: E:\.env\.win\ws\PortableDesktop\.git\info/exclude
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\vite.config.ts: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\tsconfig.node.json: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))     
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\tsconfig.json: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), 
original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\README.md: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\pnpm-lock.yaml: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\package.json: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\index.html: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\.git: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] whitelisting E:\.env\.win\ws\PortableDesktop\.gitignore: Whitelist(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "!**/.gitignore", actual: "**/.gitignore", is_whitelist: true, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\.vscode: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\dist: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("E:\\.env\\.win\\ws\\PortableDesktop\\.gitignore"), original: "dist", actual: "**/dist", is_whitelist: false, is_only_dir: false })))   
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\LICENSE: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\node_modules: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("E:\\.env\\.win\\ws\\PortableDesktop\\.gitignore"), original: "node_modules", actual: "**/node_modules", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\public: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\screenshots: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\src: Ignore(IgnoreMin\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\screenshots: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\src: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring E:\.env\.win\ws\PortableDesktop\src-tauri: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("\\\\?\\E:\\.env\\.win\\ws\\.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::gitignore] opened gitignore file: E:\.env\.win\ws\PortableDesktop\src-tauri\.gitignore
    Debug [globset] built glob set; 2 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
thread '<unnamed>' panicked at crates\tauri-cli\src\helpers\app_paths.rs:119:5:
Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json`, `tauri.conf.json5` or `Tauri.toml` file in any subfolder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed with exit code 3221226505.

```

**Comment by amrbashir** [comment]
it seems like you have some gitignore files in `E:\.env\.gitignore`, `E:\.env\.win\.gitignore` and `E:\.env\.win\ws\.gitignore` specifically `E:\.env\.win\.gitignore` has a rule that prevents our lookup to find the config file.

**Comment by kerwin612** [comment]
> it seems like you have some gitignore files in `E:\.env\.gitignore`, `E:\.env\.win\.gitignore` and `E:\.env\.win\ws\.gitignore` specifically `E:\.env\.win\.gitignore` has a rule that prevents our lookup to find the config file.

The content of this(`E:\.env\.win\.gitignore`) file is：
```
*
!**/.gitignore
!**/tauri.conf.json
```

**Comment by amrbashir** [comment]
sorry I meant `E:\.env\.win\ws\.gitignore`

**Comment by kerwin612** [comment]
> sorry I meant `E:\.env\.win\ws\.gitignore`

Similarly, the content of this file(`E:\.env\.win\ws\.gitignore`) is also the same: 
```
*
!**/.gitignore
!**/tauri.conf.json
```

**If I clear the content of this file(`E:\.env\.win\ws\.gitignore`), it should be restored to normal. May I ask which ignore settings should I disable?**

**Comment by amrbashir** [comment]
try to also not ignore `src-tauri`, i.e add `!**/src-tauri`

**Comment by kerwin612** [comment]
> try to also not ignore `src-tauri`, i.e add `!**/src-tauri`

Nice!!!

**Comment by amrbashir** [comment]
@Phaired do you also have a similar situation with a .gitignore? can you run with `-vvv` and post the output?

**Comment by Phaired** [comment]
No issue with CLI 2.0.3 but still have it with 2.0.4.


```
pnpm tauri dev -vvv

> test@0.1.0 tauri /Users/remy/Developer/DofusFM2/test
> tauri "dev" "-vvv"

    Debug [ignore::gitignore] opened gitignore file: /var/folders/pk/9ltm7r6d3w54jkcrm9yrw_1w0000gn/T/.gitignore
    Debug [globset] built glob set; 0 literals, 3 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
    Debug [ignore::gitignore] opened gitignore file: /Users/remy/.gitignore
    Debug [globset] glob converted to regex: Glob { glob: "**/*", re: "(?-u)^(?:/?|.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, ZeroOrMore]) }
    Debug [globset] built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
    Debug [ignore::gitignore] opened gitignore file: /Users/remy/Developer/DofusFM2/test/.gitignore
    Debug [globset] glob converted to regex: Glob { glob: "**/.env.*", re: "(?-u)^(?:/?|.*/)\\.env\\.[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('.'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/vite.config.js.timestamp-*", re: "(?-u)^(?:/?|.*/)vite\\.config\\.js\\.timestamp\\-[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('v'), Literal('i'), Literal('t'), Literal('e'), Literal('.'), Literal('c'), Literal('o'), Literal('n'), Literal('f'), Literal('i'), Literal('g'), Literal('.'), Literal('j'), Literal('s'), Literal('.'), Literal('t'), Literal('i'), Literal('m'), Literal('e'), Literal('s'), Literal('t'), Literal('a'), Literal('m'), Literal('p'), Literal('-'), ZeroOrMore]) }
    Debug [globset] glob converted to regex: Glob { glob: "**/vite.config.ts.timestamp-*", re: "(?-u)^(?:/?|.*/)vite\\.config\\.ts\\.timestamp\\-[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([RecursivePrefix, Literal('v'), Literal('i'), Literal('t'), Literal('e'), Literal('.'), Literal('c'), Literal('o'), Literal('n'), Literal('f'), Literal('i'), Literal('g'), Literal('.'), Literal('t'), Literal('s'), Literal('.'), Literal('t'), Literal('i'), Literal('m'), Literal('e'), Literal('s'), Literal('t'), Literal('a'), Literal('m'), Literal('p'), Literal('-'), ZeroOrMore]) }
    Debug [globset] built glob set; 3 literals, 4 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 3 regexes
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/tsconfig.json: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/package.json: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/README.md: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/vite.config.js: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/svelte.config.js: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/pnpm-lock.yaml: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/node_modules: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/Developer/DofusFM2/test/.gitignore"), original: "node_modules", actual: "**/node_modules", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/.gitignore: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/static: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/src-tauri: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::gitignore] opened gitignore file: /Users/remy/Developer/DofusFM2/test/src-tauri/.gitignore
    Debug [globset] built glob set; 2 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/.svelte-kit: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/Developer/DofusFM2/test/.gitignore"), original: "/.svelte-kit", actual: ".svelte-kit", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/.vscode: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/src: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
thread '<unnamed>' panicked at crates/tauri-cli/src/helpers/app_paths.rs:117:5:
Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json`, `tauri.conf.json5` or `Tauri.toml` file in any subfolder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed.
zsh: abort      pnpm tauri dev -vvv
```

<img width="455" alt="Capture d’écran 2024-11-12 à 21 22 55" src="https://github.com/user-attachments/assets/990354a4-133d-4f72-9721-f2b12cf03e7a">

src-tauri/.gitignore
```
# Generated by Cargo
# will have compiled files and executables
/target/

# Generated by Tauri
# will have schema files for capabilities auto-completion
/gen/schemas
```

.gitignore
```
.DS_Store
node_modules
/build
/.svelte-kit
/package
.env
.env.*
!.env.example
vite.config.js.timestamp-*
vite.config.ts.timestamp-*
```

**Comment by amrbashir** [comment]
you also have the same problem at `/Users/remy/.gitignore`

**Comment by amrbashir** [comment]
you could also try setting `TAURI_CLI_CONFIG_DEPTH=1`

**Comment by Phaired** [comment]
> you also have the same problem at `/Users/remy/.gitignore`

This .gitignore is empty ...

**Comment by amrbashir** [comment]
I really don't know but this is what the debug log states
```
    Debug [ignore::walk] ignoring /Users/remy/Developer/DofusFM2/test/src-tauri: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/Users/remy/.gitignore"), original: "*", actual: "**/*", is_whitelist: false, is_only_dir: false })))
```
