### ISSUE TITLE
[bug] Tauri dev failing when adding tailwind to SvelteKit project

### ISSUE THREAD

**Issue by torepettersen** [tauri-apps/tauri#11710]
### Describe the bug

After adding tailwindcss to a brand new project, I get an error when running `pnpm tauri dev`.
But works when running `pnpm run dev` and opening in the browser.

Seems similar to this issue: https://github.com/tauri-apps/tauri/issues/11482

### Reproduction

- Create a new project with `pnpm create tauri-app`. All default options, except selecting Svelte as the framework.
- Add tailwind with `pnpm dlx sv add tailwindcss`
- Run `pnpm tauri dev`

### Expected behavior

Should be able to run the app, instead of crashing.

### Full `tauri info` output

```text
[✔] Environment
    - OS: EndeavourOS Rolling Release x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.3
    ✔ rsvg2: 2.59.2
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.82.0-x86_64-unknown-linux-gnu (default)
    - node: 22.11.0
    - pnpm: 9.13.2
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.0.4
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
10:39:54 AM [vite] Internal server error: [postcss] /home/tore/workspace/query-nest/src/routes/+page.svelte?svelte&type=style&lang.css:2:12: Unknown word
  Plugin: vite:css
  File: /home/tore/workspace/query-nest/src/routes/+page.svelte?svelte&type=style&lang.css:2:11
  1  |  <script lang="ts">
  2  |    import { invoke } from "@tauri-apps/api/core";
     |             ^
  3  |  
  4  |    let name = $state("");
      at Input.error (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parser.js:593:22)
      at Parser.other (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parser.js:435:12)
      at Parser.parse (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parser.js:470:16)
      at parse (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/tore/workspace/query-nest/node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/processor.js:53:14)
      at compileCSS (file:///home/tore/workspace/query-nest/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36897:59)
      at async TransformPluginContext.transform (file:///home/tore/workspace/query-nest/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36170:11)
      at async PluginContainer.transform (file:///home/tore/workspace/query-nest/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
```

**Comment by FabianLars** [comment]
> But works when running pnpm run dev and opening in the browser.

Can you try that same thing but with epiphany (also known as gnome web)?

**Comment by torepettersen** [comment]
Yes, I have now tried with Epiphany and it also works there.

**Comment by torepettersen** [comment]
I now also managed to reproduce the bug in Epiphany.

Seems like I mangage to make it run in Epiphany and with `pnpm taruri dev` if I open the app in a browser (like Firefox) first and then open the app in Epiphany or the app window afterwards.

**Comment by progzone122** [comment]
the same problem

**Comment by prehonor** [comment]
for me 
export const prerender = true;
export const ssr = true; 
solve the problem.
 Otherwise,export const ssr = false, problems will occur.

**Comment by kotkoroid** [comment]
Hi, are you experiencing the same issue when installing TailwindCSS 4 as a Vite plugin?

**Comment by Octogonapus** [comment]
> Hi, are you experiencing the same issue when installing TailwindCSS 4 as a Vite plugin?

Still running into this with both TailwindCSS 3 and 4 (installed as Vite plugin). `ssr = true` does work around the error but obviously not ideal.

The error with tailwindcss 4:
```
2:00:01 PM [vite] (client) Pre-transform error: Invalid declaration: `invoke`
  Plugin: @tailwindcss/vite:generate:serve
  File: /path/to/project/src/routes/+page.svelte?svelte&type=style&lang.css
2:00:01 PM [vite] Internal server error: Invalid declaration: `invoke`
  Plugin: @tailwindcss/vite:generate:serve
  File: /path/to/project/src/routes/+page.svelte?svelte&type=style&lang.css
      at me (file:///path/to/project/node_modules/.pnpm/tailwindcss@4.1.10/node_modules/tailwindcss/dist/chunk-E562WLSY.mjs:1:2671)
      at Ca (file:///path/to/project/node_modules/.pnpm/tailwindcss@4.1.10/node_modules/tailwindcss/dist/chunk-E562WLSY.mjs:35:1876)
      at $a (file:///path/to/project/node_modules/.pnpm/@tailwindcss+node@4.1.10/node_modules/@tailwindcss/node/dist/index.mjs:10:3439)
      at C.generate (file:///path/to/project/node_modules/.pnpm/@tailwindcss+vite@4.1.10_vite@6.3.5_jiti@2.4.2_lightningcss@1.30.1_yaml@2.8.0_/node_modules/@tailwindcss/vite/dist/index.mjs:1:3577)
      at TransformPluginContext.transform (file:///path/to/project/node_modules/.pnpm/@tailwindcss+vite@4.1.10_vite@6.3.5_jiti@2.4.2_lightningcss@1.30.1_yaml@2.8.0_/node_modules/@tailwindcss/vite/dist/index.mjs:1:1957)
      at EnvironmentPluginContainer.transform (file:///path/to/project/node_modules/.pnpm/vite@6.3.5_jiti@2.4.2_lightningcss@1.30.1_yaml@2.8.0/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:42295:19)
      at loadAndTransform (file:///path/to/project/node_modules/.pnpm/vite@6.3.5_jiti@2.4.2_lightningcss@1.30.1_yaml@2.8.0/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:35735:49)
```

My environment:
```
[✔] Environment
    - OS: Ubuntu 24.4.0 x86_64 (X64) (Unknown DE on Unknown Session)
    ✔ webkit2gtk-4.1: 2.48.3
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.87.0 (17067e9ac 2025-05-09)
    ✔ cargo: 1.87.0 (99624be96 2025-05-06)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.14.0
    - pnpm: 10.12.3
    - npm: 10.9.2

[-] Packages
    - tauri 🦀: 2.5.1
    - tauri-build 🦀: 2.2.0
    - wry 🦀: 0.51.2, (outdated, latest: 0.52.0)
    - tao 🦀: 0.33.0, (outdated, latest: 0.34.0)
    - @tauri-apps/api : 2.5.0
    - @tauri-apps/cli : 2.5.0

[-] Plugins
    - tauri-plugin-opener 🦀: 2.3.0
    - @tauri-apps/plugin-opener : 2.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite


dependencies:
@tailwindcss/vite 4.1.10
@tauri-apps/api 2.5.0
@tauri-apps/plugin-opener 2.3.0
tailwindcss 4.1.10

devDependencies:
@sveltejs/adapter-static 3.0.8
@sveltejs/kit 2.22.0
@sveltejs/vite-plugin-svelte 5.1.0
@tauri-apps/cli 2.5.0
svelte 5.34.7
svelte-check 4.2.2
typescript 5.6.3
vite 6.3.5
```

**Comment by riverfr0zen** [comment]
I just encountered this issue, but was surprised as a slightly older project using Tailwind 4 as a Vite plugin was working fine. 

First I tried switching to the older versions ("^4.0.14" of `tailwindcss` and `@tailwindcss/vite`), and it initially looked like that solved the problem, but after repeating a few times (reverting to latest and back to old), I found that the error shows up inconsistently for both older and latest versions of tailwind.

Then I noticed that if you move past the error (i.e. by clicking outside the error overlay in your app), your app should display normally. You might have to do this a few times, but then in subsequent invocations of `pnpm tauri dev`, the error  ceases to appear.  Kind of strange behavior, but for me at least, it seems this error is some kind of ephemeral occurrence.

**Comment by samson-jerome** [comment]
I've seen the same issue, indeed clicking outside the overlay "unlocks" the app and loading finishes correctly.
The error popup is still present after 4 restarts though...

**Comment by LDprg** [comment]
I can also confirm this issue beeing a thing (I for example have the issue with font awesome icons instead of tailwind)
It also does not seem to be postcss related, since I am using lightningcss and have the same issue.

For reference there seems alot of similar issues like https://github.com/toolkitties/toolkitty/issues/12 .

**Comment by andersmmg** [comment]
Having the same issue after adding tailwind to a fresh svelte tauri project, the app works fine after closing the error overlay, but it comes up every time the app is launched.

**Comment by manymanecki** [comment]
Can confirm it also happened to me on a fresh Tauri (+ Svelte) setup. For some reason, waiting on that error screen for a few seconds refreshed the page, made the error disappear and it did not comeback for now. Weird one.

EDIT: Had it happen again after changing some configuration files. Same thing happened, after a few tries the application reloaded out of a sudden and the error was gone.

<img width="910" height="245" alt="Image" src="https://github.com/user-attachments/assets/57a49927-e301-4699-ac27-831b44d16b2b" />

**Comment by LordzShadow** [comment]
I managed to fix it by removing the `.svelte-kit` folder before running the application and adding `lang="css"` to  the `<style>` element.

**Comment by manymanecki** [comment]
> I managed to fix it by removing the `.svelte-kit` folder before running the application and adding `lang="css"` to the `<style>` element.

Removing .svelte-kit did not work, but adding `lang="css"` indeed seems to have resolved it for now.

**Comment by XurxoMF** [comment]
And +1 to the error. It's happening to me right now xD
Where are you adding the `lang="css"`??? What `<style>` element and where?

**Comment by LordzShadow** [comment]
> And +1 to the error. It's happening to me right now xD
> Where are you adding the `lang="css"`??? What `<style>` element and where?

To the style element in the svelte file where the error occurs. Although I don't think it fixed it entirely as I still get the error sometimes. Ctrl + R after build seems to be an easy enough of a workaround currently.

**Comment by XurxoMF** [comment]
Oh, using Tailwind there is no need for a style element...
I don't know if this happens always when you use invoke or just in some cases...
I'll try a few things and if I find something I'll write it here

**Comment by ynhhoJ** [comment]
You can do something like this:

```diff
<script lang="ts">
-import { invoke } from "@tauri-apps/api/core";
+import { invoke as tauriInvoke } from "@tauri-apps/api/core";

let name = $state("");
let greetMsg = $state("");

async function greet(event: Event) {
	event.preventDefault();
	// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
-	greetMsg = await invoke("greet", { name });
+	greetMsg = await tauriInvoke("greet", { name });
}
</script>

<main class="container">
	<form class="row" onsubmit={greet}>
		<input id="greet-input" placeholder="Enter a name..." bind:value={name}>
		<button type="submit">Greet</button>
	</form>
	<p>{greetMsg}</p>
</main>
```
Or another option:
`vite.config.ts`, add in `plugins`:
```ts
// When vite-plugin-svelte can't serve a cached virtual CSS module (e.g. on
// cold start), Vite falls back to reading the raw .svelte file from disk and
// @tailwindcss/vite receives JS source as CSS, crashing the CSS parser.
// This post-load plugin intercepts uncached modules and returns empty CSS.
{
	name: "svelte-virtual-css-fallback",
	enforce: "post" as const,
	load(id: string) {
		if (/[?&]svelte&type=style&lang\.css/.test(id)) {
			return { code: "" };
		}
	},
},
```

and you will be able to use `invoke` directly

**Comment by corvidism** [comment]
I have the same issue on a brand new Tauri project:

```
@tauri-apps/cli@2.10.1
@tauri-apps/api@2.10.1
vite@6.4.2
tailwindcss@4.2.4
@tailwindcss/vite@4.2.4
```

Fixes I've tested:

@ynhhoJ:

Aliasing `invoke` to `tauriInvoke` did not work for me, I just got errors on some custom functions I import in a component (clicking out of the error overlay works again, so it's the same problem).

The plugin hack does work (it needs to go right after `tailwindcss()` in the plugin list, if you have any other plugins in there), with the downside that on first load the app is unstyled. Triggering a reload (e.g. saving a file) fixes it. It's a little better than clicking out of the error overlay.


@LordzShadow:

~~I added a `<style lang="css"></style>` to my `+page.svelte` file and the error went away. **Yeah, it's literally that dumb🤦** I suspect there has to be a "correct" fix (and as @ynhhoJ mentions, this is specifically a @tailwindcss/vite + (SPA?) Sveltekit problem, not Tauri), but this works well enough for me.~~

Welp. I returned to the project after a week and the error is back. I can't figure out what I've changed. It's now choking on some custom method imports in a Svelte subcomponent, but even adding a `<style lang="css"></style>` inside *that* does not help. I guess I'll have to find and fix the actual bug instead of patching it over...

**Comment by corvidism** [comment]
A minimal Tauri + Svelte + Tailwindss project that has the error: https://github.com/corvidism/tauri-svelte-tailwind-bug

After some testing, the problem is somewhere between `@tailwindcss/vite` and Tauri. Away from Tauri, the same Svelte + Tailwindcss project runs fine. Does Tauri do something to Vite when it runs?
