### ISSUE TITLE
[bug] `window` is not defined in Next.js 15 + Tauri V2

### ISSUE THREAD

**Issue by Runkang10** [tauri-apps/tauri#11869]
### Describe the bug

When using `@tauri-apps/api/window` on Next.js 15 with Tauri V2 it will say `window` is not defined.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.27723 x86_64 (X64)
    ✔ WebView2: 131.0.2903.70
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.14.0
    - pnpm: 9.14.4
    - npm: 10.8.3
    - deno: deno 2.0.4

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : not installed!
    - tauri-plugin-updater 🦀: 2.1.0
    - @tauri-apps/plugin-updater : 2.0.0
    - tauri-plugin-upload 🦀: 2.2.1
    - @tauri-apps/plugin-upload : 2.2.1
    - tauri-plugin-fs 🦀: 2.1.0
    - @tauri-apps/plugin-fs : 2.0.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

#### Next.js
```text

Error: window is not defined
    at RootLayout (rsc://React/Server/C:%5CUsers%5Cchenr%5CDesktop%5CProjects%5CEncodeX%5C.next%5Cserver%5Cchunks%5Cssr%5Csrc_7f8077._.js?0:205:18)
    at resolveErrorDev (http://localhost:3000/_next/static/chunks/478e0_next_dist_compiled_b569b5._.js:3657:65)
    at processFullStringRow (http://localhost:3000/_next/static/chunks/478e0_next_dist_compiled_b569b5._.js:3819:23)
    at processFullBinaryRow (http://localhost:3000/_next/static/chunks/478e0_next_dist_compiled_b569b5._.js:3807:9)
    at progress (http://localhost:3000/_next/static/chunks/478e0_next_dist_compiled_b569b5._.js:3927:102)
```

#### Terminal & Console
```
 ⨯ ReferenceError: window is not defined
    at getCurrentWindow (file://C%3A/Users/chenr/Desktop/Projects/EncodeX/node_modules/.pnpm/%40tauri-apps%2Bapi%402.1.1/node_modules/%40tauri-apps/api/window.js:85:22)
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (file://C%3A/Users/chenr/Desktop/Projects/EncodeX/src/app/layout.tsx:8:30)
    at instantiateModule (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component) (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\src_7f8077._.js:246:32)
    at instantiateModule (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <module evaluation> (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\_003f1f._.js:131:160)
    at instantiateModule (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\_003f1f._.js:232:1345)
    at instantiateModule (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at instantiateRuntimeModule (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:652:12)
    at Object.getOrInstantiateRuntimeModule (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\chunks\ssr\[turbopack]_runtime.js:668:12)       
    at Object.<anonymous> (C:\Users\chenr\Desktop\Projects\EncodeX\.next\server\app\page.js:12:26)
    at call (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\require-hook.ts:70:25)
    at require (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\require.ts:121:8)
    at page (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\load-components.ts:189:41)
    at async DevServer.findPageComponentsImpl (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\next-server.ts:779:27)
    at async DevServer.findPageComponents (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\dev\next-dev-server.ts:881:13)
    at async DevServer.renderPageComponent (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\base-server.ts:3584:19)
    at async DevServer.renderToResponseImpl (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\base-server.ts:3659:23)
    at async DevServer.pipeImpl (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\base-server.ts:1698:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\next-server.ts:1034:6)
    at async DevServer.handleRequestImpl (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\base-server.ts:1462:8)
    at async (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\dev\next-dev-server.ts:514:13)
    at async Span.traceAsyncFn (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\trace\trace.ts:143:13)
    at async DevServer.handleRequest (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\dev\next-dev-server.ts:512:19)
    at async invokeRender (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\lib\router-server.ts:284:10)
    at async handleRequest (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\lib\router-server.ts:530:15)
    at async requestHandlerImpl (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\lib\router-server.ts:576:6)
    at async Server.requestListener (node_modules\.pnpm\next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1\node_modules\next\src\server\lib\start-server.ts:146:6)
  83 |  */
  84 | function getCurrentWindow() {
> 85 |     return new Window(window.__TAURI_INTERNALS__.metadata.currentWindow.label, {
     |                      ^
  86 |         // @ts-expect-error `skip` is not defined in the public API but it is handled by the constructor
  87 |         skip: true
  88 |     }); {
  page: '/'
}
```

**Comment by FabianLars** [comment]
All of tauri's apis require the window to communicate with the rust side (this is how the webview apis work 🤷). Make sure to only call the apis in a client-side context (onMount-like useeffects for example)

**Comment by Runkang10** [comment]
I was using `pnpm tauri dev` (Next with Tauri).
Isn't because i was calling it on `layout.tsx`?

**Comment by FabianLars** [comment]
> I was using pnpm tauri dev (Next with Tauri).

Yeah, i assumed that, but the same would apply after building the app.

>  Isn't because i was calling it on layout.tsx?

I'm not a nextjs expert so that could be, yeah. I'd recommend to just research in which contexts you can call `window` or `navigator` methods, that's where you can use tauri's apis then.
