### ISSUE TITLE
`yarn tauri init` doesn't work on my fedora machine. Help

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [tauri-apps/tauri#1504]
**Describe the bug**
Hi, I'm starting with Tauri but I couldn't pass the `yarn tauri init`. It gives an ugly error. I tried first using pnpm, then npm, then yarn, and all of them give the same error. If i enter `yarn tauri` it works, version and help also work, but anything else throws error. 
PS.: the only difference in my machine is that it uses **volta** instead of **nvm**. Could that be it??

**To Reproduce**
1. Install all dependencies necessary for fedora (with volta instead of npm).
2. Create a project folder.
3. With yarn installed by volta (`volta install yarn`), run `yarn add @tauri-apps/cli`.
4. Run `yarn tauri init`.
4. See error.

**Expected behavior**
Should install.

**Platform and Versions (please complete the following information):**
OS: Fedora 33 (Workstation Edition), 64 bit, GNOME Version: 3.38.5, Windowing System: Wayland; fully updated.
Node: v14.16.1
Yarn: 1.22.10
Rustc: rustc 1.51.0 (2fd73fabe 2021-03-23)

**Stack Trace**
yarn run v1.22.10
$ /home/gabriel/Documents/VSCode/mini-browser/node_modules/.bin/tauri init
 app:spawn Running "/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/bin/tauri-cli tauri init" +0ms

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/bin/tauri-cli EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/bin/tauri-cli',
  path: '/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/bin/tauri-cli',
  spawnargs: [ 'tauri', 'init' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by probablykasper** [comment]
Getting the same issue on macOS, was just about to post an issue for it.

Also, running `npx create-tauri-app` gives me this error:
```
===== running tauri init =====

> tauri-app@ tauri /Users/kasper/dev/git/riddle/x/tauri-app
> tauri "init" "--app-name" "tauri-app" "--window-title" "Tauri App" "--dist-dir" "../dist" "--dev-path" "../dist"

Downloading Tauri CLI
(node:11509) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/Users/kasper/dev/git/riddle/x/tauri-app/node_modules/got/dist/source/core/index.js:899:31)
    at Request._onResponse (/Users/kasper/dev/git/riddle/x/tauri-app/node_modules/got/dist/source/core/index.js:934:24)
    at ClientRequest.<anonymous> (/Users/kasper/dev/git/riddle/x/tauri-app/node_modules/got/dist/source/core/index.js:948:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/kasper/dev/git/riddle/x/tauri-app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11509) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11509) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nklayman** [comment]
Your issue was triggered because the prebuilt CLI binary wasn't published. It is published now, give it a try and it should work. You will probably have to reinstall the js package so that the prebuilt CLI is redownloaded as well.

**Comment by nothingismagick** [comment]
Closing issue. If it is still happening, by all means reopen it.

**Comment by Gabriel-Alves-Cunha** [comment]
Hi again, not sure if it is relatively the same issue but `yarn tauri info` gives out an error. `yarn tauri init` is working now.

Error:
```
yarn run v1.22.10
$ /home/gabriel/Documents/VSCode/mini-browser/node_modules/.bin/tauri info
 app:spawn Running "/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Fedora, version 33.0.0 X64

Node.js environment
Error: missing field `js_cli` at line 8 column 1

 app:spawn Command "/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 1 +1ms
(node:9569) UnhandledPromiseRejectionWarning: Error
    at d (/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/dist/helpers/rust-cli.js:1:6078)
    at w (/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/dist/helpers/rust-cli.js:1:6119)
    at ChildProcess.<anonymous> (/home/gabriel/Documents/VSCode/mini-browser/node_modules/@tauri-apps/cli/dist/helpers/rust-cli.js:1:7250)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9569) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9569) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.22s.
```

**Comment by amrbashir** [comment]
@Gabriel-Alves-Cunha this is issue has been reported and fixed but not released yet. It should be released soon

**Comment by Gabriel-Alves-Cunha** [comment]
> @Gabriel-Alves-Cunha this is issue has been reported and fixed but not released yet. It should be released soon

Oh, ok. Thank you :)

**Comment by Pierstoval** [comment]
Thanks for reporting this and fixing it so quickly ♥ I'm having the exact same issue on Ubuntu 20.04 under WSL 😀

🚀

**Comment by loicngr** [comment]
Hi!

I'm on windows, and i have same error with `yarn tauri init` command.

```
F:\perso\simple-calculator>yarn tauri init
yarn run v1.22.10
$ tauri init
 app:spawn Running "F:\perso\simple-calculator\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri init" +0ms

What is your app name?: Error: Not a terminal

 app:spawn Command "F:\perso\simple-calculator\node_modules\@tauri-apps\cli\bin\tauri-cli.exe" failed with exit code: 1 +0ms
(node:7696) UnhandledPromiseRejectionWarning: Error
    at d (F:\perso\simple-calculator\node_modules\@tauri-apps\cli\dist\helpers\rust-cli.js:1:6078)
    at w (F:\perso\simple-calculator\node_modules\@tauri-apps\cli\dist\helpers\rust-cli.js:1:6119)
    at ChildProcess.<anonymous> (F:\perso\simple-calculator\node_modules\@tauri-apps\cli\dist\helpers\rust-cli.js:1:7250)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (F:\perso\simple-calculator\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.12s.

F:\perso\simple-calculator>
```

My **package.json** config : 
```
{
  "name": "simple-calculator",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "tauri": "tauri"
  },
  "dependencies": {
    "@tauri-apps/cli": "^1.0.0-beta-rc.2"
  }
}
```

**Comment by amrbashir** [comment]
@loicngr this is a know issue, tracked at #1492
