### ISSUE TITLE
Windows Notification Api causes application crash

### ISSUE THREAD

**Issue by dibadibadiudiu** [tauri-apps/tauri#1870]
**Describe the bug**

Using the notification API on windows will cause the application to crash. 

Errors in both `yarn tauri build` and `yarn tauri dev` modes.

The error is as follows:

```
thread 'main' panicked at 'failed to call RoInitialize: error -2147417850', ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winrt-0.4.0\src\rt\mod.rs:729:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\/library\std\src\panicking.rs:493       
   1: std::panicking::begin_panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\/library\std\src\panicking.rs:435       
   2: winrt::rt::RuntimeContext::init
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winrt-0.4.0\src\rt\mod.rs:729
   3: winrt_notification::Toast::show
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winrt-notification-0.2.4\src\lib.rs:278
   4: notify_rust::windows::show_notification
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\notify-rust-4.5.2\src\windows.rs:42
   5: notify_rust::notification::Notification::show
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\notify-rust-4.5.2\src\notification.rs:378
   6: tauri::api::notification::Notification::show
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.1\src\api\notification.rs:84
   7: app::push
             at .\src\main.rs:48
   8: app::main::{{closure}}
             at .\src\main.rs:38
   9: alloc::boxed::{{impl}}::call<tuple<tauri::hooks::Invoke<tauri::manager::Args<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>>>,Fn<tuple<tauri::hooks::
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1560
  10: tauri::manager::WindowManager<tauri::manager::Args<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>>::run_invoke_handler<tauri::manager::Args<alloc::st
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.1\src\manager.rs:514
  11: tauri::window::Window<tauri::manager::Args<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>>::on_message<tauri::manager::Args<alloc::string::String, al
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.1\src\window.rs:214
  12: tauri::manager::{{impl}}::prepare_rpc_handler::{{closure}}<tauri::manager::Args<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.1\src\manager.rs:338
  13: alloc::boxed::{{impl}}::call<tuple<tauri_runtime::window::DetachedWindow<tauri::manager::Args<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>>, tauri_
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1560
  14: tauri_runtime_wry::create_rpc_handler::{{closure}}<tauri::manager::Args<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.1.1\src\lib.rs:1113
  15: alloc::boxed::{{impl}}::call<tuple<tao::window::Window*, wry::webview::RpcRequest>,Fn<tuple<tao::window::Window*, wry::webview::RpcRequest>>,alloc::alloc::Global>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1560
  16: alloc::boxed::{{impl}}::call<tuple<tao::window::Window*, wry::webview::RpcRequest>,Fn<tuple<tao::window::Window*, wry::webview::RpcRequest>>,alloc::alloc::Global>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1560
  17: wry::webview::rpc_proxy
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\wry-0.9.4\src\webview\mod.rs:57
  18: wry::webview::win32::{{impl}}::new::{{closure}}::{{closure}}::{{closure}}
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\wry-0.9.4\src\webview\win32\mod.rs:118
  19: webview2::{{impl}}::add_web_message_received::{{closure}}<closure-2>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-0.1.0\src\lib.rs:987
  20: alloc::boxed::{{impl}}::call<tuple<mut mut webview2_sys::ICoreWebView2VTable**, mut mut webview2_sys::ICoreWebView2WebMessageReceivedEventArgsVTable**>,Fn<tuple<mut mut webview2_sys::ICoreWebView2VTable**, mut mut webview2_sys::ICoreWebView2WebMessageRece
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1560
  21: webview2::{{impl}}::add_web_message_received::{{impl}}::invoke::{{closure}}
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-0.1.0\src\lib.rs:96
  22: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  23: std::panic::{{impl}}::call_once<i32,closure-0>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  24: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,i32>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  25: std::panicking::begin_panic::{{impl}}::take_box<str>
  26: std::panicking::try<i32,std::panic::AssertUnwindSafe<closure-0>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  27: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,i32>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  28: webview2::{{impl}}::add_web_message_received::{{impl}}::invoke
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-0.1.0\src\lib.rs:95
  29: webview2_sys::{{impl}}::vtable::icorewebview2webmessagereceivedeventhandler_invoke<webview2::{{impl}}::add_web_message_received::Impl,com::offset::Zero>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-sys-0.1.0\src\lib.rs:2921
  30: CreateWebViewEnvironmentWithOptionsInternal
  31: DllCanUnloadNow
  32: DllCanUnloadNow
  33: DllCanUnloadNow
  34: DllCanUnloadNow
  35: DllCanUnloadNow
  36: DllCanUnloadNow
  37: DllCanUnloadNow
  38: DllCanUnloadNow
  39: DllCanUnloadNow
  40: Ordinal0
  41: DllCanUnloadNow
  42: CallWindowProcW
  43: DispatchMessageW
  44: tao::platform_impl::platform::event_loop::EventLoop<tauri_runtime_wry::Message>::run_return<tauri_runtime_wry::Message,closure-0>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.2.6\src\platform_impl\windows\event_loop.rs:224
  45: tao::platform_impl::platform::event_loop::EventLoop<tauri_runtime_wry::Message>::run<tauri_runtime_wry::Message,closure-0>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.2.6\src\platform_impl\windows\event_loop.rs:193
  46: tao::event_loop::EventLoop<tauri_runtime_wry::Message>::run<tauri_runtime_wry::Message,closure-0> 
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.2.6\src\event_loop.rs:150
  47: tauri_runtime_wry::{{impl}}::run
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.1.1\src\lib.rs:882
  48: tauri::app::Builder<alloc::string::String, alloc::string::String, alloc::string::String, alloc::string::String, tauri_utils::assets::EmbeddedAssets, tauri_runtime_wry::Wry>::run<alloc::string::String,alloc::string::String,alloc::string::String,alloc::stri
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.1\src\app.rs:588
  49: app::main
             at .\src\main.rs:13
  50: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
webview2: panic in callback function. Aborting because it's UB to unwind across FFI boundaries.
error: process didn't exit successfully: `target\debug\app.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

yarn tauri info:

```
Operating System - Windows, version 10.0.19041 X64
Webview2 - 90.0.818.62

Node.js environment
  Node.js - 14.16.1
  @tauri-apps/cli - 1.0.0-beta.1（ It's actually 1.0.0-beta.2,This package contains version error, please check）
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.12
  yarn - 1.22.5

Rust environment
  rustc - 1.52.0
  cargo - 1.52.0

App directory structure
/.git
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self'
distDir - ../dist
devPath - http://localhost:8080
framework - Vue.js (Vue CLI)
bundler - Webpack
```

**Comment by dibadibadiudiu** [comment]
In addition, the winrt and winrt-notification package versions of Tauri are not up-to-date.

**Comment by lucasfernog** [comment]
Duplicated of #917
