### ISSUE TITLE
API example doesn't open new window when button clicked (crashes on `--release`)

### ISSUE THREAD

**Issue by chippers** [tauri-apps/tauri#2038]
**Describe the bug**
API example crashes when clicking "New Window" in a release build. Debug builds generate the same error, but does not crash the window.

**To Reproduce**
1. Check out latest dev (59784c7e5587ff10d7f0c37ac414499da42d0707 at the time of writing)
2. Run `cargo run --bin api` (release and backtrace optional)
3. Click the "Window" tab on the left side
4. Click "New window" button
5. See backtrace and no new window (or crash if running release).

**Expected behavior**
A new window to open.

**Platform and Versions (please complete the following information):**
OS: `5.12.10-arch1-1 x86_64 GNU/Linux`
Rustc: `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

**Stack Trace**
```
➜  tauri git:(dev) RUST_BACKTRACE=full cargo run --bin api
   Compiling api v0.1.0 (/home/chip/code/tauri-apps/tauri/examples/api/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 15.30s
     Running `target/debug/api`
thread 'tokio-runtime-worker' panicked at 'GTK may only be used from the main thread.', /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/auto/menu_item.rs:48:9
stack backtrace:
   0:     0x55d62996ede0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d62996ede0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d62996ede0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d62996ede0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d629992e9f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x55d629967c92 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x55d629971645 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d629971645 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d629971645 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x55d6299710f3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x55d629971c4d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x55d6298f0f13 - std::panicking::begin_panic::{{closure}}::he8f93f7e759b0ba1
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
  12:     0x55d6298f1df9 - std::sys_common::backtrace::__rust_end_short_backtrace::ha36071299d5cd72d
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d6298f0e49 - std::panicking::begin_panic::h431f118bdc0194c2
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  14:     0x55d6294664f4 - gtk::auto::menu_item::MenuItem::with_label::h5964dbf8a2a3b164
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/auto/menu_item.rs:48:9
  15:     0x55d629401a52 - tao::platform_impl::platform::menu::Menu::add_item::hfba384ef49c75fd7
                               at /home/chip/.cargo/git/checkouts/tao-b2c91e21b396bd53/01fc43b/src/platform_impl/linux/menu.rs:119:7
  16:     0x55d629437216 - tao::menu::MenuBar::add_item::h726cfa794a5823ab
                               at /home/chip/.cargo/git/checkouts/tao-b2c91e21b396bd53/01fc43b/src/menu.rs:162:5
  17:     0x55d628e2f033 - tauri_runtime_wry::menu::to_wry_menu::h39edc51cb043a514
                               at /home/chip/code/tauri-apps/tauri/core/tauri-runtime-wry/src/menu.rs:202:24
  18:     0x55d628e2f1e0 - tauri_runtime_wry::menu::to_wry_menu::h39edc51cb043a514
                               at /home/chip/code/tauri-apps/tauri/core/tauri-runtime-wry/src/menu.rs:217:11
  19:     0x55d628e2f1e0 - tauri_runtime_wry::menu::to_wry_menu::h39edc51cb043a514
                               at /home/chip/code/tauri-apps/tauri/core/tauri-runtime-wry/src/menu.rs:217:11
  20:     0x55d628e9192d - <tauri_runtime_wry::WindowBuilderWrapper as tauri_runtime::webview::WindowBuilder>::menu::h42e09692869749ad
                               at /home/chip/code/tauri-apps/tauri/core/tauri-runtime-wry/src/lib.rs:453:23
  21:     0x55d628d00525 - tauri::manager::WindowManager<P>::prepare_pending_window::h0468943817a9c93d
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/manager.rs:339:34
  22:     0x55d628cfd64a - tauri::manager::WindowManager<P>::prepare_window::hf763b837e436a9be
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/manager.rs:631:17
  23:     0x55d628d7f7fc - tauri::sealed::ManagerBase::create_new_window::h0487f5aa4406e8d3
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/lib.rs:373:21
  24:     0x55d628d810e0 - tauri::window::Window<P>::create_window::hd1eaf13dbdc3a2e4
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/window.rs:177:5
  25:     0x55d628d8a66a - tauri::endpoints::window::Cmd::run::{{closure}}::h2ff48bf0065a5e1f
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/endpoints/window.rs:118:11
  26:     0x55d628ddd3c7 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h84705a5a0c6052a3
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  27:     0x55d628ed7eb0 - tauri::endpoints::Module::run::{{closure}}::ha2293eb79d020c0a
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/endpoints.rs:85:9
  28:     0x55d628ddc573 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2aff57ae925f6777
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  29:     0x55d628cbe9e2 - tauri::hooks::InvokeResolver<P>::return_task::{{closure}}::h3454087c291cac3c
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/hooks.rs:202:18
  30:     0x55d628ddc64b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2b619efce86182a6
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  31:     0x55d628cc33b9 - tauri::hooks::InvokeResolver<P>::respond_async::{{closure}}::hcaa988cb8e979712
                               at /home/chip/code/tauri-apps/tauri/core/tauri/src/hooks.rs:140:7
  32:     0x55d628ddc87b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3133698c5f597189
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  33:     0x55d628e8a90f - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hf4b3c616b745b4bb
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:243:17
  34:     0x55d628dd821a - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hb57803f23a8544dc
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/loom/std/unsafe_cell.rs:14:9
  35:     0x55d628e89117 - tokio::runtime::task::core::CoreStage<T>::poll::h351af312a2bd8df7
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:233:13
  36:     0x55d628c8969a - tokio::runtime::task::harness::poll_future::{{closure}}::h1b6bb336a7886bb2
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:427:23
  37:     0x55d628d49a93 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5618fa2623a00c46
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  38:     0x55d628e69270 - std::panicking::try::do_call::h6b4cd76d2df4ec85
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  39:     0x55d628e924ed - __rust_try
  40:     0x55d628e6701a - std::panicking::try::h079bb0ef2ad595f0
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  41:     0x55d628d6aeba - std::panic::catch_unwind::hcdad958aa29939d4
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  42:     0x55d628c86ddd - tokio::runtime::task::harness::poll_future::h8122b6b51300cb4d
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:414:19
  43:     0x55d628c8b72b - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h8b2855d00e58b49f
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:89:9
  44:     0x55d628c9447b - tokio::runtime::task::harness::Harness<T,S>::poll::hab1c27b83f7340db
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:59:15
  45:     0x55d628e42e20 - tokio::runtime::task::raw::poll::h418f4deaaa0c4887
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/raw.rs:104:5
  46:     0x55d629552eff - tokio::runtime::task::raw::RawTask::poll::h28b45349aeee56aa
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/raw.rs:66:18
  47:     0x55d6294fed71 - tokio::runtime::task::Notified<S>::run::he6e10cff487544e2
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/mod.rs:171:9
  48:     0x55d629554af2 - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::h6b87b8528d16ec6d
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/worker.rs:349:13
  49:     0x55d6295478bc - tokio::coop::with_budget::{{closure}}::hb3d5ab32aa66cf00
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  50:     0x55d62952b3a8 - std::thread::local::LocalKey<T>::try_with::h763c8e8b61295922
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  51:     0x55d62952a15e - std::thread::local::LocalKey<T>::with::h6946f555c2b12312
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  52:     0x55d629554913 - tokio::coop::with_budget::ha121e1df7817c02f
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  53:     0x55d629554913 - tokio::coop::budget::h4e20927c985e29a3
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  54:     0x55d629554913 - tokio::runtime::thread_pool::worker::Context::run_task::h87909a9126c1021d
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/worker.rs:348:9
  55:     0x55d62955435f - tokio::runtime::thread_pool::worker::Context::run::hdf66e77b2bbac681
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/worker.rs:318:24
  56:     0x55d629554163 - tokio::runtime::thread_pool::worker::run::{{closure}}::h52fb233fb975435c
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/worker.rs:303:17
  57:     0x55d62954026d - tokio::macros::scoped_tls::ScopedKey<T>::set::hdaa10259270110b9
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  58:     0x55d629554043 - tokio::runtime::thread_pool::worker::run::hcc763c8d1b7c63ae
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/worker.rs:300:5
  59:     0x55d629553f0b - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::h5f547adbe270fba9
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/worker.rs:279:45
  60:     0x55d6294f111f - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hdb48425e0643a8f5
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/task.rs:42:21
  61:     0x55d62954edc0 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h604c9cd6eb04de0f
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:243:17
  62:     0x55d6295225ee - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h9e3e825bf9e5ea66
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/loom/std/unsafe_cell.rs:14:9
  63:     0x55d62954ec68 - tokio::runtime::task::core::CoreStage<T>::poll::he29c4f672b78b3ab
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:233:13
  64:     0x55d6294f0fee - tokio::runtime::task::harness::poll_future::{{closure}}::h1f1bb9d04694bca9
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:427:23
  65:     0x55d629513383 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h66a7178785073cc7
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  66:     0x55d629506682 - std::panicking::try::do_call::hc21893bbc7dfa5aa
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  67:     0x55d62950f04d - __rust_try
  68:     0x55d62950635a - std::panicking::try::h30c854025d5ac431
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  69:     0x55d62951470b - std::panic::catch_unwind::hc3a4215c319d27cb
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  70:     0x55d6294f0c8e - tokio::runtime::task::harness::poll_future::h59fea0639df7125d
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:414:19
  71:     0x55d6294efce3 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::he37042f2db418de8
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:89:9
  72:     0x55d6294efabc - tokio::runtime::task::harness::Harness<T,S>::poll::hd6135347522ed60f
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:59:15
  73:     0x55d629552ff2 - tokio::runtime::task::raw::poll::h1ff9ac99e80a0d75
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/raw.rs:104:5
  74:     0x55d629552eff - tokio::runtime::task::raw::RawTask::poll::h28b45349aeee56aa
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/raw.rs:66:18
  75:     0x55d6294fed01 - tokio::runtime::task::Notified<S>::run::h290b5ac28489684c
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/mod.rs:171:9
  76:     0x55d629517dd8 - tokio::runtime::blocking::pool::Inner::run::hb1bce7d9b035d58d
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/pool.rs:265:17
  77:     0x55d629517b69 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h9744f5a8cad85eb6
                               at /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/pool.rs:245:17
  78:     0x55d6294ed3cc - std::sys_common::backtrace::__rust_begin_short_backtrace::h598df8a60f91115d
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  79:     0x55d6295153d1 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h0a47aaed1ca4c6dc
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  80:     0x55d6295133c1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha8da20582852243b
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  81:     0x55d62950662c - std::panicking::try::do_call::ha0297dbfab79b15c
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  82:     0x55d62950f04d - __rust_try
  83:     0x55d629506471 - std::panicking::try::h3c96b7489d9add04
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  84:     0x55d6295146d1 - std::panic::catch_unwind::h646c70b5604d7875
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  85:     0x55d6295151c5 - std::thread::Builder::spawn_unchecked::{{closure}}::ha8993155bfe13b8d
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  86:     0x55d6295069ff - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e582427485c6e04
                               at /home/chip/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  87:     0x55d629979a4a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc444a77f8dd8d825
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  88:     0x55d629979a4a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8b68a0a9a2093dfc
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  89:     0x55d629979a4a - std::sys::unix::thread::Thread::new::thread_start::hb95464447f61f48d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  90:     0x7fac9b970259 - start_thread
  91:     0x7fac9b7555e3 - __GI___clone
  92:                0x0 - <unknown>
```

**Comment by lucasfernog** [comment]
Oops, I'll check this tomorrow. Thanks for finding it before the release!
