### ISSUE TITLE
macOS 12 beta support

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#2227]
**Is your feature request related to a problem? Please describe.**

Seems local storage do not work on macos 12...

**Describe the solution you'd like**
Probably connected with https://github.com/tauri-apps/tauri/issues/1570

**Describe alternatives you've considered**
N/A

**Additional context**
We should do more testing and add more context.

To be completed

**Comment by NeoEvaX** [comment]
Steps to Reproduce:

1. npm start
2. npm run tauri dev
3. performing a localStorage.setItem("test", 1); crashes the development server with this error:

```
node:events:371
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid status code 22373
    at Receiver.controlMessage (/Users/iankremer/Development/init-tracker/node_modules/webpack-dev-server/node_modules/ws/lib/receiver.js:449:18)
    at Receiver.getData (/Users/iankremer/Development/init-tracker/node_modules/webpack-dev-server/node_modules/ws/lib/receiver.js:335:42)
    at Receiver.startLoop (/Users/iankremer/Development/init-tracker/node_modules/webpack-dev-server/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/Users/iankremer/Development/init-tracker/node_modules/webpack-dev-server/node_modules/ws/lib/receiver.js:74:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/Users/iankremer/Development/init-tracker/node_modules/webpack-dev-server/node_modules/ws/lib/websocket.js:864:35)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/Users/iankremer/Development/init-tracker/node_modules/webpack-dev-server/node_modules/ws/lib/websocket.js:769:13)
    at Receiver.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  [Symbol(status-code)]: 1002
}
```

The tauri server keeps running, but the window goes white. Full crash of the node server running. 
If I do a build of the application and run that, it works fine. As does running the app in the browser from just the development server.

Including a very basic version of code that does this.
[Init-Tracker-main.zip](https://github.com/tauri-apps/tauri/files/6832510/Init-Tracker-main.zip)

tauri info
```
Operating System - Mac OS, version 12.0.0 X64

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.19.1
  yarn - Not installed

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/public
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by lucasfernog** [comment]
Can you guys check if it works after #2444?

**Comment by NeoEvaX** [comment]
> Can you guys check if it works after #2444?

I updated @tauri-apps/api from 1.0.0-beta.5 to 1.0.0-beta.6 and it seems to be working now.

Thank you.

**Comment by lemarier** [comment]
Awesome thanks !
