### ISSUE TITLE
Asset `35729/livereload.js` not found; fallback to index.html (examples/api)

### ISSUE THREAD

**Issue by Y2KForever** [tauri-apps/tauri#2355]
### **Describe the bug**
Trying to run the example in example/api results in the tauri app to show only a grey background, with the console saying: 
`Asset 35729/livereload.js not found; fallback to index.html`

### **To Reproduce**
Clone the latest release and follow the instructions in the README.md inside example/api.

### **Expected behavior**
The app to look the same as the screenshot in example/api.

### **Screenshots**
![image](https://user-images.githubusercontent.com/38052875/128251650-440a3687-1588-4dca-b92b-4fdd9d87daeb.png)

### **Platform and Versions (required):**
```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 92.0.902.62

Node.js environment
  Node.js - 14.15.4
  @tauri-apps/cli - 1.0.0-beta.6

Global packages
  npm - 6.14.10
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - path:"../../../core/tauri" [1.0.0-beta.5] (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: asset: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - ../public
  framework - Svelte
  bundler - Rollup
```

**Comment by Y2KForever** [comment]
Update:

Tried to compile the beta2 instead of beta5, that works fine, so it seem the problem is with the newest release.
Compiling the project again shows a few errors that did not come up during the beta2.

```
$ rimraf ./dist && rollup -c --silent && node ./scripts/after-build.cjs
babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
(!) Plugin typescript: @rollup/plugin-typescript TS2578: Unused '@ts-expect-error' directive.
src\window.ts: (198:3)

198   // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~

src\window.ts: (210:3)

210   // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2345: Argument of type '{ skip: boolean; }' is not assignable to parameter of type 'WindowOptions'.
  Object literal may only specify known properties, and 'skip' does not exist in type 'WindowOptions'.
src\window.ts: (200:5)
y only specify known properties, and 'skip' does not exist in type 'WindowOptions'.

200     skip: true
        ~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2345: Argument of type 'WindowDef' is not assignable to parameter of type 'string'.
src\window.ts: (212:30)

212     (w) => new WebviewWindow(w, { skip: true })
                                 ~

[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src\fs.ts (38:7)
36: import { invokeTauriCommand } from './helpers/tauri'
37:
38: export enum BaseDirectory {
           ^
39:   Audio = 1,
40:   Cache,
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Users\Hansen\Desktop\tauri-tauri-v1.0.0-beta.5\tooling\api\node_modules\rollup\dist\shared\rollup.js:151:30)
    at Module.error (C:\Users\Hansen\Desktop\tauri-tauri-v1.0.0-beta.5\tooling\api\node_modules\rollup\dist\shared\rollup.js:9995:16)
    at Module.tryParse (C:\Users\Hansen\Desktop\tauri-tauri-v1.0.0-beta.5\tooling\api\node_modules\rollup\dist\shared\rollup.js:10398:25)
    at Module.setSource (C:\Users\Hansen\Desktop\tauri-tauri-v1.0.0-beta.5\tooling\api\node_modules\rollup\dist\shared\rollup.js:10301:24)
    at ModuleLoader.addModuleSource (C:\Users\Hansen\Desktop\tauri-tauri-v1.0.0-beta.5\tooling\api\node_modules\rollup\dist\shared\rollup.js:19662:20)
    at ModuleLoader.fetchModule (C:\Users\Hansen\Desktop\tauri-tauri-v1.0.0-beta.5\tooling\api\node_modules\rollup\dist\shared\rollup.js:19718:9)
    at async Promise.all (index 1)

error Command failed with exit code 1.
```

This is when running the `./.scripts/setup.ps1` script.

**Comment by amrbashir** [comment]
You should always check out the latest commits, a lot of fixes happened.

Follow these steps:
1. run `.scripts/setup.ps1` and say yes to install nodejs cli
2. `cd examples/api`
3. `yarn install`
4. `yarn tauri dev`

**Comment by Y2KForever** [comment]
> 
> 
> You should always check out the latest commits, a lot of fixes happened.
> 
> Follow these steps:
> 
>     1. run `.scripts/setup.ps1` and say yes to install nodejs cli
> 
>     2. `cd examples/api`
> 
>     3. `yarn install`
> 
>     4. `yarn tauri dev`

Cloned the lastest dev, followed your instructions still the same result.

![image](https://user-images.githubusercontent.com/38052875/128570876-a1f323e7-9e8f-4a6d-9796-1920ba353ac7.png)
![image](https://user-images.githubusercontent.com/38052875/128570965-fc2425f4-ecfd-487f-99c7-3e7c594077f2.png)

**Comment by amrbashir** [comment]
Seems like something goes wrong when it tries to build `tooling/api` can you run `yarn build` in that folder and see if it throws any errors

**Comment by Y2KForever** [comment]
EDIT: I was a bit tired last night when I read what you wrote.
I ran `yarn build` inside `tooling/api` and it does produce the same error.

```
yarn run v1.22.10
$ rimraf ./dist && rollup -c --silent && node ./scripts/after-build.cjs
babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src\app.ts (19:27)
17:  * @returns A promise resolving to the application version.
18:  */
19: async function getVersion(): Promise<string> {
                               ^
20:   return invokeTauriCommand<string>({
21:     __tauriModule: 'App',
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Users\Hansen\Desktop\tauri-2\tauri\tooling\api\node_modules\rollup\dist\shared\rollup.js:151:30)
    at Module.error (C:\Users\Hansen\Desktop\tauri-2\tauri\tooling\api\node_modules\rollup\dist\shared\rollup.js:9995:16)
    at Module.tryParse (C:\Users\Hansen\Desktop\tauri-2\tauri\tooling\api\node_modules\rollup\dist\shared\rollup.js:10398:25)
    at Module.setSource (C:\Users\Hansen\Desktop\tauri-2\tauri\tooling\api\node_modules\rollup\dist\shared\rollup.js:10301:24)
    at ModuleLoader.addModuleSource (C:\Users\Hansen\Desktop\tauri-2\tauri\tooling\api\node_modules\rollup\dist\shared\rollup.js:19662:20)
    at ModuleLoader.fetchModule (C:\Users\Hansen\Desktop\tauri-2\tauri\tooling\api\node_modules\rollup\dist\shared\rollup.js:19718:9)
    at async Promise.all (index 0)

error Command failed with exit code 1.
```

**Comment by lucasfernog** [comment]
Looks like a problem with your setup since it works on my machine and it also works on CI. Please reach out on our Discord and we'll help you.

Also this is a good resource to follow: https://github.com/tauri-apps/tauri/blob/dev/.github/CONTRIBUTING.md
