### ISSUE TITLE
Windows Notification API requestPermission causes application crash

### ISSUE THREAD

**Issue by youngsing** [tauri-apps/tauri#2652]
I used below code to request Permission:
```code
Notification.requestPermission().then((status) => {
      console.log(status)
      const n = new Notification('title', { body: 'notification body' })
    })
```

And it crashed with:
```code
thread 'main' panicked at 'This API cannot be called on the main thread. Try using `std::thread::spawn` or `tauri::async_runtime::spawn`.', C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.2.1\src\lib.rs:1129:8
stack backtrace:
   0: std::panicking::begin_panic<str>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\std\src\panicking.rs:541
   1: tauri_runtime_wry::impl$32::hwnd
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.2.1\src\lib.rs:1129
   2: tauri::window::Window<tauri_runtime_wry::Wry>::hwnd<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\window.rs:525
   3: tauri::api::dialog::window_parent<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\api\dialog.rs:68
   4: tauri::api::dialog::ask<tauri_runtime_wry::Wry,tauri::endpoints::notification::request_permission::closure$0,str,str>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\api\dialog.rs:156
   5: tauri::endpoints::notification::request_permission<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\endpoints\notification.rs:114
   6: enum$<tauri::endpoints::notification::Cmd>::run<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\endpoints\notification.rs:64
   7: tauri::endpoints::impl$1::run::closure$10<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\endpoints.rs:130
   8: tauri::hooks::InvokeResolver<tauri_runtime_wry::Wry>::return_closure<tauri_runtime_wry::Wry,enum$<serde_json::value::Value>,tauri::endpoints::impl$1::run::closure$10>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\hooks.rs:215
   9: tauri::hooks::InvokeResolver<tauri_runtime_wry::Wry>::respond_closure<tauri_runtime_wry::Wry,enum$<serde_json::value::Value>,tauri::endpoints::impl$1::run::closure$10>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\hooks.rs:168
  10: enum$<tauri::endpoints::Module>::run<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\endpoints.rs:129
  11: tauri::endpoints::handle<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\endpoints.rs:176
  12: tauri::window::Window<tauri_runtime_wry::Wry>::on_message<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\window.rs:218
  13: tauri::manager::impl$2::prepare_rpc_handler::closure$0<tauri_runtime_wry::Wry>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\manager.rs:396
  14: alloc::boxed::impl$46::call<tuple$<tauri_runtime::window::DetachedWindow<tauri_runtime_wry::Wry>,tauri_runtime::webview::RpcRequest>,dyn$<core::ops::function::Fn<tuple$<tauri_runtime::window::DetachedWindow<tauri_runtime_wry::Wry>,tauri_runtime::webview::
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\alloc\src\boxed.rs:1586
  15: tauri_runtime_wry::create_rpc_handler::closure$0
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.2.1\src\lib.rs:2502
  16: alloc::boxed::impl$46::call<tuple$<ref$<tao::window::Window>,wry::webview::RpcRequest>,dyn$<core::ops::function::Fn<tuple$<ref$<tao::window::Window>,wry::webview::RpcRequest>,assoc$<Output,enum$<core::option::Option<wry::webview::RpcResponse>, 0, 6, Some>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\alloc\src\boxed.rs:1586
  17: alloc::boxed::impl$46::call<tuple$<ref$<tao::window::Window>,wry::webview::RpcRequest>,dyn$<core::ops::function::Fn<tuple$<ref$<tao::window::Window>,wry::webview::RpcRequest>,assoc$<Output,enum$<core::option::Option<wry::webview::RpcResponse>, 0, 6, Some>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\alloc\src\boxed.rs:1586
  18: wry::webview::rpc_proxy
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\wry-0.12.2\src\webview\mod.rs:435
  19: wry::webview::webview2::impl$0::new::closure$0::closure$0::closure$3
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\wry-0.12.2\src\webview\webview2\mod.rs:174
  20: webview2::impl$4::add_web_message_received::closure$0<wry::webview::webview2::impl$0::new::closure$0::closure$0::closure$3>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-0.1.3\src\lib.rs:991
  21: alloc::boxed::impl$46::call<tuple$<ptr_mut$<ptr_mut$<webview2_sys::ICoreWebView2VTable> >,ptr_mut$<ptr_mut$<webview2_sys::ICoreWebView2WebMessageReceivedEventArgsVTable> > >,dyn$<core::ops::function::Fn<tuple$<ptr_mut$<ptr_mut$<webview2_sys::ICoreWebView2
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\alloc\src\boxed.rs:1586
  22: webview2::impl$4::add_web_message_received::impl$0::invoke::closure$0
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-0.1.3\src\lib.rs:96
  23: core::ops::function::FnOnce::call_once<webview2::impl$4::add_web_message_received::impl$0::invoke::closure$0,tuple$<> >
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\ops\function.rs:227
  24: std::panic::impl$30::call_once<i32,webview2::impl$4::add_web_message_received::impl$0::invoke::closure$0>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\std\src\panic.rs:347
  25: std::panicking::try::do_call<std::panic::AssertUnwindSafe<webview2::impl$4::add_web_message_received::impl$0::invoke::closure$0>,i32>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\std\src\panicking.rs:401
  26: std::panicking::begin_panic::impl$1::take_box<str>
  27: std::panicking::try<i32,std::panic::AssertUnwindSafe<webview2::impl$4::add_web_message_received::impl$0::invoke::closure$0> >
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\std\src\panicking.rs:365
  28: std::panic::catch_unwind<std::panic::AssertUnwindSafe<webview2::impl$4::add_web_message_received::impl$0::invoke::closure$0>,i32>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\std\src\panic.rs:434
  29: webview2::impl$4::add_web_message_received::impl$0::invoke
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-0.1.3\src\lib.rs:95
  30: webview2_sys::impl$353::vtable::icorewebview2webmessagereceivedeventhandler_invoke<webview2::impl$4::add_web_message_received::Impl,com::offset::Zero>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\webview2-sys-0.1.1\src\lib.rs:3286
  31: CreateWebViewEnvironmentWithOptionsInternal
  32: DllCanUnloadNow
  33: DllCanUnloadNow
  34: DllCanUnloadNow
  35: DllCanUnloadNow
  36: DllCanUnloadNow
  37: DllCanUnloadNow
  38: DllCanUnloadNow
  39: DllCanUnloadNow
  40: DllCanUnloadNow
  41: DllCanUnloadNow
  42: DllCanUnloadNow
  43: Ordinal0
  44: DllCanUnloadNow
  45: CallWindowProcW
  46: DispatchMessageW
  47: tao::platform_impl::platform::event_loop::EventLoop<enum$<tauri_runtime_wry::Message> >::run_return<enum$<tauri_runtime_wry::Message>,tauri_runtime_wry::impl$36::run::closure$0>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop.rs:248
  48: tao::platform_impl::platform::event_loop::EventLoop<enum$<tauri_runtime_wry::Message> >::run<enum$<tauri_runtime_wry::Message>,tauri_runtime_wry::impl$36::run::closure$0>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop.rs:203
  49: tao::event_loop::EventLoop<enum$<tauri_runtime_wry::Message> >::run<enum$<tauri_runtime_wry::Message>,tauri_runtime_wry::impl$36::run::closure$0>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\event_loop.rs:151
  50: tauri_runtime_wry::impl$36::run<tauri::app::impl$13::run::closure$0>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.2.1\src\lib.rs:1797
  51: tauri::app::App<tauri_runtime_wry::Wry>::run<tauri_runtime_wry::Wry,tauri::app::impl$15::run::closure$0>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\app.rs:431
  52: tauri::app::Builder<tauri_runtime_wry::Wry>::run<tauri_runtime_wry::Wry,tauri_utils::assets::EmbeddedAssets>
             at C:\Users\youngsing\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-beta.8\src\app.rs:1040
  53: app::main
             at .\src\main.rs:7
  54: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
webview2: panic in callback function. Aborting because it's UB to unwind across FFI boundaries.
error: process didn't exit successfully: `target\debug\app.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

yarn tauri info:
```cdoe
Operating System - Windows, version 10.0.19043 X64
Webview2 - 93.0.961.52

Node.js environment
  Node.js - 14.15.3
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.9
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/assets
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - React
```

**Comment by FabianLars** [comment]
this should be fixed on the `next` branch. If you want to try it out, change the tauri dependency in Cargo.toml to something similar to this:
```tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all"] }```

**Comment by youngsing** [comment]
Thanks! It worked after switching to the `next` branch.
