### ISSUE TITLE
Can't create a New Tauri Project

### ISSUE THREAD

**Issue by nurmohammed840** [tauri-apps/tauri#2665]
Getting weird Error... 

```
❯ npm x create-tauri-app
We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This should get you started. See our docs at https://tauri.studio/
If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/getting-started/setup-windows/
Press any key to continue...
? What is your app name? hadis
? What should the window title be? Hadis
? What UI recipe would you like to add? create-react-app (https://create-react-app.dev/)
? Add "@tauri-apps/api" npm package? No
? Which create-react-app template would you like to use? create-react-app (Typescript)
>> Running initial command(s)

Creating a new React app in E:\projects\hadis.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-typescript...


added 1934 packages, and audited 1935 packages in 5m

150 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

Initialized a git repository.

Installing template dependencies using npm...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@27.2.2',
npm WARN EBADENGINE   required: { node: '^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/types@27.1.1',
npm WARN EBADENGINE   required: { node: '^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }

added 48 packages, changed 1 package, and audited 1983 packages in 41s

151 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

We detected TypeScript in your project (src\App.test.tsx) and created a tsconfig.json file for you.

Your tsconfig.json has been populated with default values.

Removing template package using npm...

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/types@27.1.1',
npm WARN EBADENGINE   required: { node: '^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@27.2.2',
npm WARN EBADENGINE   required: { node: '^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }

removed 1 package, and audited 1982 packages in 8s

151 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

Created git commit.

Success! Created hadis at E:\projects\hadis
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd hadis
  npm start

Happy hacking!
>> Installing any additional needed dependencies
- Installing @tauri-apps/cli@latest...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/types@27.1.1',
npm WARN EBADENGINE   required: { node: '^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@27.2.2',
npm WARN EBADENGINE   required: { node: '^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'globby@12.0.2',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 421 packages, and audited 2403 packages in 1m

191 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (10 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
>> Updating "package.json"
>> Running "tauri init"

> hadis@0.1.0 tauri
> tauri "init" "--app-name" "hadis" "--window-title" "Hadis" "--dist-dir" "../build" "--dev-path" "http://localhost:3000" "--ci"

(node:10600) UnhandledPromiseRejectionWarning: file:///E:/projects/hadis/node_modules/@tauri-apps/cli/dist/helpers/download-binary.js:1
import{_ as r,a as t}from"../tslib.es6-753a81cf.js";import{promisify as o}from"util";import n from"stream";import i from"fs";import e from"path";import{bootstrap as s}from"global-agent";import{fileURLToPath as a}from"url";import{createRequire as c}from"module";var u=e.dirname(a(import.meta.url)),l=c(import.meta.url)("got"),p=o(n.pipeline),m={};function f(o,n,e){return r(this,void 0,void 0,(function(){var r,a;return t(this,(function(t){switch(t.label){case 0:return r="https://github.com/tauri-apps/binary-releases/releases/download/"+o+"/"+n,a=function(){try{r in m||i.unlinkSync(e)}finally{process.exit()}},process.on("exit",a),process.on("SIGINT",a),process.on("SIGTERM",a),process.on("SIGHUP",a),process.on("SIGBREAK",a),s({environmentVariableNamespace:""}),[4,p(l.stream(r),i.createWriteStream(e)).catch((function(r){try{i.unlinkSync(e)}catch(r){}throw r}))];case 1:return t.sent(),m[r]=!0,i.chmodSync(e,448),console.log("Download Complete"),[2]}}))}))}function d(){return r(this,void 0,void 0,(function(){var r,o,n;return t(this,(function(t){switch(t.label){case 0:if("win32"===(r=process.platform))r="windows";else if("linux"===r)r="linux";else{if("darwin"!==r)throw Error("Unsupported platform");r="macos"}return o="windows"===r?".exe":"",n=e.join(u,"../../bin/tauri-cli"+o),console.log("Downloading Rust CLI..."),[4,f("tauri-cli-v1.0.0-beta.7","tauri-cli_"+r+o,n)];case 1:return t.sent(),[2]}}))}))}function h(){return r(this,void 0,void 0,(function(){var r;return t(this,(function(t){switch(t.label){case 0:return r="win32"===process.platform?"rustup-init.exe":"rustup-init.sh",console.log("Downloading Rustup..."),[4,f("rustup",r,e.join(u,"../../bin/"+r))];case 1:return[2,t.sent()]}}))}))}export{d as downloadCli,h as downloadRustup};
                                                                                                                                                        ^^^^^^^^^
SyntaxError: The requested module 'global-agent' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'global-agent';
const {_: r,a: t}from"../tslib.es6-753a81cf.js";import{promisify: o}from"util";import n from"stream";import i from"fs";import e from"path";import{bootstrap: s}from"global-agent";import{fileURLToPath: a}from"url";import{createRequire: c}from"module";var u=e.dirname(a(import.meta.url)),l=c(import.meta.url)("got"),p=o(n.pipeline),m={};function f(o,n,e){return r(this,void 0,void 0,(function(){var r,a;return t(this,(function(t){switch(t.label){case 0:return r="https://github.com/tauri-apps/binary-releases/releases/download/"+o+"/"+n,a=function(){try{r in m||i.unlinkSync(e)}finally{process.exit()}},process.on("exit",a),process.on("SIGINT",a),process.on("SIGTERM",a),process.on("SIGHUP",a),process.on("SIGBREAK",a),s({environmentVariableNamespace:""}),[4,p(l.stream(r),i.createWriteStream(e)).catch((function(r){try{i.unlinkSync(e)}catch(r){}throw r}))];case 1:return t.sent(),m[r]=!0,i.chmodSync(e,448),console.log("Download Complete"),[2]}}))}))}function d(){return r(this,void 0,void 0,(function(){var r,o,n;return t(this,(function(t){switch(t.label){case 0:if("win32"===(r=process.platform))r="windows";else if("linux"===r)r="linux";else{if("darwin"!==r)throw Error("Unsupported platform");r="macos"}return o="windows"===r?".exe":"",n=e.join(u,"../../bin/tauri-cli"+o),console.log("Downloading Rust CLI..."),[4,f("tauri-cli-v1.0.0-beta.7","tauri-cli_"+r+o,n)];case 1:return t.sent(),[2]}}))}))}function h(){return r(this,void 0,void 0,(function(){var r;return t(this,(function(t){switch(t.label){case 0:return r="win32"===process.platform?"rustup-init.exe":"rustup-init.sh",console.log("Downloading Rustup..."),[4,f("rustup",r,e.join(u,"../../bin/"+r))];case 1:return[2,t.sent()]}}))}))}export{d: downloadCli,h: downloadRustup} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async tauri (file:///E:/projects/hadis/node_modules/@tauri-apps/cli/bin/tauri.js:73:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> Updating "tauri.conf.json"
Error: ENOENT: no such file or directory, open 'E:\projects\hadis\src-tauri\tauri.conf.json'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at updateTauriConf (C:\Users\nurmo\AppData\Local\Yarn\Data\global\node_modules\create-tauri-app\dist\index.js:555:32)
    at C:\Users\nurmo\AppData\Local\Yarn\Data\global\node_modules\create-tauri-app\dist\index.js:823:9
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\nurmo\AppData\Local\Yarn\Data\global\node_modules\create-tauri-app\dist\index.js:39:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\projects\\hadis\\src-tauri\\tauri.conf.json'
}
```

**Comment by amrbashir** [comment]
can you try to update your nodejs version to 14.17.6 ?

**Comment by nurmohammed840** [comment]
Problem fixed after updating NodeJS.
