### ISSUE TITLE
tauri build, an error occurred for windows 32bit!

### ISSUE THREAD

**Issue by txj123** [tauri-apps/tauri#2713]
app:spawn Running "C:\Users\ll\Desktop\tauri_demo\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri build" +0ms

(node:1184) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:667:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:871:17)
    at spawn (C:\Users\ll\Desktop\tauri_demo\node_modules\cross-spawn\index.js:12:24)
    at t (file:///C:/Users/ll/Desktop/tauri_demo/node_modules/@tauri-apps/cli/dist/helpers/spawn.js:1:219)
    at file:///C:/Users/ll/Desktop/tauri_demo/node_modules/@tauri-apps/cli/dist/helpers/rust-cli.js:1:771
    at file:///C:/Users/ll/Desktop/tauri_demo/node_modules/@tauri-apps/cli/dist/tslib.es6-753a81cf.js:1:1452
    at Object.next (file:///C:/Users/ll/Desktop/tauri_demo/node_modules/@tauri-apps/cli/dist/tslib.es6-753a81cf.js:1:1557)
    at file:///C:/Users/ll/Desktop/tauri_demo/node_modules/@tauri-apps/cli/dist/tslib.es6-753a81cf.js:1:494
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.72s.

**Comment by amrbashir** [comment]
Please fill out the issue template properly.
