### ISSUE TITLE
Window specific menu crashes program on button click

### ISSUE THREAD

**Issue by Cielquan** [tauri-apps/tauri#2962]
### **Describe the bug**
When I add a menu to a specific window like shown in the [official docs](https://tauri.studio/en/docs/usage/guides/visual/menu#adding-the-menu-to-a-specific-window) the window and menu render as expected. But when I click on a 'button' from the menu (not a submenu!) the program crashes at an '`unwrap()` called on a `None` value'. From the causing line in `window.rs` (see stack trace below) I assume that there is some issue with the retrieval of the `menu_item_id`.

### **To Reproduce**
1. Create a new tauri app
2. Change `main.rs` to below content (which just adds a menu to a window)
3. Start the program: `yarn tauri dev`
4. Click on the `Test` button in the menu of the second window
5. See the program crash

<details><summary>main.rs update</summary>
<p>

#### main.rs

```rust
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use tauri::{CustomMenuItem, Menu, WindowBuilder};

fn main() {
    tauri::Builder::default()
        .create_window(
            "test",
            tauri::WindowUrl::App("index.html".into()),
            move |window_builder, webview_attributes| {
                (
                    window_builder.menu(Menu::new().add_item(CustomMenuItem::new("test", "Test"))),
                    webview_attributes,
                )
            },
        )
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

```

</p>
</details>

### **Expected behavior**
The program should not crash and fire the menu event without error for the menu event listener to catch.

### **Screenshots**
No

### **Platform and Versions (required):**

```
Operating System - Linux Mint, version 20.1 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.15.1
  yarn - 1.22.10

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/dist
/src-tauri
/node_modules

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
```

### **Additional context**
I made this bug report base off of my linux maschine, but this error happens on my Win10 maschine too.
But there I need a custom build script because of issue #2871.

### **Stack Trace**
<details><summary>RUST_BACKTRACE=1</summary>
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/window.rs:297:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:735:21
   4: tauri::window::Window<R>::on_menu_event::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/window.rs:297:23
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1650:9
   6: tauri_runtime_wry::handle_event_loop
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.2.1/src/lib.rs:1889:9
   7: <tauri_runtime_wry::Wry as tauri_runtime::Runtime>::run::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.2.1/src/lib.rs:1798:7
   8: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.5.2/src/platform_impl/linux/event_loop.rs:700:22
   9: tao::platform_impl::platform::event_loop::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.5.2/src/platform_impl/linux/event_loop.rs:131:5
  10: tao::event_loop::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.5.2/src/event_loop.rs:151:5
  11: <tauri_runtime_wry::Wry as tauri_runtime::Runtime>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.2.1/src/lib.rs:1797:5
  12: tauri::app::App<R>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/app.rs:431:5
  13: tauri::app::Builder<R>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/app.rs:1040:5
  14: app::main
             at ./src/main.rs:9:3
  15: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

<details><summary>RUST_BACKTRACE=full</summary>
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/window.rs:297:57
stack backtrace:
   0:     0x555bfee8dc1c - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x555bfee8dc1c - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555bfee8dc1c - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555bfee8dc1c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x555bfeeb50dc - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x555bfee863f5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x555bfee8fd90 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x555bfee8fd90 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x555bfee8fd90 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x555bfee8f947 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x555bfee90444 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x555bfee8fef2 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:519:13
  12:     0x555bfee8e0e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x555bfee8fe89 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x555bfe219a41 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:     0x555bfe21998d - core::panicking::panic::hcb81dec512b2768f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
  16:     0x555bfe34ca6c - core::option::Option<T>::unwrap::h165de29b64b67df0
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:735:21
  17:     0x555bfe3dbc68 - tauri::window::Window<R>::on_menu_event::{{closure}}::h9501a7dcb7457bd0
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/window.rs:297:23
  18:     0x555bfea59350 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4260cff3ab822b24
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1650:9
  19:     0x555bfea0a4ef - tauri_runtime_wry::handle_event_loop::h254e361e322464c2
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.2.1/src/lib.rs:1889:9
  20:     0x555bfe509967 - <tauri_runtime_wry::Wry as tauri_runtime::Runtime>::run::{{closure}}::h539bf5c71e2e923e
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.2.1/src/lib.rs:1798:7
  21:     0x555bfe33c9eb - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::hf15aaff257335e44
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.5.2/src/platform_impl/linux/event_loop.rs:700:22
  22:     0x555bfe3441a2 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::hd4a610728417938e
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.5.2/src/platform_impl/linux/event_loop.rs:131:5
  23:     0x555bfe3302fa - tao::event_loop::EventLoop<T>::run::h2b9158090b0bb00d
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.5.2/src/event_loop.rs:151:5
  24:     0x555bfe509572 - <tauri_runtime_wry::Wry as tauri_runtime::Runtime>::run::h7970530376cdc0d2
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.2.1/src/lib.rs:1797:5
  25:     0x555bfe3d34cf - tauri::app::App<R>::run::hfec30d1c6cc4f29c
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/app.rs:431:5
  26:     0x555bfe3d3f52 - tauri::app::Builder<R>::run::h4d02f808ebb5c644
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/app.rs:1040:5
  27:     0x555bfe238bd7 - app::main::hb1d034ae25169a36
                               at /home/user/Projects/.testing/tauri-app/src-tauri/src/main.rs:9:3
  28:     0x555bfe55bcbb - core::ops::function::FnOnce::call_once::h0cf21d05684fd0ed
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  29:     0x555bfe3e809e - std::sys_common::backtrace::__rust_begin_short_backtrace::hb02288dceb7da940
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125:18
  30:     0x555bfe2fd301 - std::rt::lang_start::{{closure}}::h2c54cce0a1586356
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:63:18
  31:     0x555bfee90a4a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  32:     0x555bfee90a4a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  33:     0x555bfee90a4a - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  34:     0x555bfee90a4a - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  35:     0x555bfee90a4a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  36:     0x555bfee90a4a - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  37:     0x555bfee90a4a - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  38:     0x555bfee90a4a - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  39:     0x555bfee90a4a - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  40:     0x555bfe2fd2d0 - std::rt::lang_start::he8c39a79111da141
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:62:5
  41:     0x555bfe238c8c - main
  42:     0x7f06cdff20b3 - __libc_start_main
  43:     0x555bfe21a23e - _start
  44:                0x0 - <unknown>
```
</details>

### **Little Workaround**
I currently use the following workaround for my project. But it only works because I only have one main window and a splashscreen.

I just add the menu as a global menu and in the `setup()` call on the `Builder` hide the menu for the splashscreen like so:

```rust
let app = tauri::Builder::default()
    .setup(|app| {
        let splashscreen_window = app.get_window("splashscreen").unwrap();
        splashscreen_window.menu_handle().hide().unwrap();
    });
```

EDIT: Line breaks

**Comment by lucasfernog** [comment]
I believe this was fixed on the `next` branch, can you try that? Just change your src-tauri/Cargo.toml:
from `tauri = { version = "1.0.0-beta.8", ... }` to `tauri = { git = "https://github.com/tauri-apps/tauri/", branch = "next" }`.

**Comment by Cielquan** [comment]
Thanks for the fast reply 😃 

You are right the bug is fixed on `next` 👍🏾

**Comment by lucasfernog** [comment]
Amazing, thanks for the report!
