### ISSUE TITLE
"yarn create tauri-app" fails on Apple Silicon

### ISSUE THREAD

**Issue by e-oz** [tauri-apps/tauri#3088]
I've completed this step successfully: https://tauri.studio/en/docs/get-started/setup-macos  
Started this step: https://tauri.studio/en/docs/development/integration  

Please let me know if I can fix it with some workaround on my side.
<details>
<summary>Here is the log of "yarn create tauri-app" on MBP M1</summary>

```
oz@Avalon tmp % yarn create tauri-app
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-tauri-app@1.0.0-beta.4" with binaries:
      - create-tauri-app
[#####################################################################################################] 101/101We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This should get you started. See our docs at https://tauri.studio/
If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/getting-started/setup-macos/
Press any key to continue...
? What is your app name? example
? What should the window title be? Example
? What UI recipe would you like to add? Vanilla.js (html, css, and js without the bundlers)
? Add "@tauri-apps/api" npm package? Yes
>> Running initial command(s)
>> Installing any additional needed dependencies
- Installing @tauri-apps/cli@latest...
yarn add v1.22.17
warning package.json: No license field
info No lockfile found.
warning example: No license field
[1/4] 🔍  Resolving packages...
warning @tauri-apps/cli > imagemin-optipng > exec-buffer > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
warning Ignored scripts due to flag.
success Saved lockfile.
warning example: No license field
success Saved 304 new dependencies.
info Direct dependencies
└─ @tauri-apps/cli@1.0.0-beta.10
✨  Done in 9.25s.
- Installing @tauri-apps/api@latest...
yarn add v1.22.17
warning package.json: No license field
warning example: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning example: No license field
success Saved 1 new dependency.
info Direct dependencies
└─ @tauri-apps/api@1.0.0-beta.8
info All dependencies
└─ @tauri-apps/api@1.0.0-beta.8
✨  Done in 2.12s.
>> Updating "package.json"
>> Running "tauri init"
yarn run v1.22.17
warning package.json: No license field
$ tauri init --app-name example --window-title Example --dist-dir ../dist --dev-path ../dist --ci
Downloading Rust CLI...
Download Complete
 app:spawn Running "/Users/oz/repos/tmp/example/node_modules/@tauri-apps/cli/bin/tauri-cli tauri init --app-name example --window-title Example --dist-dir ../dist --dev-path ../dist --ci" +0ms

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error with command: yarn
Error: Error: Command failed with exit code 1: yarn tauri init --app-name example --window-title Example --dist-dir ../dist --dev-path ../dist --ci
    at /Users/oz/.config/yarn/global/node_modules/create-tauri-app/dist/index.js:63:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/oz/.config/yarn/global/node_modules/create-tauri-app/dist/index.js:40:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
✨  Done in 36.46s.
oz@Avalon tmp % 
oz@Avalon tmp % sudo /Users/oz/repos/tmp/example/node_modules/@tauri-apps/cli/bin/tauri-cli tauri init --app-name example --window-title Example --dist-dir ../dist --dev-path ../dist --ci
sudo: unable to execute /Users/oz/repos/tmp/example/node_modules/@tauri-apps/cli/bin/tauri-cli: Bad CPU type in executable
```

</details>

### **Platform and Versions (required):**

```
Mac OS Monterey 12.1
Node.js: v16.13.1
npm: 8.3.0
yarn: 1.22.17
rustc: 1.58.0-beta.2 (0e07bcb68 2021-12-04)
cargo: 1.58.0-beta (7f08ace4f 2021-11-24)
```

**Comment by e-oz** [comment]
Same for npm:

```
oz@Avalon tmp % npm x create-tauri-app
Need to install the following packages:
  create-tauri-app
Ok to proceed? (y) y
We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This should get you started. See our docs at https://tauri.studio/
If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/getting-started/setup-macos/
Press any key to continue...
? What is your app name? example
? What should the window title be? Example
? What UI recipe would you like to add? Vanilla.js (html, css, and js without the bundlers)
? Add "@tauri-apps/api" npm package? Yes
>> Running initial command(s)
>> Installing any additional needed dependencies
- Installing @tauri-apps/cli@latest...
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 478 packages, and audited 479 packages in 34s

59 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (10 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
- Installing @tauri-apps/api@latest...

added 1 package, and audited 480 packages in 3s

60 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (10 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
>> Updating "package.json"
>> Running "tauri init"

> tauri
> tauri "init" "--app-name" "example" "--window-title" "Example" "--dist-dir" "../dist" "--dev-path" "../dist" "--ci"

Downloading Rust CLI...
Download Complete
 app:spawn Running "/Users/oz/repos/tmp/example/node_modules/@tauri-apps/cli/bin/tauri-cli tauri init --app-name example --window-title Example --dist-dir ../dist --dev-path ../dist --ci" +0ms

Error with command: npm
Error: Error: Command failed with exit code 1: npm run tauri -- init --app-name example --window-title Example --dist-dir ../dist --dev-path ../dist --ci
    at /Users/oz/.npm/_npx/b58944764482de26/node_modules/create-tauri-app/dist/index.js:63:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/oz/.npm/_npx/b58944764482de26/node_modules/create-tauri-app/dist/index.js:40:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by e-oz** [comment]
Not sure if it might help, but here is log of 
<details>
<summary>npm i -g @tauri-apps/cli</summary>

```
oz@Avalon tmp % sudo npm i -g @tauri-apps/cli
Password:
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@tauri-apps/cli/node_modules/optipng-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! compiling from source
npm ERR! spawn Unknown system error -86
npm ERR! optipng pre-build test failed
npm ERR! Error: Command failed: /bin/sh -c make install
npm ERR! pngrtran.c:99:1: warning: unused function 'png_rtran_ok' [-Wunused-function]
npm ERR! png_rtran_ok(png_structrp png_ptr, int need_IHDR)
npm ERR! ^
npm ERR! 1 warning generated.
npm ERR! ld: warning: option -s is obsolete and being ignored
npm ERR! Undefined symbols for architecture arm64:
npm ERR!   "_png_init_filter_functions_neon", referenced from:
npm ERR!       _png_read_filter_row in libpng.a(pngrutil.o)
npm ERR! ld: symbol(s) not found for architecture arm64
npm ERR! clang: error: linker command failed with exit code 1 (use -v to see invocation)
npm ERR! make[1]: *** [optipng] Error 1
npm ERR! make: *** [install] Error 2
npm ERR! 
npm ERR! cd src/optipng && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make install && \
npm ERR! 	cd ../..
npm ERR! cd ../libpng && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make -f Makefile PNGLIBCONF_H_PREBUILT=pnglibconf.h.optipng && \
npm ERR! 	cd ../optipng
npm ERR! cp pnglibconf.h.optipng pnglibconf.h
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o png.o png.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngerror.o pngerror.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngget.o pngget.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngmem.o pngmem.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngpread.o pngpread.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngread.o pngread.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrio.o pngrio.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrtran.o pngrtran.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrutil.o pngrutil.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngset.o pngset.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngtrans.o pngtrans.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwio.o pngwio.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwrite.o pngwrite.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwtran.o pngwtran.c
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwutil.o pngwutil.c
npm ERR! ar rcs libpng.a png.o pngerror.o pngget.o pngmem.o pngpread.o pngread.o pngrio.o pngrtran.o pngrutil.o pngset.o pngtrans.o pngwio.o pngwrite.o pngwtran.o pngwutil.o
npm ERR! ranlib libpng.a
npm ERR! gcc -c -I../zlib  -O2 -Wall -Wextra -o pngtest.o pngtest.c
npm ERR! gcc  -L../zlib -o pngtest pngtest.o libpng.a -lz -lm
npm ERR! cd ../opngreduc && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make -f Makefile libopngreduc.a && \
npm ERR! 	cd ../optipng
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -o opngreduc.o opngreduc.c
npm ERR! ar cru libopngreduc.a opngreduc.o
npm ERR! ranlib libopngreduc.a
npm ERR! cd ../gifread && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make -f Makefile libgifread.a && \
npm ERR! 	cd ../optipng
npm ERR! gcc -c  -O2 -Wall -Wextra -o gifread.o gifread.c
npm ERR! ar cru libgifread.a gifread.o
npm ERR! ranlib libgifread.a
npm ERR! cd ../pnmio && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make -f Makefile libpnmio.a && \
npm ERR! 	cd ../optipng
npm ERR! gcc -c  -O2 -Wall -Wextra -o pnmin.o pnmin.c
npm ERR! gcc -c  -O2 -Wall -Wextra -o pnmout.o pnmout.c
npm ERR! gcc -c  -O2 -Wall -Wextra -o pnmutil.o pnmutil.c
npm ERR! ar cru libpnmio.a pnmin.o pnmout.o pnmutil.o
npm ERR! ranlib libpnmio.a
npm ERR! cd ../minitiff && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make -f Makefile libminitiff.a && \
npm ERR! 	cd ../optipng
npm ERR! gcc -c  -O2 -Wall -Wextra -o tiffread.o tiffread.c
npm ERR! gcc -c  -O2 -Wall -Wextra -o tiffutil.o tiffutil.c
npm ERR! ar cru libminitiff.a tiffread.o tiffutil.o 
npm ERR! ranlib libminitiff.a
npm ERR! cd ../pngxtern && \
npm ERR! 	/Library/Developer/CommandLineTools/usr/bin/make -f Makefile libpngxtern.a && \
npm ERR! 	cd ../optipng
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxread.o pngxread.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrbmp.o pngxrbmp.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrgif.o pngxrgif.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrjpg.o pngxrjpg.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrpnm.o pngxrpnm.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrtif.o pngxrtif.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxio.o pngxio.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxmem.o pngxmem.c
npm ERR! gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxset.o pngxset.c
npm ERR! ar cru libpngxtern.a pngxread.o pngxrbmp.o pngxrgif.o pngxrjpg.o pngxrpnm.o pngxrtif.o pngxio.o pngxmem.o pngxset.o
npm ERR! ranlib libpngxtern.a
npm ERR! gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o optipng.o optipng.c
npm ERR! gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o optim.o optim.c
npm ERR! gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o bitset.o bitset.c
npm ERR! gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o ioutil.o ioutil.c
npm ERR! gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o ratio.o ratio.c
npm ERR! gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o wildargs.o wildargs.c
npm ERR! gcc -s -o optipng optipng.o optim.o bitset.o ioutil.o ratio.o wildargs.o ../opngreduc/libopngreduc.a ../pngxtern/libpngxtern.a ../libpng/libpng.a  ../gifread/libgifread.a ../pnmio/libpnmio.a ../minitiff/libminitiff.a  -lz -lm 
npm ERR! 
npm ERR!     at /usr/local/lib/node_modules/@tauri-apps/cli/node_modules/execa/index.js:231:11
npm ERR!     at runMicrotasks (<anonymous>)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async /usr/local/lib/node_modules/@tauri-apps/cli/node_modules/optipng-bin/lib/install.js:17:4

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oz/.npm/_logs/2021-12-19T11_28_16_595Z-debug-0.log
```

[2021-12-19T11_28_16_595Z-debug-0.log](https://gist.github.com/e-oz/5b342f9c51f2bf88e32a2b3dc2a3e0af)
</details

**Comment by amrbashir** [comment]
I think this is because we only pre-built the rust cli for x86_x64 arch and not arm so I am marking this as duplicate of #2421. Unfortunately the only workaround I see is to compile our rust cli yourself and use it directly and don't use create-tauri-app. Hopefully the next release we will provide a prebuilt binary for all archs.

**Comment by Borber** [comment]
> I think this is because we only pre-built the rust cli for x86_x64 arch and not arm so I am marking this as duplicate of #2421. Unfortunately the only workaround I see is to compile our rust cli yourself and use it directly and don't use create-tauri-app. Hopefully the next release we will provide a prebuilt binary for all archs.

So how do we create a tauri-app quickly now? I'm a bit confused

**Comment by amrbashir** [comment]
@Borber
you have to do it manually. the following instructions can be used until the next release

1. first install tauri-cli from git using cargo
```sh
cargo install tauri-cli --git https://github.com/tauri-apps/tauri
```
2. bootstrap your javascript project using whatever framework you like, for example, `create-react-app` and cd into it.
3. init tauri project there
```sh
cargo tauri init 
```
4. modify `devPath` and `distDir` inside `src-tauri/tauri.conf.json` according to your framework devServer url and build output
5. start tauri dev
```
cargo tauri dev
```

**Comment by lwjcjmx123** [comment]
@amrbashir 
first should be 
```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri
```

**Comment by amrbashir** [comment]
sorry, updated the instructions.
