### ISSUE TITLE
[bug] `getter!` macro panics with `'called 'Result::unwrap()' on an 'Err' value: RecvError'` when sender is disconnected

### ISSUE THREAD

**Issue by AhmadAlHallak** [tauri-apps/tauri#3188]
### Describe the bug

Calling `window.outer_position()` and other similar methods that use the `getter!` macro somewhere in the call stack may result in a ` 'Result::unwrap()' on an 'Err' value: RecvError` panic when the channel sender is disconnected (because a window was closed for example). 

This is due to using `.unwrap()` on the result of `rx.recv()` in `tauri-runtime-wry/src/lib.rs:140`.

I believe that this shouldn't occur, and that there should be a new runtime error similar to `tauri::Error::FailedToSendMessage` (`FailedToReceiveMessage` maybe?) that the `getter!` would return instead of just unwrapping and causing a panic

### Reproduction

1. Start Tauri and create a window
2. Then run the following code:
```rust
let windows = app.windows(); // app is an instance of App
let window = windows.get(&window_label).unwrap(); // window_label is a label of a previously created and still open window
window.close();
window.outer_position(); // ` `Result::unwrap()` on an `Err` value: RecvError'`` panic occurs here.
```

### Expected behavior

An error should be returned instead of panicking, as this could easily happen (without doing it on purpose like in the example), and this should not be considered a fatal error.

### Platform and versions

```shell
Operating System - Windows, version 10.0.19042 X64
Webview2 - 97.0.1072.55

Node.js environment
  Node.js - 15.6.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.4.2
  yarn - 1.5.1

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/.git
/.vscode
/dist
/node_modules
/public
/src
/src-tauri
/target

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
```

### Stack trace

```shell
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', C:\Users\Ahmad\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\46f2eae\core\tauri-runtime-wry\src\lib.rs:1144:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\panicking.rs:100
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\result.rs:1616
   3: enum$<core::result::Result<enum$<core::result::Result<tauri_runtime::window::dpi::PhysicalPosition<i32>,enum$<tauri_runtime::Error> > >,std::sync::mpsc::RecvError>, 0, 1, Ok>::unwrap<enum$<core::result::Result<tauri_runtime::window::dpi::PhysicalPosition<
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\result.rs:1298
   4: tauri_runtime_wry::impl$38::outer_position        
             at C:\Users\Ahmad\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\46f2eae\core\tauri-runtime-wry\src\lib.rs:1144
   5: tauri::window::Window<tauri_runtime_wry::Wry>::outer_position<tauri_runtime_wry::Wry>
             at C:\Users\Ahmad\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\46f2eae\core\tauri\src\window.rs:415 
   6: auto_lang::gui::notify_window::create_notify_window::closure$0
             at .\src\gui\notify_window.rs:97
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

I can make a pull request to fix this issue if you would like.

**Comment by amrbashir** [comment]
Thanks for the detailed report. A PR sounds fantastic.

**Comment by AhmadAlHallak** [comment]
Ok, will hopefully have something ready for you guys to review soon.
