### ISSUE TITLE
[bug] Failed to run `yarn create tauri-app`

### ISSUE THREAD

**Issue by lomirus** [tauri-apps/tauri#3338]
### Describe the bug

I always use tauri on my Manjaro PC and it works fine. But today I want to try it on the Windows platform. So I ran the `yarn create tauri-app` in my powershell, but it gave me such errors (the last few lines):

```
error D:\tauri-app\node_modules\zopflipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\tauri-app\node_modules\zopflipng-bin
Output:
node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:167:9)
    at Object.<anonymous> (D:\tauri-app\node_modules\npm-conf\lib\defaults.js:31:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {



Error with command: yarn
Error: Error: Command failed with exit code 1: yarn add @tauri-apps/api@latest
    at C:\Users\28154\.config\yarn\global\node_modules\create-tauri-app\dist\index.js:63:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\28154\.config\yarn\global\node_modules\create-tauri-app\dist\index.js:40:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Done in 150.89s.
```

At first I thought it might be problem of my node version, so I downgrade it to 16 from 17, and so did the npm. But it still did not work.

### Reproduction

Just run `yarn create tauri` in the powershell.

### Expected behavior

Create tauri-app successfully without any error

### Platform and versions

```shell
OS: Windows 11 21H2 Professional
Node: v16.13.2
npm: 8.1.2
yarn: 1.22.17
rustup: 1.24.3 (ce5817a94 2021-05-31)
rustc: 1.58.0 (02072b482 2022-01-11)
```

### Stack trace

<details>

<summary>Whole Output</summary>

```
PS D:\> yarn create tauri-app
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-tauri-app@1.0.0-beta.4" with binaries:
      - create-tauri-app
[###########################################################################################################] 107/107We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This should get you started. See our docs at https://tauri.studio/
If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/getting-started/setup-windows/
Press any key to continue...
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-vite (https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
? Add "@tauri-apps/api" npm package? Yes
? Which vite template would you like to use? react-ts
>> Running initial command(s)
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-vite@2.7.2" with binaries:
      - create-vite
      - cva
[###########################################################################################################] 107/107
Scaffolding project in D:\tauri-app...

Done. Now run:

  cd tauri-app
  yarn
  yarn dev

Done in 2.02s.
>> Installing any additional needed dependencies
- Installing @tauri-apps/cli@latest...
yarn add v1.22.17
warning package.json: No license field
info No lockfile found.
warning tauri-app@0.0.0: No license field
[1/4] Resolving packages...
warning @tauri-apps/cli > imagemin-optipng > exec-buffer > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
success Saved lockfile.
warning tauri-app@0.0.0: No license field
success Saved 360 new dependencies.
info Direct dependencies
├─ @tauri-apps/cli@1.0.0-beta.10
├─ @types/react-dom@17.0.11
├─ @types/react@17.0.39
├─ @vitejs/plugin-react@1.1.4
├─ react-dom@17.0.2
├─ react@17.0.2
├─ typescript@4.5.5
└─ vite@2.7.13
info All dependencies
├─ @ampproject/remapping@2.0.4
├─ @babel/compat-data@7.17.0
├─ @babel/core@7.17.0
├─ @babel/helper-annotate-as-pure@7.16.7
├─ @babel/helper-compilation-targets@7.16.7
├─ @babel/helper-function-name@7.16.7
├─ @babel/helper-get-function-arity@7.16.7
├─ @babel/helper-hoist-variables@7.16.7
├─ @babel/helper-module-transforms@7.16.7
├─ @babel/helper-simple-access@7.16.7
├─ @babel/helper-validator-option@7.16.7
├─ @babel/helpers@7.17.0
├─ @babel/highlight@7.16.10
├─ @babel/parser@7.17.0
├─ @babel/plugin-syntax-jsx@7.16.7
├─ @babel/plugin-transform-react-jsx-development@7.16.7
├─ @babel/plugin-transform-react-jsx-self@7.16.7
├─ @babel/plugin-transform-react-jsx-source@7.16.7
├─ @babel/plugin-transform-react-jsx@7.16.7
├─ @jridgewell/resolve-uri@3.0.4
├─ @jridgewell/sourcemap-codec@1.4.10
├─ @jridgewell/trace-mapping@0.3.2
├─ @nodelib/fs.scandir@2.1.5
├─ @nodelib/fs.stat@2.0.5
├─ @nodelib/fs.walk@1.2.8
├─ @rollup/pluginutils@4.1.2
├─ @sindresorhus/is@4.4.0
├─ @szmarczak/http-timer@4.0.6
├─ @tauri-apps/cli@1.0.0-beta.10
├─ @tauri-apps/toml@2.2.4
├─ @types/cacheable-request@6.0.2
├─ @types/http-cache-semantics@4.0.1
├─ @types/keyv@3.1.3
├─ @types/prop-types@15.7.4
├─ @types/react-dom@17.0.11
├─ @types/react@17.0.39
├─ @types/responselike@1.0.0
├─ @types/scheduler@0.16.2
├─ @vitejs/plugin-react@1.1.4
├─ ansi-align@3.0.1
├─ ansi-escapes@4.3.2
├─ ansi-styles@4.3.0
├─ aproba@1.2.0
├─ arch@2.2.0
├─ archive-type@4.0.0
├─ are-we-there-yet@1.1.7
├─ array-find-index@1.0.2
├─ array-union@3.0.1
├─ balanced-match@1.0.2
├─ base64-js@1.5.1
├─ bin-check@4.1.0
├─ bin-version-check@4.0.0
├─ bin-version@3.1.0
├─ bin-wrapper@4.1.0
├─ bl@4.1.0
├─ boxen@5.1.2
├─ brace-expansion@1.1.11
├─ braces@3.0.2
├─ browserslist@4.19.1
├─ buffer-alloc-unsafe@1.1.0
├─ buffer-alloc@1.2.0
├─ buffer-crc32@0.2.13
├─ buffer-fill@1.0.0
├─ buffer@5.7.1
├─ cacheable-lookup@5.0.4
├─ cacheable-request@7.0.2
├─ camelcase-keys@2.1.0
├─ camelcase@6.3.0
├─ caniuse-lite@1.0.30001307
├─ caw@2.0.1
├─ chardet@0.7.0
├─ chownr@1.1.4
├─ ci-info@2.0.0
├─ cli-boxes@2.2.1
├─ cli-spinners@2.6.1
├─ cli-width@3.0.0
├─ clone-response@1.0.2
├─ clone@1.0.4
├─ code-point-at@1.1.0
├─ color-convert@1.9.3
├─ color-name@1.1.4
├─ color-string@1.9.0
├─ color@3.2.1
├─ commander@2.20.3
├─ concat-map@0.0.1
├─ config-chain@1.1.13
├─ configstore@5.0.1
├─ console-control-strings@1.1.0
├─ console-stream@0.1.1
├─ convert-source-map@1.8.0
├─ core-util-is@1.0.3
├─ cross-env@7.0.3
├─ cross-spawn@7.0.3
├─ crypto-random-string@2.0.0
├─ csstype@3.0.10
├─ currently-unhandled@0.4.1
├─ decamelize@1.2.0
├─ decode-uri-component@0.2.0
├─ decompress-tar@4.1.1
├─ decompress-tarbz2@4.1.1
├─ decompress-targz@4.1.1
├─ decompress-unzip@4.0.1
├─ decompress@4.2.1
├─ deep-extend@0.6.0
├─ defaults@1.0.3
├─ defer-to-connect@2.0.1
├─ define-properties@1.1.3
├─ delegates@1.0.0
├─ detect-node@2.1.0
├─ dir-glob@3.0.1
├─ dot-prop@5.3.0
├─ download@6.2.5
├─ electron-to-chromium@1.4.65
├─ emoji-regex@8.0.0
├─ end-of-stream@1.4.4
├─ error-ex@1.3.2
├─ es6-error@4.1.1
├─ esbuild-windows-64@0.13.15
├─ esbuild@0.13.15
├─ escalade@3.1.1
├─ escape-goat@2.1.1
├─ estree-walker@2.0.2
├─ executable@4.1.1
├─ expand-template@2.0.3
├─ ext-list@2.2.2
├─ external-editor@3.1.0
├─ fast-glob@3.2.11
├─ fastq@1.13.0
├─ fd-slicer@1.1.0
├─ figures@3.2.0
├─ filename-reserved-regex@2.0.0
├─ fill-range@7.0.1
├─ find-up@1.1.2
├─ find-versions@3.2.0
├─ from2@2.3.0
├─ fs-extra@10.0.0
├─ fs.realpath@1.0.0
├─ function-bind@1.1.1
├─ gauge@2.7.4
├─ gensync@1.0.0-beta.2
├─ get-proxy@2.1.0
├─ get-stream@3.0.0
├─ github-from-package@0.0.0
├─ glob-parent@5.1.2
├─ glob@7.2.0
├─ global-agent@3.0.0
├─ global-dirs@3.0.0
├─ globals@11.12.0
├─ globalthis@1.0.2
├─ globby@12.2.0
├─ got@11.8.2
├─ has-ansi@2.0.0
├─ has-flag@4.0.0
├─ has-symbol-support-x@1.4.2
├─ has-to-string-tag-x@1.4.1
├─ has-unicode@2.0.1
├─ has-yarn@2.1.0
├─ has@1.0.3
├─ hosted-git-info@2.8.9
├─ http2-wrapper@1.0.3
├─ iconv-lite@0.4.24
├─ ieee754@1.2.1
├─ ignore@5.2.0
├─ imagemin-optipng@8.0.0
├─ imagemin-zopfli@7.0.0
├─ imagemin@8.0.1
├─ import-lazy@2.1.0
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ ini@1.3.8
├─ inquirer@8.1.2
├─ into-stream@3.1.0
├─ is-arrayish@0.3.2
├─ is-ci@2.0.0
├─ is-core-module@2.8.1
├─ is-extglob@2.1.1
├─ is-finite@1.1.0
├─ is-fullwidth-code-point@3.0.0
├─ is-glob@4.0.3
├─ is-installed-globally@0.4.0
├─ is-interactive@1.0.0
├─ is-natural-number@4.0.1
├─ is-npm@5.0.0
├─ is-number@7.0.0
├─ is-obj@2.0.0
├─ is-object@1.0.2
├─ is-path-inside@3.0.3
├─ is-retry-allowed@1.2.0
├─ is-utf8@0.2.1
├─ is-yarn-global@0.3.0
├─ isarray@1.0.0
├─ js-tokens@4.0.0
├─ jsesc@2.5.2
├─ json-stringify-safe@5.0.1
├─ json5@2.2.0
├─ jsonfile@6.1.0
├─ junk@3.1.0
├─ keyv@4.1.0
├─ latest-version@5.1.0
├─ load-json-file@1.1.0
├─ lodash@4.17.21
├─ log-symbols@4.1.0
├─ logalot@2.1.0
├─ longest@1.0.1
├─ loud-rejection@1.6.0
├─ lpad-align@1.1.2
├─ lru-cache@4.1.5
├─ make-dir@1.3.0
├─ map-obj@1.0.1
├─ matcher@3.0.0
├─ meow@3.7.0
├─ merge2@1.4.1
├─ micromatch@4.0.4
├─ mime-db@1.51.0
├─ mimic-fn@2.1.0
├─ minimatch@3.0.4
├─ minimist@1.2.5
├─ mkdirp-classic@0.5.3
├─ ms@2.1.3
├─ mute-stream@0.0.8
├─ nanoid@3.2.0
├─ napi-build-utils@1.0.2
├─ nice-try@1.0.5
├─ node-abi@2.30.1
├─ node-addon-api@3.2.1
├─ node-releases@2.0.1
├─ normalize-package-data@2.5.0
├─ normalize-url@6.1.0
├─ npm-conf@1.1.3
├─ npmlog@4.1.2
├─ number-is-nan@1.0.1
├─ object-keys@1.1.1
├─ onetime@5.1.2
├─ optipng-bin@7.0.1
├─ ora@5.4.1
├─ os-filter-obj@2.0.0
├─ os-tmpdir@1.0.2
├─ p-cancelable@2.1.1
├─ p-event@1.3.0
├─ p-is-promise@1.1.0
├─ p-map-series@1.0.0
├─ p-pipe@4.0.0
├─ p-reduce@1.0.0
├─ p-try@2.2.0
├─ package-json@6.5.0
├─ parse-json@2.2.0
├─ path-exists@2.1.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ path-parse@1.0.7
├─ path-type@4.0.0
├─ peek-readable@4.0.2
├─ pend@1.2.0
├─ picomatch@2.3.1
├─ pinkie@2.0.4
├─ png2icons@2.0.1
├─ postcss@8.4.6
├─ prebuild-install@6.1.4
├─ process-nextick-args@2.0.1
├─ proto-list@1.2.4
├─ pseudomap@1.0.2
├─ pupa@2.1.1
├─ query-string@5.1.1
├─ queue-microtask@1.2.3
├─ quick-lru@5.1.1
├─ react-dom@17.0.2
├─ react-refresh@0.11.0
├─ react@17.0.2
├─ read-chunk@3.2.0
├─ read-pkg-up@1.0.1
├─ read-pkg@1.1.0
├─ readable-stream@2.3.7
├─ readable-web-to-node-stream@3.0.2
├─ redent@1.0.0
├─ registry-auth-token@4.2.1
├─ registry-url@5.1.0
├─ repeating@2.0.1
├─ replace-ext@2.0.0
├─ resolve-alpn@1.2.1
├─ resolve@1.22.0
├─ responselike@1.0.2
├─ restore-cursor@3.1.0
├─ reusify@1.0.4
├─ rimraf@2.7.1
├─ roarr@2.15.4
├─ rollup@2.67.0
├─ run-async@2.4.1
├─ run-parallel@1.2.0
├─ rxjs@7.5.2
├─ safe-buffer@5.2.1
├─ safer-buffer@2.1.2
├─ scheduler@0.20.2
├─ seek-bzip@1.0.6
├─ semver-compare@1.0.0
├─ semver-diff@3.1.1
├─ semver-regex@2.0.0
├─ semver-truncate@1.1.2
├─ semver@5.7.1
├─ serialize-error@7.0.1
├─ set-blocking@2.0.0
├─ sharp@0.28.3
├─ shebang-regex@1.0.0
├─ simple-concat@1.0.1
├─ simple-get@3.1.1
├─ simple-swizzle@0.2.2
├─ slash@3.0.0
├─ sort-keys-length@1.0.1
├─ sort-keys@1.1.2
├─ source-map-js@1.0.2
├─ source-map@0.5.7
├─ spdx-correct@3.1.1
├─ spdx-exceptions@2.3.0
├─ sprintf-js@1.1.2
├─ squeak@1.3.0
├─ strict-uri-encode@1.1.0
├─ string_decoder@1.1.1
├─ string-width@4.2.3
├─ strip-bom@2.0.0
├─ strip-dirs@2.1.0
├─ strip-indent@1.0.1
├─ strip-json-comments@2.0.1
├─ strip-outer@1.0.1
├─ strtok3@6.2.4
├─ supports-color@7.2.0
├─ supports-preserve-symlinks-flag@1.0.0
├─ tar-fs@2.1.1
├─ tar-stream@2.2.0
├─ temp-dir@1.0.0
├─ through@2.3.8
├─ timed-out@4.0.1
├─ tmp@0.0.33
├─ to-buffer@1.1.1
├─ to-fast-properties@2.0.0
├─ to-readable-stream@1.0.0
├─ to-regex-range@5.0.1
├─ token-types@4.1.1
├─ trim-newlines@1.0.0
├─ trim-repeated@1.0.0
├─ tslib@2.3.1
├─ type-fest@0.13.1
├─ typedarray-to-buffer@3.1.5
├─ typescript@4.5.5
├─ unbzip2-stream@1.4.3
├─ unique-string@2.0.0
├─ update-notifier@5.1.0
├─ util-deprecate@1.0.2
├─ uuid@3.4.0
├─ validate-npm-package-license@3.0.4
├─ vite@2.7.13
├─ wcwidth@1.0.1
├─ wide-align@1.1.5
├─ widest-line@3.1.0
├─ with-open-file@0.1.7
├─ wrap-ansi@7.0.0
├─ write-file-atomic@3.0.3
├─ xtend@4.0.2
├─ yallist@2.1.2
├─ yauzl@2.10.0
└─ zopflipng-bin@6.0.1
Done in 131.77s.
- Installing @tauri-apps/api@latest...
yarn add v1.22.17
warning package.json: No license field
warning tauri-app@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⡀ optipng-bin
[2/4] ⡀ zopflipng-bin
[3/4] ⡀ sharp
error D:\tauri-app\node_modules\zopflipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\tauri-app\node_modules\zopflipng-bin
Output:
node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:167:9)
    at Object.<anonymous> (D:\tauri-app\node_modules\npm-conf\lib\defaults.js:31:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {



Error with command: yarn
Error: Error: Command failed with exit code 1: yarn add @tauri-apps/api@latest
    at C:\Users\28154\.config\yarn\global\node_modules\create-tauri-app\dist\index.js:63:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\28154\.config\yarn\global\node_modules\create-tauri-app\dist\index.js:40:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Done in 150.89s.
PS D:\>
```

</details>

**Comment by FabianLars** [comment]
This should (hopefully) fix itself with the next release when we remove `tauricon` from `@tauri-apps/cli` (soon ™️)
