### ISSUE TITLE
Unknown Syntax Error: Unsupported option name ("--ignore-scripts").

### ISSUE THREAD

**Issue by DaZiYuan** [tauri-apps/tauri#3382]
### Describe the bug

yarn create tauri-app  
windows10

### Reproduction

yarn create tauri-app  
windows10

### Platform and versions

```shell
Missing script: "tauri"
```

### Additional context

 yarn create tauri-app
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 14s 982ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 526ms
➤ YN0000: Done in 15s 742ms

? What is your app name? test0
? What should the window title be? test0
? Would you like to add a UI recipe? Vanilla.js
===== running initial command(s) =====
===== installing any additional needed deps =====
Installing @tauri-apps/cli...
Unknown Syntax Error: Unsupported option name ("--ignore-scripts").

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
Error with command: yarn
Error: Error: Command failed with exit code 1: yarn add --dev --ignore-scripts @tauri-apps/cli
    at C:\Users\user\AppData\Local\Yarn\Berry\cache\create-tauri-app-npm-1.0.0-beta-rc.4-90c8c4d827-8.zip\node_modules\create-tauri-app\dist\index.js:59:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\user\AppData\Local\Yarn\Berry\cache\create-tauri-app-npm-1.0.0-beta-rc.4-90c8c4d827-8.zip\node_modules\create-tauri-app\dist\index.js:36:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by amrbashir** [comment]
Looks like yarn2+ removed `--ignore-scripts` option 😕. Thanks for reporting.

Looks like I need to adapt create-tauri-app to yarn1, yarn2+, npm6&7&8 and pnpm6&7

**Comment by GiantappMan** [comment]
yarn1.22.15 still reports an error
```
yarn create tauri-app
yarn create v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-tauri-app@1.0.0-beta.4" with binaries:
      - create-tauri-app
文件名、目录名或卷标语法不正确。
error Command failed.
Exit code: 1
Command: C:\Users\user\AppData\Local\Yarn\bin\create-tauri-app
Arguments: 
Directory: C:\Users\user\Desktop\test
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by amrbashir** [comment]
try `yarn create tauri-app --verbose` and if possible the content of `yarn-error.log` file

**Comment by GiantappMan** [comment]
nothing changed
```
PS C:\Users\user\Desktop\test> node -v
v16.14.0
PS C:\Users\user\Desktop\test> yarn create tauri-app --verbose
yarn create v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-tauri-app@1.0.0-beta.4" with binaries:
      - create-tauri-app
文件名、目录名或卷标语法不正确。
error Command failed.
Exit code: 1
Command: C:\Users\ying\AppData\Local\Yarn\bin\create-tauri-app
Arguments: --verbose
Directory: C:\Users\user\Desktop\test
Output:
```

**Comment by amrbashir** [comment]
is there any `yarn-error.log` files there after you run the command?

**Comment by GiantappMan** [comment]
no yarn-error.log file.

but `npx create-tauri-app` works
