### ISSUE TITLE
[bug]  npx create-tauri-app get error

### ISSUE THREAD

**Issue by GiantappMan** [tauri-apps/tauri#3393]
### Describe the bug

`npx create-tauri-app` with Vanilla.js works,
but other templates all get an error

### Reproduction

```
npx create-tauri-app

We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This tool should get you quickly started. See our docs at https://tauri.studio/

If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/get-started/setup-windows/

Press any key to continue...
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-vite (vanilla, vue, react, svelte, preact, lit) (https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
? Add "@tauri-apps/api" npm package? Yes
? Which vite template would you like to use? vue
>> Running initial command(s)
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-11T02_22_44_672Z-debug-0.log
Error with command: npx
Error: Error: Command failed with exit code 1: npx  create-vite@latest tauri-app --template vue
    at C:\Users\user\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\user\AppData\Local\npm-cache\_npx\b58944764482de26\node_modules\create-tauri-app\dist\index.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

logs
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\nvm\\v17.5.0\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   '',
0 verbose cli   'create-vite@latest',
0 verbose cli   'tauri-app',
0 verbose cli   '--template',
0 verbose cli   'vue'
0 verbose cli ]
1 info using npm@8.4.1
2 info using node@v17.5.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\user\AppData\Roaming\nvm\v17.5.0\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:C:\Users\user\Desktop\test\.npmrc Completed in 1ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:C:\Users\user\.npmrc Completed in 3ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 21ms
19 timing npm:load:configload Completed in 21ms
20 timing npm:load:setTitle Completed in 1ms
21 timing config:load:flatten Completed in 4ms
22 timing npm:load:display Completed in 5ms
23 verbose logfile C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-11T02_22_44_672Z-debug-0.log
24 timing npm:load:logFile Completed in 10ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 38ms
28 silly logfile start cleaning logs, removing 4 files
29 http fetch GET 200 https://registry.npmjs.org/undefined 27ms (cache stale)
30 timing command:exec Completed in 44ms
31 verbose stack Error: could not determine executable to run
31 verbose stack     at getBinFromManifest (C:\Users\user\AppData\Roaming\nvm\v17.5.0\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
31 verbose stack     at exec (C:\Users\user\AppData\Roaming\nvm\v17.5.0\node_modules\npm\node_modules\libnpmexec\lib\index.js:115:15)
31 verbose stack     at async module.exports (C:\Users\user\AppData\Roaming\nvm\v17.5.0\node_modules\npm\lib\cli.js:66:5)
32 verbose pkgid undefined@0.1.0
33 verbose cwd C:\Users\user\Desktop\test
34 verbose Windows_NT 10.0.19043
35 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\nvm\\v17.5.0\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "" "create-vite@latest" "tauri-app" "--template" "vue"
36 verbose node v17.5.0
37 verbose npm  v8.4.1
38 error could not determine executable to run
39 verbose exit 1
40 timing npm Completed in 1587ms
41 verbose code 1
42 error A complete log of this run can be found in:
42 error     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-11T02_22_44_672Z-debug-0.log
```

### Platform and versions

```shell
windows10
node 17.5
```

**Comment by amrbashir** [comment]
Can you try any recipe other than vite? can you try this
`npx create-vite vite-project --template vue` and see if it succeeds?

**Comment by GiantappMan** [comment]
it succeeds
```
npx create-vite vite-project --template vue
Need to install the following packages:
  create-vite
Ok to proceed? (y)

Scaffolding project in C:\Users\user\Desktop\test\vite-project...

Done. Now run:

  cd vite-project
  npm install    
  npm run dev    

```

**Comment by itibbers** [comment]
```bash
$ npx create-tauri-app

npx: installed 99 in 20.618s

We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This tool should get you quickly started. See our docs at https://tauri.studio/

If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/get-started/setup-macos/

Press any key to continue...
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-react-app (https://create-react-app.dev/)
? Add "@tauri-apps/api" npm package? Yes
? Which create-react-app template would you like to use? create-react-app (Typescript)
>> Running initial command(s)

ERROR: You must supply a command.

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Error with command: npx
Error: Error: Command failed with exit code 1: npx  create-react-app@latest --template typescript tauri-app --use-npm
    at /Users/ive/.npm/_npx/70384/lib/node_modules/create-tauri-app/dist/index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/ive/.npm/_npx/70384/lib/node_modules/create-tauri-app/dist/index.js:39:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by Verzach3** [comment]
I have the same problem

```
$ yarn create tauri-app

success Installed "create-tauri-app@1.0.0-rc.0" with binaries:
      - create-tauri-app

Press any key to continue...
? What is your app name? raffle-manager-tauri
? What should the window title be? Raffle Manager
? What UI recipe would you like to add? create-react-app (https://create-react-app.dev/)
? Add "@tauri-apps/api" npm package? Yes
? Which create-react-app template would you like to use? create-react-app (Typescript)
>> Running initial command(s)
yarn install v1.22.17
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add create react-app raffle-manager-tauri" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error with command: yarn
Error: Error: Command failed with exit code 1: yarn  create react-app --template typescript raffle-manager-tauri
    at C:\Users\Verzach3\AppData\Local\Yarn\Data\global\node_modules\create-tauri-app\dist\index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Verzach3\AppData\Local\Yarn\Data\global\node_modules\create-tauri-app\dist\index.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Done in 30.04s.
```

**Comment by WhiteGreeny** [comment]
same problem

```
$ npx create-tauri-app
npx: installed 99 in 10.237s

We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This tool should get you quickly started. See our docs at https://tauri.studio/

If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/get-started/setup-windows/

Press any key to continue...
? What is your app name? t2
? What should the window title be? t2
? What UI recipe would you like to add? Vue CLI (https://cli.vuejs.org/)
? Add "@tauri-apps/api" npm package? Yes
>> Running initial command(s)

ERROR: You must supply a command.

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Error with command: npx
Error: Error: Command failed with exit code 1: npx  @vue/cli@latest create t2 --packageManager npm
    at C:\Users\666\AppData\Roaming\npm-cache\_npx\10212\node_modules\create-tauri-app\dist\index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\666\AppData\Roaming\npm-cache\_npx\10212\node_modules\create-tauri-app\dist\index.js:39:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
but
`npx  @vue/cli@latest create t2 --packageManager npm` is work

**Comment by ishowshao** [comment]
I have the same problem

**Comment by amrbashir** [comment]
A new version has been published, please try again.

**Comment by GiantappMan** [comment]
it works now, thanks
