### ISSUE TITLE
[bug]  problem using tauricon

### ISSUE THREAD

**Issue by yeus** [tauri-apps/tauri#3708]
### Describe the bug

I am trying to use tauricon but failing. Installation seems to work fine...  I did both:

globall:

  yarn global add @tauri-apps/tauricon

and locally:

  yarn add @tauri-apps/tauricon

I can start tauricon in both cases. But getting this error message, and at the same time my mouse turns into this funny cross...
I am really not sure whats going on here?

it doesn't matter what I do with tauricon I am always getting the same error:

- tauricon --help
- tauricon
- tauricon /somepath

![image](https://user-images.githubusercontent.com/736695/158556293-3eece668-2eab-4d46-b2df-13cc6de55b52.png)

after clicking around a bit, the mouse turns back to normal and I get this error message:

```
/home/laptop/.yarn/bin/tauricon: line 1: //: Is a directory
/home/laptop/.yarn/bin/tauricon: line 2: //: Is a directory
/home/laptop/.yarn/bin/tauricon: line 3: //: Is a directory
import-im6.q16: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9187.
import-im6.q16: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9187.
/home/laptop/.yarn/bin/tauricon: line 8: /bin: Is a directory
/home/laptop/.yarn/bin/tauricon: line 9: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 10: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 11: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 12: boolean}: command not found
/home/laptop/.yarn/bin/tauricon: line 12: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 13: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 13: boolean}: command not found
/home/laptop/.yarn/bin/tauricon: line 14: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 15: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 16: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 17: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 18: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 19: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 20: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 21: babel.config.js: command not found
/home/laptop/.yarn/bin/tauricon: line 22: dist/: Is a directory
/home/laptop/.yarn/bin/tauricon: line 23: syntax error near unexpected token `('
/home/laptop/.yarn/bin/tauricon: line 23: `const argv = parseArgs(process.argv.slice(2), {'

```

I am really not sure whats going on here...  does anybody have an idea?

### Reproduction

not sure how to reproduce...  I simply installed tauricon through yarn.

### Platform and versions

```shell
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 17.7.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.2
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - Not installed
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - Not installed

App directory structure
/src-pwa
/node_modules
/public
/.vscode
/dist
/src-ssr
/.quasar
/src-electron
/src
/src-tauri

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist/spa
  devPath - http://localhost:8080/
  framework - Vue.js (Quasar)
  bundler - Webpack
```

**Comment by yeus** [comment]
soo..  a bit more investigaten

I added this line to the top of "tauricon" (my project dir:  ./node_modeuls/.bin/tauricon):

`#!/usr/bin/env node`

and now running tauricon inside my project it works...

when I run the global version outside the project dir I m getting error messages like this:

```
Error: EACCES: permission denied, scandir '/home/laptop/comcharax/neo4j/import'
    at Object.readdirSync (node:fs:1405:3)
    at GlobSync._readdir (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:285:46)
    at GlobSync._readdirInGlobStar (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:264:20)
    at GlobSync._readdir (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:273:17)
    at GlobSync._processGlobStar (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:347:22)
    at GlobSync._process (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:127:10)
    at GlobSync._processGlobStar (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:380:10)
    at GlobSync._process (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:127:10)
    at GlobSync._processGlobStar (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:380:10)
    at GlobSync._process (/home/laptop/.config/yarn/global/node_modules/@tauri-apps/tauricon/node_modules/glob/sync.js:127:10) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/home/laptop/comcharax/neo4j/import'
}

```

I guess it scans my entire hoe directory? not sure if thats a good way to do this...   

- there should probabl be a better error message, that we should only run tauricon inside the project dir
- don't scan every directory there is, but have a better way of detecting whether we are in a project dir.

**Comment by FabianLars** [comment]
> I guess it scans my entire hoe directory? not sure if thats a good way to do this...

I didn't test it enough when i rewrote the docs and i forgot that it searches for a tauri project to save the icon to.
The first thing that comes to mind is to detect whether the command runs globally and output the icons in `./icons` instead. I'm open for suggestions.
