### ISSUE TITLE
[bug] GlobalShortcutManager registration fails with 'Unknown error' on Ubuntu 20.04

### ISSUE THREAD

**Issue by rscarson** [tauri-apps/tauri#3783]
### Describe the bug

Shortcut key registrations fail on Ubuntu 20.04, with the error only containing 'GlobalShortcut(InvalidAccelerator("Unknown error"))'

This error occurs for any accelerators registered

### Reproduction

```rs
let mut gsm = app_handle.global_shortcut_manager();
gsm.register("CmdOrCtrl+Space", || {}).unwrap();
```

### Expected behavior

Expectation is behaviour of the same codebase on Windows hosts, where the shortcut is registered successfully

### Platform and versions

```shell
cargo tauri info

Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 17.8.0
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 8.5.5
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/node_modules
/src-tauri
/src
/.git
/public
/.vscode

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

### Stack trace
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: GlobalShortcut(InvalidAccelerator("Unknown error"))', src/keybind.rs:41:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
   4: lavendeux::keybind::bind_shortcut
             at ./src/keybind.rs:41:2
   5: lavendeux::settings::update_settings
             at ./src/settings.rs:124:21
   6: lavendeux::main::{{closure}}::{{closure}}
             at ./src/main.rs:117:11
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1868:9
   8: tauri::event::Listeners::trigger
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/event.rs:212:15
   9: tauri::manager::WindowManager<R>::trigger
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/manager.rs:1211:5
  10: tauri::window::Window<R>::trigger
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/window.rs:709:5
  11: tauri::endpoints::event::Cmd::emit
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/endpoints/event.rs:130:5
  12: tauri::endpoints::event::Cmd::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/endpoints/event.rs:56:10
  13: tauri::endpoints::Module::run::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/endpoints.rs:140:9
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  15: tauri::hooks::InvokeResolver<R>::return_task::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/hooks.rs:239:22
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  17: tauri::hooks::InvokeResolver<R>::respond_async::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-rc.4/src/hooks.rs:186:70
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  19: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  21: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  22: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  24: std::panicking::try::do_call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  25: __rust_try
  26: std::panicking::try
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27: std::panic::catch_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28: tokio::runtime::task::harness::poll_future
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  29: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  30: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  31: tokio::runtime::task::raw::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  32: tokio::runtime::task::raw::RawTask::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  33: tokio::runtime::task::LocalNotified<S>::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
  34: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:425:13
  35: tokio::coop::with_budget::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  36: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  37: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  38: tokio::coop::with_budget
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  39: tokio::coop::budget
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  40: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
  41: tokio::runtime::thread_pool::worker::Context::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:391:24
  42: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
  43: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  44: tokio::runtime::thread_pool::worker::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
  45: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
  46: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
  47: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  48: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  49: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  50: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  51: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  52: std::panicking::try::do_call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  53: __rust_try
  54: std::panicking::try
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  55: std::panic::catch_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  56: tokio::runtime::task::harness::poll_future
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  59: tokio::runtime::task::raw::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  60: tokio::runtime::task::raw::RawTask::poll
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  61: tokio::runtime::task::UnownedTask<S>::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
  62: tokio::runtime::blocking::pool::Task::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
  63: tokio::runtime::blocking::pool::Inner::run
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
  64: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/rcarson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

Same result observed under an installation through virtualbox, a separate installation through VMware, as well as an attempt through wsl2 on Windows 10

**Comment by rscarson** [comment]
Upon further investigation, the error was due
