### ISSUE TITLE
[bug] thread 'main' panicked at 'error found during tauri-build: unknown field `allowDowngrades`

### ISSUE THREAD

**Issue by glud123** [tauri-apps/tauri#3822]
### Describe the bug

It will appear when I run dev or run build

### Reproduction

1. `npm run tauri dev` or `npm run tauri build`
2. an error will be reported during the compilation phase

### Expected behavior

start app normally

### Platform and versions

```shell
> schematool@0.0.0 tauri
> tauri "info"


Environment
  › OS: Mac OS 12.3.0 X64
  › Node.js: 14.18.0
  › npm: 8.3.0
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.61.0-nightly
  › cargo: 1.61.0-nightly
  › Rust toolchain: nightly-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.4,
  › tauri-build [RUST]: 1.0.0-rc.4,
  › tao [RUST]: 0.6.4,
  › wry [RUST]: 0.13.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  └─ src
```

### Stack trace

```shell
gaokung@kundeMBP  ~/code/schemaTool   main  RUST_BACKTRACE=full npm run tauri dev

> schematool@0.0.0 tauri
> tauri "dev"

[tauri:dev] Running `npm run dev`
[tauri:dev] Waiting for your frontend dev server to start on http://localhost:3000/...

> schematool@0.0.0 dev
> vite


  vite v2.8.6 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 384ms.

   Compiling app v0.1.0 (/Users/gaokung/code/schemaTool/src-tauri)
error: failed to run custom build command for `app v0.1.0 (/Users/gaokung/code/schemaTool/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/gaokung/code/schemaTool/src-tauri/target/debug/build/app-c16d57820a6c855b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: unknown field `allowDowngrades`, expected one of `digestAlgorithm`, `certificateThumbprint`, `timestampUrl`, `tsp`, `webviewFixedRuntimePath`, `wix` at line 1 column 988', /Users/gaokung/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tauri-build-1.0.0-rc.4/src/lib.rs:146:5
  stack backtrace:
     0:        0x10d745164 - std::backtrace_rs::backtrace::libunwind::trace::h096f35e5462493d7
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x10d745164 - std::backtrace_rs::backtrace::trace_unsynchronized::h5afa9dfdd5cf9540
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x10d745164 - std::sys_common::backtrace::_print_fmt::h1194ab6dbae55aaf
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/sys_common/backtrace.rs:66:5
     3:        0x10d745164 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb99c5a718a6b728d
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/sys_common/backtrace.rs:45:22
     4:        0x10d75ef7b - core::fmt::write::h24aa8d5cda717419
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/core/src/fmt/mod.rs:1190:17
     5:        0x10d7427d8 - std::io::Write::write_fmt::hf2de1f6a23545435
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/io/mod.rs:1655:15
     6:        0x10d74693d - std::sys_common::backtrace::_print::h056f3eb6ac177f80
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/sys_common/backtrace.rs:48:5
     7:        0x10d74693d - std::sys_common::backtrace::print::ha38178b2246155b4
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/sys_common/backtrace.rs:35:9
     8:        0x10d74693d - std::panicking::default_hook::{{closure}}::hdd6feb3e3ce42782
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:295:22
     9:        0x10d746621 - std::panicking::default_hook::h0e1d108e05af35ca
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:314:9
    10:        0x10d746ebe - std::panicking::rust_panic_with_hook::hd5e1ec82b8190db9
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:698:17
    11:        0x10d746db3 - std::panicking::begin_panic_handler::{{closure}}::hdc6bebe22f5b314d
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:588:13
    12:        0x10d7455e7 - std::sys_common::backtrace::__rust_end_short_backtrace::h7a4973d6f8784324
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/sys_common/backtrace.rs:138:18
    13:        0x10d746a8a - rust_begin_unwind
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:584:5
    14:        0x10d76e653 - core::panicking::panic_fmt::hceee391d46af7460
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/core/src/panicking.rs:143:14
    15:        0x10d504b5a - tauri_build::build::h510624745a30c736
                                 at /Users/gaokung/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tauri-build-1.0.0-rc.4/src/lib.rs:146:5
    16:        0x10d2df079 - build_script_build::main::ha74b2edfd52ed8f8
                                 at /Users/gaokung/code/schemaTool/src-tauri/build.rs:2:3
    17:        0x10d2df02e - core::ops::function::FnOnce::call_once::h1105ef9b8e898027
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/core/src/ops/function.rs:227:5
    18:        0x10d2df121 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf4055f4e715e021b
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/sys_common/backtrace.rs:122:18
    19:        0x10d2df1a4 - std::rt::lang_start::{{closure}}::h09dcd233686ee601
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/rt.rs:145:18
    20:        0x10d73d47a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7a39425aa6efb8dd
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/core/src/ops/function.rs:259:13
    21:        0x10d73d47a - std::panicking::try::do_call::hbef5f52fe2725b85
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:492:40
    22:        0x10d73d47a - std::panicking::try::h07bc201e7748d743
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:456:19
    23:        0x10d73d47a - std::panic::catch_unwind::h41fd81df6436f03e
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panic.rs:137:14
    24:        0x10d73d47a - std::rt::lang_start_internal::{{closure}}::h7fad6c5ef02eb76b
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/rt.rs:128:48
    25:        0x10d73d47a - std::panicking::try::do_call::h96831f7c75b61e60
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:492:40
    26:        0x10d73d47a - std::panicking::try::h0fb23922f257b542
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:456:19
    27:        0x10d73d47a - std::panic::catch_unwind::h373dd65488bf8724
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panic.rs:137:14
    28:        0x10d73d47a - std::rt::lang_start_internal::had77d2859be511d4
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/rt.rs:128:20
    29:        0x10d2df17e - std::rt::lang_start::h7e9ced50586dd365
                                 at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/rt.rs:144:17
    30:        0x10d2df096 - _main
```

**Comment by amrbashir** [comment]
Please update your `@tauri-apps/cli` version to `1.0.0-rc.8`

**Comment by JonasKruckenberg** [comment]
Maybe we should remove `deny_unknown_fields` 🤔 Or at least stop panicking and give a proper error

**Comment by glud123** [comment]
> Please update your `@tauri-apps/cli` version to `1.0.0-rc.8`

Thanks! 
My local `@tauri-apps/cli` version is already  `1.0.0-rc.8`, But it still gives the same error.
```shell
✘ gaokung@kundeMBP  ~/code/schemaTool   main ±  npm ls @tauri-apps/cli
schematool@0.0.0 /Users/gaokung/code/schemaTool
└── @tauri-apps/cli@1.0.0-rc.8
```
And I found that the version of the information `@tauri-apps/cli` produced by `npm run tauri info` is not accurate.
Now I execute `npm run tauri info` and it still shows that the version of `@tauri-apps/cli` is `1.0.0-rc.7`.

```shell
 gaokung@kundeMBP  ~/code/schemaTool   main ±  npm run tauri info

> schematool@0.0.0 tauri
> tauri "info"


Environment
  › OS: Mac OS 12.3.0 X64
  › Node.js: 14.18.0
  › npm: 8.3.0
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.4,
  › tauri-build [RUST]: 1.0.0-rc.4,
  › tao [RUST]: 0.6.4,
  › wry [RUST]: 0.13.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  └─ src
```

**Comment by onetonfoot** [comment]
I'm also still experiencing this issue, having installed the latest version of `tauri-cli` (1.0.0-rc.8) from cargo.

**Comment by onetonfoot** [comment]
Turns out the issue was because I had the wrong version of  tauri-build (1.0.0-rc.4) after updating to `1.0.0-rc.5 all is good

**Comment by zsmatrix62** [comment]
actually 1.0.0-rc.6 works but not rc.8

**Comment by BrunoBernardino** [comment]
I'm also running into this problem with `rc.10`:

```
$ npm run tauri info

> @padloc/tauri@4.0.0 tauri
> tauri "info"


Environment
  › OS: Linux 16 X64
  › Node.js: 16.13.1
  › npm: 8.2.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.57.0
  › cargo: 1.57.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.4,
  › tauri-build [RUST]: 1.0.0-beta.4,
  › tao [RUST]: 0.6.4,
  › wry [RUST]: 0.13.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:8080/
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ src-tauri
  ├─ node_modules
  └─ src
```

**Comment by FabianLars** [comment]
@BrunoBernardino both your `tauri` and `tauri-build` versions are outdated, the latter is the one causing the error here (but you still need to update both).
Here's a guide for updating the rust dependencies: https://tauri.studio/v1/guides/development/updating-dependencies#update-cargo-packages

**Comment by BrunoBernardino** [comment]
Thanks @FabianLars that worked! (running `cd src-tauri && cargo update`)
