### ISSUE TITLE
[bug] @tauri-apps/api imports trigger error in unit tests

### ISSUE THREAD

**Issue by dArignac** [tauri-apps/tauri#3962]
### Describe the bug

I'm using tauri with React (Typescript). I integrated the @tauri-apps/api (version 1.0.0-rc.3) package into the React application, within a class:

```
import { createDir, Dir } from "@tauri-apps/api/fs"
import { dataDir } from "@tauri-apps/api/path"
...
export class StrongholdStorage implements Storage {
...
```

When running the application everything works, no issues.

When I import and instantiate the class within a jest test, I get 

```
    SyntaxError: Cannot use import statement outside a module
    > 1 | import { createDir, Dir } from "@tauri-apps/api/fs"
```

### Reproduction

1. Create a tauri app with React/Typescript and select to install the @tauri-app/api package 
2. create file that imports the @tauri-apps/api and uses it
3. create test instantiating this class
4. run test

I created a repository that reproduces the issue, you just need to install packages and run the tests: https://github.com/dArignac/tauri-apps-api-reproduction-case

### Expected behavior

Tests do not fail

### Platform and versions

```shell
Environment
  › OS: Ubuntu 21.10 X64
  › Node.js: 16.14.2
  › npm: 8.7.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.58.1
  › cargo: 1.58.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src 'self' style-src: 'unsafe-inline'
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ .husky
  ├─ .github
  ├─ public
  ├─ src
  ├─ .git
  ├─ src-tauri
  ├─ build
  ├─ dependencies
  ├─ scripts
  ├─ .vscode
  └─ tauri-plugin-stronghold
```

### Stack trace

```shell
FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/alex/projects/github/tauri-app/node_modules/@tauri-apps/api/fs.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import"./tslib.es6-6e0f8414.js";import"./tauri-c3f7456b.js";export{B as BaseDirectory,B as Dir,g as copyFile,d as createDir,a as readBinaryFile,c as readDir,r as readTextFile,e as removeDir,h as removeFile,i as renameFile,b as writeBinaryFile,w as writeFile}from"./fs-9194ac62.js";import"./tauri-94e4ec1e.js";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { createDir, Dir } from "@tauri-apps/api/fs";
        | ^
      2 | import { dataDir } from "@tauri-apps/api/path";
      3 |
      4 | export class Storage {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/storage.ts:1:1)
```

**Comment by amrbashir** [comment]
AFAIK that's an issue with jest not playing nice with ESM modules

**Comment by FabianLars** [comment]
Yep, like amr said, it's not a tauri problem, you'd have the same "problem" with every other module/package. Furthermore using tauri apis in tests is tricky because you don't have access to the IPC (which is only available in tauri _windows_), therefore you'd need to _mock_ the IPC, see this guide: https://tauri.studio/docs/testing/mocking

**Comment by nothingismagick** [comment]
There are ways to get this to work (but it is not Tauri's fault as stated above):
https://stackoverflow.com/questions/59879689/jest-syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by dArignac** [comment]
Thanks for the fast replies and the hints! Sorry for bothering with something that is not originated in tauri.

Managed to get it running with the following, if anyone is curious or has the same issue:
```
# package.json
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@tauri-apps/api)/)"
    ]
  },
```
