### ISSUE TITLE
[bug] get "unknown field `useBootstrapper`, expected `depends` or `files`" after update `tauri` to `1.0.0-rc.8`

### ISSUE THREAD

**Issue by lastnigtic** [tauri-apps/tauri#3982]
### Describe the bug

this is my `tauri.conf.json`
```
{
  "package": {
    "productName": "apng-editor-app",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:3000",
    "beforeDevCommand": "yarn dev:app",
    "beforeBuildCommand": "yarn build:app"
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": []
      },
      "macOS": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "exceptionDomain": "",
        "signingIdentity": null,
        "providerShortName": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "allowlist": {
      "all": true,
      "fs": {
        "all": true,
        "scope": ["/*"]
      }
    },
    "windows": [
      {
        "title": "Apng Editor",
        "width": 1358,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": null
    }
  }
}
```

---
my `Cargo.toml`
```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.8", features = ["api-all"] }
[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: 6.14.5
  › yarn: 1.22.18
  › rustup: Not installed!
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7
  › @tauri-apps/api [NPM]: 1.0.0-rc.3
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ scripts
  ├─ src-tauri
  ├─ .git
  └─ src
```

### Stack trace

```shell
Caused by:
  process didn't exit successfully: `~/Desktop/Working/Github/apng-editor/src-tauri/target/debug/build/app-f486aeb21c99da67/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: Error("unknown field `useBootstrapper`, expected `depends` or `files`", line: 1, column: 618)', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.7/src/lib.rs:146:5
  stack backtrace:
     0:        0x10b52da31 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0d1bc6b9a6cb5b34
     1:        0x10b54cfbb - core::fmt::write::h64ddbe43c958ac83
     2:        0x10b5205b6 - std::io::Write::write_fmt::h7e453fd0bb915ce8
     3:        0x10b529d77 - std::panicking::default_hook::{{closure}}::hc0a95f88628ea979
     4:        0x10b5299bc - std::panicking::default_hook::hf67658777aa79be9
     5:        0x10b52a31c - std::panicking::rust_panic_with_hook::h59a745e8579c1996
     6:        0x10b52e2fe - std::panicking::begin_panic_handler::{{closure}}::h77c7cdc59f5a8e41
     7:        0x10b52db57 - std::sys_common::backtrace::__rust_end_short_backtrace::hc399a88e87a79fbd
     8:        0x10b529e13 - _rust_begin_unwind
     9:        0x10b55f39f - core::panicking::panic_fmt::h0686ac972197ca01
    10:        0x10b2fe13e - tauri_build::build::h7c54a20f6bd4f84b
                                 at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.7/src/lib.rs:146:5
    11:        0x10b0c63a9 - build_script_build::main::h3d10f5092dac55a5
                                 at ~/Desktop/Working/Github/apng-editor/src-tauri/build.rs:2:3
    12:        0x10b0c644e - core::ops::function::FnOnce::call_once::h59f51c141e717fa1
                                 at /private/tmp/rust-20220304-60118-2krfor/rustc-1.59.0-src/library/core/src/ops/function.rs:227:5
    13:        0x10b0c6531 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2e857219b2cc4c9d
                                 at /private/tmp/rust-20220304-60118-2krfor/rustc-1.59.0-src/library/std/src/sys_common/backtrace.rs:123:18
    14:        0x10b0c6504 - std::rt::lang_start::{{closure}}::h6f68e1530e74d084
                                 at /private/tmp/rust-20220304-60118-2krfor/rustc-1.59.0-src/library/std/src/rt.rs:145:18
    15:        0x10b51bb65 - std::rt::lang_start_internal::ha766b113f2bd4ad1
    16:        0x10b0c64de - std::rt::lang_start::hc87078130c02315a
                                 at /private/tmp/rust-20220304-60118-2krfor/rustc-1.59.0-src/library/std/src/rt.rs:144:17
    17:        0x10b0c63c6 - <unknown>
                                 at ~/Desktop/Working/Github/apng-editor/src-tauri/build.rs:3:2
```

**Comment by enedrio** [comment]
I'm seeing the same error after updating my plugin to tauri 1.0.0-rc.8

**Comment by FabianLars** [comment]
At least while we're in the context of prerelease versions you always need to update **all** packages not just tauri.
So we're talking about tauri, tauri-build, tauri-cli, `@tauri-apps/api` and `@tauri-apps/cli`. In this case it's the cli version causing the error.

P.S. just to be clear, you don't need all of the mentioned packages, but if you have them you need to upgrade them.

**Comment by OceanBelongsToMe** [comment]
@lastnigtic hello，Take the liberty to ask, has this bug been resolved? I had the same problem！

**Comment by FabianLars** [comment]
@OceanBelongsToMe there really is no "bug" to resolve here. You just need to upgrade your dependencies like described above and remove the `useBootstraper` properties in tauri.conf.json if you had them in there...

**Comment by kxxoling** [comment]
> You just need to upgrade your dependencies like described above and remove the useBootstraper properties in tauri.conf.json if you had them in there..

Same issue here from a new project created with `cargo create-tauri-app`, and there's no `useBootstraper` in the project. My cargo version is `cargo 1.64.0 (387270bc7 2022-09-16)`, and rust version created in `Cargo.toml` is `rust-version = "1.57"`.

**Comment by StiliyanHoody** [comment]
@FabianLars good thing OP had `useBootstraper` in tauri.conf.json
Oh wait.. he didn't...

**Comment by FabianLars** [comment]
That's why I didn't instruct them to remove it in my first message... In the second message i mentioned it because it _can_ be part of the error message and other people than OP stumbled upon this issue.

Also please remember that we're all just humans so this kind of attitude is honestly just inappropriate :/
