### ISSUE TITLE
[bug] Unable to call 'invoke' when using with SvelteKit

### ISSUE THREAD

**Issue by Mattchine** [tauri-apps/tauri#4018]
### Describe the bug

When importing `invoke` into sveltekit, running `yarn tauri dev`  resulted in error.

### Reproduction
1. Adding `SSR: false` in `hook.ts` (Example repo below)
2. Import `invoke`
```svelte
<script>
  // index.svelte
  import { invoke } from "@tauri-apps/api";
</script>
```
3. Run `yarn tauri dev`
```bash
$ yarn tauri dev
# -- skip --
ReferenceError: navigator is not defined
    at Object.exports.isWindows (<path>/node_modules/@tauri-apps/api/os-check-92914785.cjs:1:43)
    at Object.<anonymous> (<path>/node_modules/@tauri-apps/api/path-2801ccc1.cjs:1:4577)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<path>/node_modules/@tauri-apps/api/index.cjs:1:173)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
```

### Expected behavior

Importing / Running works fine with sveltekit

### Platform and versions

```shell
Environment
  › OS: OracleLinux 35.0.0 X64
  › Node.js: 17.9.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7
  › @tauri-apps/api [NPM]: 1.0.0-rc.3
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ src
  ├─ static
  ├─ node_modules
  └─ .svelte-kit
```

### Stack trace

```shell
After researching, I found that:
- This error usually occur when we trying to access `window` object inside `server`, in other words, during `SSR`. Which is not make sense since I already disable it in `hook.ts`.

- I tried using `withGlobalTauri`, still no luck.
- I tried setting `SSR: false` (just trying...), still no luck.
- I tried adding `context="module"` during import, still no luck.

- I'm thinking about namespace error but I have no idea, so I guess I better open an issue here.
```

### Additional context

Example repos: [invoke_error branch](https://github.com/Mattchine/skitty/tree/invoke_error)

**Comment by vdvman1** [comment]
This is probably caused by server side rendering, you need to check to make sure it is running in the browser before calling any Tauri APIs

**Comment by Mattchine** [comment]
> This is probably caused by server side rendering, you need to check to make sure it is running in the browser before calling any Tauri APIs

Yes, I think so. But I'm unable to fix it (explanation above). Since this is just importing not calling the function. Could you please provide me an example?

**Comment by Mattchine** [comment]
I found the issue. This is so embarrassing and releasing at the same time.

I have `hook.ts`, while my `svelte.config.js` is pointed to `src/hooks.ts`.
Renaming file solve the issue.
