### ISSUE TITLE
[bug] npx create-tauri-app fails to install with create-react-app

### ISSUE THREAD

**Issue by neofight78** [tauri-apps/tauri#4245]
### Describe the bug

```
npx create-tauri-app

We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This tool should get you quickly started. See our docs at https://tauri.studio/

If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/docs/getting-started/setting-up-macos/

Press any key to continue...
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-react-app (https://create-react-app.dev/)
? Add "@tauri-apps/api" npm package? Yes
? Which create-react-app template would you like to use? create-react-app (Typescript)
>> Running initial command(s)
Need to install the following packages:
  create-react-app
Ok to proceed? (y) y

You are running `create-react-app` 4.0.3, which is behind the latest release (5.0.1).

We no longer support global installation of Create React App.

Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app

The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/

npm ERR! code 1
npm ERR! path /Users/whoggarth/Documents/Projects
npm ERR! command failed
npm ERR! command sh -c create-react-app "tauri-app" "--template" "typescript" "--use-npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/whoggarth/.npm/_logs/2022-05-30T19_30_43_374Z-debug-0.log
Error with command: npm
Error: Error: Command failed with exit code 1: npm init react-app -- tauri-app --template typescript --use-npm
    at /Users/whoggarth/.npm/_npx/b58944764482de26/node_modules/create-tauri-app/dist/index.js:147:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/whoggarth/.npm/_npx/b58944764482de26/node_modules/create-tauri-app/dist/index.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Platform and versions

```shell
N/A - Installation failure
```

**Comment by FabianLars** [comment]
This is not really a tauri/CTA issue. You still have a really old version of CRA installed _globally_. Like the error tells you, you need to uninstall that.

to be clear this error comes from create-react-app, not tauri.
