### ISSUE TITLE
[bug] Cannot start app

### ISSUE THREAD

**Issue by jolic** [tauri-apps/tauri#4339]
### Describe the bug

```npm run tauri dev``` quits with an error

### Platform and versions

```shell
> tauri "info"


Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 14.17.1
  › npm: 8.7.0
  › pnpm: Not installed!
  › yarn: 1.22.0
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.14
  › @tauri-apps/api [NPM]: 1.0.0-rc.7
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › framework: React

App directory structure
  ├─ node_modules
  ├─ retinsight_log
  ├─ public
  ├─ src-tauri
  ├─ build
  ├─ .git
  ├─ e2e
  ├─ coverage
  └─ src
```

### Stack trace

```shell
/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: Error("unknown field `appimage`, expected one of `active`, `targets`, `identifier`, `icon`, `resources`, `copyright`, `category`, `shortDescription`, `longDescription`, `deb`, `macOS`, `externalBin`, `windows`", line: 1, column: 1594)', /Users/m.jolic/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.12/src/lib.rs:165:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
     2: tauri_build::build
               at /Users/m.jolic/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.12/src/lib.rs:165:5
     3: build_script_build::main
               at ./src/build.rs:2:3
     4: core::ops::function::FnOnce::call_once
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[dev] npm run dev exited with code 1
```

**Comment by lucasfernog** [comment]
You need to update the Rust crates (tauri to rc.15, tauri-build to rc.13).

**Comment by jolic** [comment]
Thx @lucasfernog! This worked!

```
cd src-tauri
cargo update
```
