### ISSUE TITLE
[bug] app panics on Windows 11 `The filename, directory name, or volume label syntax is incorrect`

### ISSUE THREAD

**Issue by maacl** [tauri-apps/tauri#4371]
### Describe the bug

Build of app on Windows 11 succeeds but app exits immediately.

I have successfully built and run this app: https://github.com/wildwestrom/tauri-shadow-cljs on WSL for Windows 11.

### Reproduction

On Windows 11:

1 Clone https://github.com/wildwestrom/tauri-shadow-cljs
2 cd src-tauri
3 cargo tauri build
4 cd target\release
5 .\cljs-tauri.exe
5. Executable exits immediately.

### Expected behavior

App main window would display.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 102.0.1245.41
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 14.12.0
  › npm: 6.14.8
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
```

**Comment by FabianLars** [comment]
Can you try other (newer) apps? The one your shared uses beta.8 which was released 10 months ago and a lot has changed since then (and we explicitly don't support beta version and with the stable version released we'll stop supporting RCs too).

Also try `tauri dev` or for a more similar result to what you tried: `tauri build --debug` (output in target/build/) which both have a terminal session attached so you can see errors.

That said i'm going to close this for now until you reported the same issues with the stable tauri release too...

**Comment by maacl** [comment]
I have updated Cargo.toml to the below and the result remains the same:
```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

```

**Comment by maacl** [comment]
Building with `cargo tauri build --debug` and running `src-tauri\target\debug\cljs-tauri.exe` outputs:

`thread 'main' panicked at 'error while running tauri application: Io(Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." })', src\main.rs:9:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by maacl** [comment]
For easy reference this is the contents of main.rs:

````
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

fn main() {
  tauri::Builder::default()
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
````

**Comment by maacl** [comment]
Please let me know if there is additional output I can provide.

**Comment by FabianLars** [comment]
Hmm can't remember ever seeing that error :thinking: 

Is the file path in any way special? Like uncommon user names or folders?

**Comment by maacl** [comment]
I don't think so. The path to the project is:

`C:\Users\marti\tmp\tauri-shadow-cljs\`

As mentioned the same project builds and runs without issue on WSL2 for Windows 11.

**Comment by amrbashir** [comment]
@maacl try setting the rust back trace env var first before running the app and see if you can get any useful backtrace
```
$env:RUST_BACKTRACE=1
```

If not, please package the project in a zip (without `node_modules` or `target` dirs) and upload it here.

**Comment by maacl** [comment]
Here is the result of running with `$env:RUST_BACKTRACE='full'`:

```
PS C:\Users\marti\tmp\tauri-shadow-cljs\src-tauri\target\debug> .\cljs-tauri.exe
thread 'main' panicked at 'error while running tauri application: Io(Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." })', src\main.rs:9:6
stack backtrace:
   0:     0x7ff7fd73a6bf - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7fd73a6bf - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7fd73a6bf - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff7fd73a6bf - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff7fd758ffa - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff7fd733299 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff7fd73d0bb - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff7fd73d0bb - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff7fd73d0bb - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff7fd73ccae - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff7fd73d6b1 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff7fd73d56d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  12:     0x7ff7fd73afc7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff7fd73d249 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff7fd768855 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  15:     0x7ff7fd768963 - core::result::unwrap_failed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\result.rs:1785
  16:     0x7ff7fcfbff51 - enum$<core::result::Result<tuple$<>,enum$<tauri::error::Error> >, 0, 25, Err>::expect<tuple$<>,enum$<tauri::error::Error> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\result.rs:1035
  17:     0x7ff7fd008d6c - app::main
                               at C:\Users\marti\tmp\tauri-shadow-cljs\src-tauri\src\main.rs:7
  18:     0x7ff7fcf4c72b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:227
  19:     0x7ff7fd00f29b - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\sys_common\backtrace.rs:122
  20:     0x7ff7fce18191 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\rt.rs:145
  21:     0x7ff7fd72cd8e - core::ops::function::impls::impl$2::call_once
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:259
  22:     0x7ff7fd72cd8e - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  23:     0x7ff7fd72cd8e - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  24:     0x7ff7fd72cd8e - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  25:     0x7ff7fd72cd8e - std::rt::lang_start_internal::closure$2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  26:     0x7ff7fd72cd8e - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  27:     0x7ff7fd72cd8e - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  28:     0x7ff7fd72cd8e - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  29:     0x7ff7fd72cd8e - std::rt::lang_start_internal
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  30:     0x7ff7fce1815f - std::rt::lang_start<tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\rt.rs:144
  31:     0x7ff7fd009af6 - main
  32:     0x7ff7fd761024 - invoke_main
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33:     0x7ff7fd761024 - __scrt_common_main_seh
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34:     0x7ffab1a854e0 - BaseThreadInitThunk
  35:     0x7ffab26c485b - RtlUserThreadStart
```

**Comment by amrbashir** [comment]
Nothing useful in the stack, so I cloned the repo you linked and after fixing it and updating it to the latest tauri, it worked fine. can you try to do `cargo update` inside `src-tauri`?

**Comment by maacl** [comment]
After running `cargo update` result is the same. Maybe I have missed something that needs updating. Could you post a diff of the changes you made to the repo?

**Comment by maacl** [comment]
Maybe something in outpu from `cargo tauri info` that could be useful:

```
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 102.0.1245.41
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 14.12.0
  › npm: 6.14.8
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .shadow-cljs
  ├─ dist
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment]
here is a diff without `Cargo.lock`
```diff
diff --git a/package.json b/package.json
index 3f1fd98..351aede 100644
--- a/package.json
+++ b/package.json
@@ -4,11 +4,11 @@
     "tauri": "tauri"
   },
   "devDependencies": {
-    "@tauri-apps/cli": "^1.0.0-beta.10",
-    "shadow-cljs": "^2.15.12"
+    "@tauri-apps/cli": "^1.0.0",
+    "shadow-cljs": "^2.19.3"
   },
   "dependencies": {
-    "@tauri-apps/api": "^1.0.0-beta.8",
+    "@tauri-apps/api": "^1.0.1",
     "react": "^17.0.2",
     "react-dom": "^17.0.2"
   }
diff --git a/src-tauri/Cargo.toml b/src-tauri/Cargo.toml
index e460700..26795ca 100644
--- a/src-tauri/Cargo.toml
+++ b/src-tauri/Cargo.toml
@@ -12,12 +12,12 @@ build = "src/build.rs"
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [build-dependencies]
-tauri-build = { version = "1.0.0-beta.4" }
+tauri-build = "1.0.0"
 
 [dependencies]
-serde_json = "1.0"
-serde = { version = "1.0", features = ["derive"] }
-tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
+serde_json = "1.0.81"
+serde = { version = "1.0.137", features = ["derive"] }
+tauri = { version = "1.0.0", features = ["api-all"] }
 
 [features]
 default = [ "custom-protocol" ]
diff --git a/src-tauri/tauri.conf.json b/src-tauri/tauri.conf.json
index 10155ec..d9fdbd8 100644
--- a/src-tauri/tauri.conf.json
+++ b/src-tauri/tauri.conf.json
@@ -13,7 +13,7 @@
     "bundle": {
       "active": true,
       "targets": "all",
-      "identifier": "com.tauri.dev",
+      "identifier": "com.tauri.cljs",
       "icon": [
         "icons/32x32.png",
         "icons/128x128.png",
@@ -28,13 +28,11 @@
       "shortDescription": "",
       "longDescription": "",
       "deb": {
-        "depends": [],
-        "useBootstrapper": false
+        "depends": []
       },
       "macOS": {
         "frameworks": [],
         "minimumSystemVersion": "",
-        "useBootstrapper": false,
         "exceptionDomain": "",
         "signingIdentity": null,
         "entitlements": null

```

But you're probably better starting off with a new project.

**Comment by maacl** [comment]
I believe I have made all the required changes, but I am still getting the same result. I have zipped the project and attach it here
[tauri-shadow-cljs.zip](https://github.com/tauri-apps/tauri/files/8927584/tauri-shadow-cljs.zip)
.

**Comment by lucasfernog** [comment]
Looks like something in your system tbh, it's hard to trace this.

**Comment by maacl** [comment]
Sorry about that. Is there any version of dependency info that I can provide.

**Comment by maacl** [comment]
So I initted a new project and moved the cljs / js parts into it, and now it works. No idea why. Sorry for the inconvenience.

**Comment by lucasfernog** [comment]
Wow that's weird :D

**Comment by maacl** [comment]
Very.

**Comment by maacl** [comment]
Thanks @FabianLars @lucasfernog @amrbashir
