### ISSUE TITLE
[bug] Cannot launch Quick Start Demo

### ISSUE THREAD

**Issue by JSoon** [tauri-apps/tauri#4439]
### Describe the bug

After following the [quick start guide](https://tauri.app/v1/guides/getting-started/setup/vite), runing yarn tauri dev, I got an error and was not able to launch the demo.

### Reproduction

1. yarn create tauri-app
2. choose the following options:
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-vite (vanilla, vue, react, svelte, preact, lit) (https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
? Add "@tauri-apps/api" npm package? Yes
? Which vite template would you like to use? vanilla-ts
3. yarn tauri dev

### Expected behavior

The app launches successfully as expected:
![image](https://user-images.githubusercontent.com/7589350/174981885-be16e8b3-8f87-46b8-b97f-48b6d13d068e.png)

### Platform and versions

```shell
Environment
  › OS: Mac OS 10.13.6 X64
  › Node.js: 14.18.0
  › npm: 6.14.15
  › pnpm: 7.2.1
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ .husky
  ├─ node_modules
  ├─ public
  ├─ build
  ├─ .git
  ├─ .vscode
  └─ src
```

### Stack trace

```shell
soon@SoondeMacBook-Pro tauri-app $ RUST_BACKTRACE=1 yarn tauri dev
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`yarn dev`)
        Warn Waiting for your frontend dev server to start on http://localhost:3000/...
$ vite

  vite v2.9.12 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 150ms.

    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/app`
2022-06-22 16:18:51.014 app[47959:855547] -[TaoApp effectiveAppearance]: unrecognized selector sent to instance 0x7f90bd402790
thread 'main' panicked at 'Uncaught exception <NSException: 0x7f90bd70fc90>', /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.11.2/src/platform_impl/macos/window.rs:277:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:72:5
   3: tao::platform_impl::platform::window::get_ns_theme
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.11.2/src/platform_impl/macos/window.rs:277:26
   4: tao::platform_impl::platform::window::UnownedWindow::new
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.11.2/src/platform_impl/macos/window.rs:498:31
   5: tao::platform_impl::platform::Window::new
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.11.2/src/platform_impl/macos/mod.rs:90:30
   6: tao::window::WindowBuilder::build
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.11.2/src/window.rs:389:5
   7: tauri_runtime_wry::create_webview
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.9.0/src/lib.rs:2937:16
   8: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::create_window
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.9.0/src/lib.rs:1934:19
   9: tauri::app::Builder<R>::build
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0/src/app.rs:1451:22
  10: tauri::app::Builder<R>::run
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0/src/app.rs:1465:5
  11: app::main
             at ./src/main.rs:8:3
  12: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by FabianLars** [comment]
Should be fixed by https://github.com/tauri-apps/tao/pull/429 which will be available via `cargo update` when tao's next patch is released.
