### ISSUE TITLE
[bug] `yarn dev` error sometimes (macOS)

### ISSUE THREAD

**Issue by rming** [tauri-apps/tauri#4532]
### Describe the bug

`yarn dev` on a m1 Max MacBook Pro

```
  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.173:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

warning: `app` (bin "app") generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 2.75s
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Creating new window
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Creating new window
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Creating new window
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2022-06-30][15:39:15][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-06-30][15:39:15][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationDidFinishLaunching`
[2022-06-30][15:39:15][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2022-06-30][15:39:15][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2022-06-30][15:39:15][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2022-06-30][15:39:15][tao::platform_impl::platform::app_state][TRACE] Skipping activating invisible window
[2022-06-30][15:39:15][tao::platform_impl::platform::app_state][TRACE] Skipping activating invisible window
[2022-06-30][15:39:15][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationDidFinishLaunching`
[2022-06-30][15:39:15][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidBecomeKey:`
[2022-06-30][15:39:15][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidBecomeKey:`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tauri-runtime-wry-0.10.0/src/lib.rs:2303:37
stack backtrace:
   0:        0x1032fcfac - std::backtrace_rs::backtrace::libunwind::trace::hce65e3f7a6c49d1b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1032fcfac - std::backtrace_rs::backtrace::trace_unsynchronized::h8e403a36971945a4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1032fcfac - std::sys_common::backtrace::_print_fmt::h01edb83516020417
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x1032fcfac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdb141e7893323405
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10331b3d0 - core::fmt::write::hed96bcfc6342aee5
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:        0x1032f6784 - std::io::Write::write_fmt::h67807909d9a5a6e1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:        0x1032fead8 - std::sys_common::backtrace::_print::h7267448814343cd4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x1032fead8 - std::sys_common::backtrace::print::h83926e01abfb57bc
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x1032fead8 - std::panicking::default_hook::{{closure}}::h23ab3d10a9c5bb0f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:        0x1032fe7b4 - std::panicking::default_hook::hfa3eb92a01f5118c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:        0x1032fefb0 - std::panicking::rust_panic_with_hook::h94fcfaabb5f8247c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:        0x1032feea4 - std::panicking::begin_panic_handler::{{closure}}::h5c2b0281f2361f0b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:        0x1032fd488 - std::sys_common::backtrace::__rust_end_short_backtrace::h48848f94b4985ec4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x1032febfc - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:        0x1033400f0 - core::panicking::panic_fmt::hfc743f4016412d36
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:        0x103340194 - core::result::unwrap_failed::h964512213a00d9f4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
  16:        0x102b79744 - core::result::Result<T,E>::unwrap::h6e829d50d4ae2456
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
  17:        0x102b64f38 - tauri_runtime_wry::handle_user_message::h096dbd81d02a5ca0
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tauri-runtime-wry-0.10.0/src/lib.rs:2303:15
  18:        0x1028b5b64 - tauri_runtime_wry::handle_event_loop::h758560db440e8b43
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tauri-runtime-wry-0.10.0/src/lib.rs:2712:16
  19:        0x1028b91d0 - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::{{closure}}::hf15fc85e316ba170
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tauri-runtime-wry-0.10.0/src/lib.rs:2088:7
  20:        0x1027de6d4 - <tao::platform_impl::platform::app_state::EventLoopHandler<T> as tao::platform_impl::platform::app_state::EventHandler>::handle_user_events::{{closure}}::hab3cf0499ecb37b5
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/app_state.rs:116:11
  21:        0x1027ded34 - tao::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback::h321e17e5a7006e7c
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/app_state.rs:78:7
  22:        0x1027de47c - <tao::platform_impl::platform::app_state::EventLoopHandler<T> as tao::platform_impl::platform::app_state::EventHandler>::handle_user_events::h806ca04ec20598bd
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/app_state.rs:110:5
  23:        0x102ca9240 - tao::platform_impl::platform::app_state::Handler::handle_user_events::hc1caebd4bb4d3c95
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/app_state.rs:216:7
  24:        0x102caa988 - tao::platform_impl::platform::app_state::AppState::cleared::hea46bd7c77ffabc8
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/app_state.rs:376:5
  25:        0x102c929e4 - tao::platform_impl::platform::observer::control_flow_end_handler::{{closure}}::h6618b2b604b8cf2f
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/observer.rs:186:11
  26:        0x102c927c0 - tao::platform_impl::platform::observer::control_flow_handler::{{closure}}::h46c214736f47fa35
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/observer.rs:147:5
  27:        0x102cc705c - std::panicking::try::do_call::h70d86fc566037345
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  28:        0x102cd1928 - ___rust_try
  29:        0x102cc6e58 - std::panicking::try::hc39bf387fdfea32a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  30:        0x102cf8270 - std::panic::catch_unwind::h1d87c523f3e0d588
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  31:        0x102cbb754 - tao::platform_impl::platform::event_loop::stop_app_on_panic::h85c45835169e6003
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/event_loop.rs:224:9
  32:        0x102c925f8 - tao::platform_impl::platform::observer::control_flow_handler::h3765c27488cc28c9
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/observer.rs:145:3
  33:        0x102c92960 - tao::platform_impl::platform::observer::control_flow_end_handler::hc5671f39b2276e0b
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/observer.rs:181:5
  34:        0x1862b9bb0 - <unknown>
  35:        0x1862b9a00 - <unknown>
  36:        0x1862b904c - <unknown>
  37:        0x1862b8490 - <unknown>
  38:        0x18eed8dd8 - <unknown>
  39:        0x18eed8b54 - <unknown>
  40:        0x18eed8908 - <unknown>
  41:        0x188e17b2c - <unknown>
  42:        0x188e16424 - <unknown>
  43:        0x188e085f0 - <unknown>
  44:        0x102ed2cd0 - <() as objc::message::MessageArguments>::invoke::h86a8f4289278a7d6
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc-0.2.7/src/message/mod.rs:128:17
  45:        0x102ed6c34 - objc::message::platform::send_unverified::{{closure}}::h136642d79117a062
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc-0.2.7/src/message/apple/mod.rs:27:9
  46:        0x102ed55c4 - objc_exception::try::{{closure}}::h0c68625977f61bee
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc_exception-0.1.2/src/lib.rs:68:31
  47:        0x102ed4704 - objc_exception::try_no_ret::try_objc_execute_closure::he0ea8400553b7587
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc_exception-0.1.2/src/lib.rs:34:9
  48:        0x102ee3d48 - RustObjCExceptionTryCatch
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc_exception-0.1.2/extern/exception.m:10:9
  49:        0x102ed3930 - objc_exception::try_no_ret::h9c6ef3fd7259b388
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc_exception-0.1.2/src/lib.rs:44:19
  50:        0x102ed5130 - objc_exception::try::hcd802a3af3ae1db2
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc_exception-0.1.2/src/lib.rs:67:9
  51:        0x102eda734 - objc::exception::try::h15fccf109439c73a
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc-0.2.7/src/exception.rs:8:5
  52:        0x102ed62c0 - objc::message::platform::send_unverified::h81dec54b0996d67f
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc-0.2.7/src/message/apple/mod.rs:26:5
  53:        0x1024bfc64 - objc::message::send_message::h9e33fa9ac086c2cc
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/objc-0.2.7/src/message/mod.rs:178:5
  54:        0x1024bfc64 - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h24c446283d7a22f2
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/event_loop.rs:181:16
  55:        0x1024c0a20 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::h7c91ef6840d30ac3
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/platform_impl/macos/event_loop.rs:148:21
  56:        0x102630384 - tao::event_loop::EventLoop<T>::run::hc315a2223508f10b
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tao-0.12.0/src/event_loop.rs:177:5
  57:        0x1028b8c6c - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::hc278be58e2389483
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tauri-runtime-wry-0.10.0/src/lib.rs:2062:5
  58:        0x10257b5c8 - tauri::app::App<R>::run::h0451279ca608049c
                               at /Users/afa/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/tauri-1.0.1/src/app.rs:732:5
  59:        0x10273be24 - app::main::h58790b4639e43809
                               at /Users/afa/git/repo/src-tauri/src/main.rs:111:3
  60:        0x102640234 - core::ops::function::FnOnce::call_once::h6790abd6bb8be81c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  61:        0x10288f940 - std::sys_common::backtrace::__rust_begin_short_backtrace::h58f210755a3c2dcb
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  62:        0x102890984 - std::rt::lang_start::{{closure}}::h1878bb2938b3eb06
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:145:18
  63:        0x1032f0fe0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h485d4c2966ec30a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  64:        0x1032f0fe0 - std::panicking::try::do_call::h375a887be0bea938
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  65:        0x1032f0fe0 - std::panicking::try::hecad40482ef3be15
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  66:        0x1032f0fe0 - std::panic::catch_unwind::haf1f664eb41a88eb
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  67:        0x1032f0fe0 - std::rt::lang_start_internal::{{closure}}::h976eba434e9ff4cf
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  68:        0x1032f0fe0 - std::panicking::try::do_call::h8f2501ab92e340b0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  69:        0x1032f0fe0 - std::panicking::try::hbeb9f8df83454d42
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  70:        0x1032f0fe0 - std::panic::catch_unwind::h0a9390b2202af6e9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  71:        0x1032f0fe0 - std::rt::lang_start_internal::hc453db0ee48af82e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  72:        0x10289094c - std::rt::lang_start::hdee114087f90fe76
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:144:17
  73:        0x10273beb0 - _main
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Platform and versions

```shell
yarn run v1.22.17
$ /Users/afa/git/repo/node_modules/.bin/tauri info

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.1
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.1,
  › tauri-build [RUST]: 1.0.1,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: img-src 'self' data: https:; script-src 'unsafe-eval' 'self'; default-src blob: data: filesystem: tauri: 'unsafe-eval' 'unsafe-inline' 'self'
  › distDir: ../dist
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ patches
  ├─ node_modules
  ├─ updater
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ tmp
  └─ src
✨  Done in 14.07s.
```

**Comment by lucasfernog** [comment]
Thanks for catching this! Fix will be available soon.
