### ISSUE TITLE
[bug] Failed to open devtools programatically

### ISSUE THREAD

**Issue by JSoon** [tauri-apps/tauri#4612]
### Describe the bug

To be honest, I am a newcomer to Rust. So I just follow the [tauri-docs](https://tauri.app/v1/guides/debugging/application#opening-devtools-programatically) to open devtools like this:

**main.rs**
```rust
fn main() {
  use tauri::Manager;
  let context = tauri::generate_context!();
  tauri::Builder::default()
    .setup(|app| {
      #[cfg(debug_assertions)] // only include this code on debug builds
      {
        let window = app.get_window("main").unwrap();
        window.open_devtools();
        // window.close_devtools();
      }
      Ok(())
    })
    .menu(tauri::Menu::os_default(&context.package_info().name))
    .invoke_handler(tauri::generate_handler![greet])
    .run(context)
    .expect("error while running tauri application");
}
```

It did not work and I cannot figure it out myself.

### Reproduction

RUST_BACKTRACE=1 tauri dev --verbose

### Expected behavior

The devtools opened after running the app.

### Platform and versions

```shell
Environment
  › OS: Mac OS 10.13.6 X64
  › Node.js: 14.18.0
  › npm: 6.14.15
  › pnpm: 7.2.1
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.1
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ dist-isolation
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```

### Stack trace

```shell
2022-07-07 15:43:29.684119+0800 app[67485:1383460] NSWindow warning: adding an unknown subview: <WKInspectorWKWebView: 0x1030b0650>. Break on NSLog to debug.
2022-07-07 15:43:29.701887+0800 app[67485:1383460] Call stack:
(
        0   AppKit                              0x00007fff2dec8285 -[NSThemeFrame addSubview:] + 109
        1   AppKit                              0x00007fff2dec80c2 -[NSView addSubview:positioned:relativeTo:] + 214
        2   AppKit                              0x00007fff2e704561 -[NSThemeFrame addSubview:positioned:relativeTo:] + 42
        3   WebKit                              0x00007fff3f540099 _ZN6WebKit17WebInspectorProxy14platformAttachEv + 297
        4   WebKit                              0x00007fff3f74a37e _ZN6WebKit17WebInspectorProxy4openEv + 82
        5   WebKit                              0x00007fff3f5c84a1 _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 127
        6   WebKit                              0x00007fff3f804324 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 24
        7   WebKit                              0x00007fff3f59588d _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 119
        8   WebKit                              0x00007fff3f5983e4 _ZN3IPC10Connection18dispatchOneMessageEv + 176
        9   JavaScriptCore                      0x00007fff3457509c _ZN3WTF7RunLoop11performWorkEv + 236
        10  JavaScriptCore                      0x00007fff34575332 _ZN3WTF7RunLoop11performWorkEPv + 34
        11  CoreFoundation                      0x00007fff30932a11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        12  CoreFoundation                      0x00007fff309ec42c __CFRunLoopDoSource0 + 108
        13  CoreFoundation                      0x00007fff30915470 __CFRunLoopDoSources0 + 208
        14  CoreFoundation                      0x00007fff309148ed __CFRunLoopRun + 1293
2022-07-07 15:57:10.662133+0800 app[68138:1394108] -[WryWebView _inspector]: unrecognized selector sent to instance 0x102753690
thread 'main' panicked at 'Uncaught exception <NSException: 0x10263ac30>', /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.19.0/src/webview/wkwebview/mod.rs:593:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:72:5
   3: wry::webview::wkwebview::InnerWebView::open_devtools
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.19.0/src/webview/wkwebview/mod.rs:593:22
   4: wry::webview::WebView::open_devtools
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.19.0/src/webview/mod.rs:488:5
   5: tauri_runtime_wry::handle_user_message
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.10.2/src/lib.rs:2226:17
   6: tauri_runtime_wry::send_user_message
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.10.2/src/lib.rs:170:5
   7: <tauri_runtime_wry::WryDispatcher<T> as tauri_runtime::Dispatch<T>>::open_devtools
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.10.2/src/lib.rs:1179:13
   8: tauri::window::Window<R>::open_devtools
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.3/src/window.rs:1269:5
   9: app::main::{{closure}}
             at ./src-tauri/src/main.rs:17:7
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
  12: tauri::app::Builder<R>::build
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.3/src/app.rs:1575:5
  13: tauri::app::Builder<R>::run
             at /Users/soon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.3/src/app.rs:1585:5
  14: app::main
             at ./src-tauri/src/main.rs:14:3
  15: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by JSoon** [comment]
Just tested the same code on my Windows computer, and it worked as expected.

**Comment by lucasfernog** [comment]
That API is only supported on 10.15+, the API we use is private on macOS so they can break it anytime.

**Comment by JSoon** [comment]
Well, thanks for explanation. Besides, is it possible that adding compatibility info(or maybe I missed something like that?) on the API [open_devtools](https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.open_devtools) or the [tauri docs](https://tauri.app/v1/guides/debugging/application#opening-devtools-programatically)? Sometimes it makes people confused, especially for developers who are not familiar with Rust. Well, like...me x(

**Comment by lucasfernog** [comment]
Yeah i'll do that if we can't find the API for macOS 10.13.

**Comment by lucasfernog** [comment]
I've tried https://stackoverflow.com/questions/2036148/how-can-i-pop-up-webkits-web-inspector-from-my-webview-object-programmatically but i think it's for older macOS, 10.13 doesn't seem to have this API. If you find out which API we should use, we can adapt it here: https://github.com/tauri-apps/wry/blob/dev/src/webview/wkwebview/mod.rs#L589

For now I'll update the docs and close this issue :( too old of a macOS release to support private APIS :/
