### ISSUE TITLE
[bug] Rust Analyzer crashes with proc macro and

### ISSUE THREAD

**Issue by CrendKing** [tauri-apps/tauri#4706]
### Describe the bug

Upon loading the workspace in VSCode with rust-analyzer extension, the "Rust Analyzer Language Server" output shows tons of crash stacktraces. As a result, any function with a proc macro involved with not show inlay hint or Intellisense popup.

### Reproduction

1. `pnpm create tauri-app`
2. Follow the prompt to create an app. I tried the svelte-ts variant.
3. Open the "src-tauri" directory with VSCode.
4. Wait for rust analyzer to finish, then go to the output panel, switch to the "Rust Analyzer Language Server" panel.
5. Observe error messages.
6. Put the following code in main.rs:
```
#[tauri::command]
fn test(arg: &str) {
  let var = arg;
}
```
7. Notice the type inlay hint for `var` no longer works. `arg.` won't show Intellisense prompt.

### Expected behavior

Rust analyzer should not stop working in Tauri app.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 103.0.1264.62
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 7.5.2
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0-nightly
  › cargo: 1.64.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.4
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

### Stack trace

I think there are two kinds:
1.
```
thread '<unnamed>' panicked at 'range end index 4 out of range for slice of length 0', library\core\src\slice\index.rs:73:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\panicking.rs:142
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\slice\index.rs:73
   3: core::ops::function::FnOnce::call_once<never$ (*)(usize,usize),tuple$<usize,usize> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\ops\function.rs:248
   4: core::intrinsics::const_eval_select<tuple$<usize,usize>,never$ (*)(usize,usize),never$ (*)(usize,usize),never$>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\intrinsics.rs:2697
   5: core::slice::index::slice_end_index_len_fail
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\slice\index.rs:67
   6: core::slice::index::impl$3::index<u8>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\core\src\slice\index.rs:304
   7: proc_macro::bridge::rpc::impl$26::decode<tuple$<> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:38
   8: proc_macro::bridge::rpc::impl$9::decode<tuple$<> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:169
   9: proc_macro::bridge::client::impl$79::decode<tuple$<> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:166
  10: proc_macro::bridge::impl$81::decode<tuple$<>,proc_macro::bridge::client::Span>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:57
  11: proc_macro::bridge::rpc::impl$11::decode<tuple$<>,proc_macro::bridge::ExpnGlobals<proc_macro::bridge::client::Span>,proc_macro::bridge::client::TokenStream>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:184
  12: proc_macro::bridge::client::run_client::closure$0<proc_macro::bridge::client::TokenStream,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>,proc_macro::bridge::client::impl$13::expand1::closure$0::closure_env$0<proc
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:409
  13: core::panic::unwind_safe::impl$23::call_once<tuple$<>,proc_macro::bridge::client::run_client::closure_env$0<proc_macro::bridge::client::TokenStream,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>,proc_macro::bridg
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\core\src\panic\unwind_safe.rs:271
  14: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client::closure_env$0<proc_macro::bridge::client::TokenStream,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\std\src\panicking.rs:492
  15: serde_derive::internals::case::impl$1::fmt
  16: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client::closure_env$0<proc_macro::bridge::client::TokenStream,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\std\src\panicking.rs:456
  17: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client::closure_env$0<proc_macro::bridge::client::TokenStream,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>,pro
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\std\src\panic.rs:137
  18: proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>,proc_macro::bridge::client::impl$13::expand1::closure$0::closure_env$0<proc_macro::Tok
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:405
  19: proc_macro::bridge::client::impl$13::expand1::closure$0<proc_macro::TokenStream (*)(proc_macro::TokenStream)>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:449
  20: proc_macro::bridge::selfless_reify::reify_to_extern_c_fn_hrt_bridge::wrapper<proc_macro::bridge::buffer::Buffer,proc_macro::bridge::client::impl$13::expand1::closure_env$0<proc_macro::TokenStream (*)(proc_macro::TokenStream)> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\selfless_reify.rs:64
  21: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::server::run_server
  22: proc_macro_srv::abis::abi_1_63::Abi::expand
  23: proc_macro_srv::abis::Abi::expand
  24: proc_macro_srv::dylib::Expander::expand
  25: proc_macro_srv::cli::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

2.
```
thread '<unnamed>' panicked at 'range end index 4 out of range for slice of length 0', library\core\src\slice\index.rs:73:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\panicking.rs:142
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\slice\index.rs:73
   3: core::ops::function::FnOnce::call_once<never$ (*)(usize,usize),tuple$<usize,usize> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\ops\function.rs:248
   4: core::intrinsics::const_eval_select<tuple$<usize,usize>,never$ (*)(usize,usize),never$ (*)(usize,usize),never$>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\intrinsics.rs:2697
   5: core::slice::index::slice_end_index_len_fail
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library\core\src\slice\index.rs:67
   6: core::slice::index::impl$3::index<u8>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\core\src\slice\index.rs:304
   7: proc_macro::bridge::rpc::impl$26::decode<tuple$<> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:38
   8: proc_macro::bridge::rpc::impl$9::decode<tuple$<> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:169
   9: proc_macro::bridge::client::impl$79::decode<tuple$<> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:166
  10: proc_macro::bridge::impl$81::decode<tuple$<>,proc_macro::bridge::client::Span>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:57
  11: proc_macro::bridge::rpc::impl$11::decode<tuple$<>,proc_macro::bridge::ExpnGlobals<proc_macro::bridge::client::Span>,tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\rpc.rs:184
  12: proc_macro::bridge::client::run_client::closure$0<tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream>,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>,proc_macro::bridge::client:
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:409
  13: core::panic::unwind_safe::impl$23::call_once<tuple$<>,proc_macro::bridge::client::run_client::closure_env$0<tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream>,enum$<core::option::Option<proc_macro::bridge::client::Toke
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\core\src\panic\unwind_safe.rs:271
  14: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client::closure_env$0<tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream>,enum$<core::option::Option<proc_macro::br
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\std\src\panicking.rs:492
  15: tauri_macros::command::wrapper::snake_case_to_camel_case
  16: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client::closure_env$0<tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream>,enum$<core::option::Option<proc_macro::br
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\std\src\panicking.rs:456
  17: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client::closure_env$0<tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream>,enum$<core::option::Option<proc_macro::bridge
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\std\src\panic.rs:137
  18: proc_macro::bridge::client::run_client<tuple$<proc_macro::bridge::client::TokenStream,proc_macro::bridge::client::TokenStream>,enum$<core::option::Option<proc_macro::bridge::client::TokenStream>, 1, 4294967295, Some>,proc_macro::bridge::client::impl$14::e
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:405
  19: proc_macro::bridge::client::impl$14::expand2::closure$0<proc_macro::TokenStream (*)(proc_macro::TokenStream,proc_macro::TokenStream)>
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\client.rs:463
  20: proc_macro::bridge::selfless_reify::reify_to_extern_c_fn_hrt_bridge::wrapper<proc_macro::bridge::buffer::Buffer,proc_macro::bridge::client::impl$14::expand2::closure_env$0<proc_macro::TokenStream (*)(proc_macro::TokenStream,proc_macro::TokenStream)> >
             at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c\library\proc_macro\src\bridge\selfless_reify.rs:64
  21: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::server::run_server
  22: proc_macro_srv::abis::abi_1_63::Abi::expand
  23: proc_macro_srv::abis::Abi::expand
  24: proc_macro_srv::dylib::Expander::expand
  25: proc_macro_srv::cli::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by amrbashir** [comment]
this is an issue with nightly rust, please use stable rust.
