### ISSUE TITLE
[bug] panic on cargo tauri dev

### ISSUE THREAD

**Issue by marn13** [tauri-apps/tauri#5057]
### Describe the bug

Hi, 
I am experimenting with tauri. I've got an error while starting tauri with cargo tauri init: 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" })' after havine initialized new example project with .

The stange thing is tha I'am able to build and run the application using direct call cargo run ./ 

I'll appreciate any help.

### Reproduction

step by step following tutorial:
https://tauri.app/v1/guides/getting-started/setup/html-css-js

### Platform and versions

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 12.22.9
  › npm: 8.5.1
  › pnpm: Not installed!
  › yarn: 0.32+git
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ./ui
  › devPath: ./ui

App directory structure
  └─ src-tauri

### Stack trace

```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" })', /home/marn/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.5/src/interface/rust.rs:126:61
stack backtrace:
   0:     0x55e793b256f1 - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e793b256f1 - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e793b256f1 - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e793b256f1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e793944cdc - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55e793af72b4 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55e793b28036 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e793b28036 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e793b28036 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55e793b27cbc - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x55e793b28ca5 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x55e793b28ba2 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x55e793b28b16 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55e793b28ad2 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x55e7938b2652 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x55e7938b28d2 - core::result::unwrap_failed::hc0baa33ef8bc7db8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
  16:     0x55e793c13a41 - <tauri_cli::interface::rust::Rust as tauri_cli::interface::Interface>::new::ha69348935de3f265
  17:     0x55e793ba99a0 - tauri_cli::dev::command::h2ba148416281460e
  18:     0x55e7938d3ad9 - tauri_cli::run::h14168c51a7b8db54
  19:     0x55e7938edaeb - cargo_tauri::main::h050eb9348b71289f
  20:     0x55e7938edc63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h54d95939d062baaa
  21:     0x55e7938ed2a6 - main
  22:     0x7f4ece358d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23:     0x7f4ece358e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  24:     0x55e7938cf0b5 - _start
  25:                0x0 - <unknown>
```

### Additional context

I have installed @tauri-apps/api with npm (version 1.0.2) but the result is the same.

**Comment by FabianLars** [comment]
Sounds like this one <https://github.com/notify-rs/notify/issues/282>

**Comment by marn13** [comment]
> Sounds like this one [notify-rs/notify#282](https://github.com/notify-rs/notify/issues/282)

yep... 
installing inotify-tools

and 

sudo sysctl fs.inotify.max_user_instances=8192
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl -p

solved the problem!

Maybe Setting Up Linux section in the tutorial could be updated?

Thanks!!!

**Comment by FabianLars** [comment]
> Maybe Setting Up Linux section in the tutorial could be updated?

We will add it to our FAQ page if more people have this issue, so far you've been the only one and inotify-tools should normally be present on every system as far as i know.
