### ISSUE TITLE
[bug] `yarn tauri dev` crashes with "panicked at 'called `Result::unwrap()` on an `Err` value"

### ISSUE THREAD

**Issue by half0wl** [tauri-apps/tauri#5803]
### Describe the bug

Running `$ yarn tauri dev` throws a Rust error (see stack trace).

### Reproduction

1. `$ yarn create tauri-app` with the following options:
    * Package manager: `yarn`
    * UI template: `react-ts`
2. Follow instructions:
    * `$ yarn`
    * `$ yarn tauri dev`
3. `$ yarn tauri dev` results in:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
```

### Expected behavior

It should not crash.

### Platform and versions

```sh
$ yarn tauri info
yarn run v1.22.18
$ tauri info

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.8.0
  › npm: 9.1.3
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.7,
  › wry [RUST]: 0.23.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
✨  Done in 8.53s.
```

### Stack trace

```shell
$ export RUST_BACKTRACE=full; yarn tauri dev
yarn run v1.22.18
$ tauri dev
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
stack backtrace:
   0:        0x10896c368 - _napi_register_module_v1
   1:        0x108588b1c - <unknown>
   2:        0x10894681c - _napi_register_module_v1
   3:        0x108970ae4 - _napi_register_module_v1
   4:        0x1089707a8 - _napi_register_module_v1
   5:        0x108970ea8 - _napi_register_module_v1
   6:        0x108970de0 - _napi_register_module_v1
   7:        0x108970d54 - _napi_register_module_v1
   8:        0x108970d30 - _napi_register_module_v1
   9:        0x108cdc158 - _napi_register_module_v1
  10:        0x108cdc310 - _napi_register_module_v1
  11:        0x108a81b7c - _napi_register_module_v1
  12:        0x108b77a9c - _napi_register_module_v1
  13:        0x108bd499c - _napi_register_module_v1
  14:        0x108bdb510 - _napi_register_module_v1
  15:        0x108bda82c - _napi_register_module_v1
  16:        0x108972eb4 - _napi_register_module_v1
  17:        0x19de0426c - __pthread_deallocate
✨  Done in 1.12s.
```

### Additional context

I worked around this by running `cargo build` in `src-tauri/`. `yarn tauri dev` works after that.

This appears to be some CLI tooling issue. The error is thrown from [this block](https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/src/interface/rust.rs#L756-L772), specifically L762:

https://github.com/tauri-apps/tauri/blob/eaf0d71779707c69903aba6106322c8908107242/tooling/cli/src/interface/rust.rs#L762

**Comment by amrbashir** [comment]
Did you install Rust? https://tauri.app/v1/guides/getting-started/prerequisites/#2-rust make sure to install all prerequisites.

**Comment by half0wl** [comment]
..turns out it was an issue with my `$PATH` - I was in an old session and forgot to re-`source` after moving some things around, so `rustc`/`cargo` wasn't available.

Thanks @amrbashir!
