### ISSUE TITLE
nix tailwindcss integration fails - postcss error

### ISSUE THREAD

**Issue by thinkrapido** [tauri-apps/tauri#5839]
### Describe the bug

I think, the problem is, because the processing mechanism of postcss.

I followed the installation instructions of tailwindcss from the webpage https://tailwindcss.com/docs/guides/sveltekit

I get

```
[vite] Internal server error: [postcss] /<abs path to project>/src/routes/+page.svelte?svelte&type=style&lang.css:1:1: Unknown word
  Plugin: vite:css
  File: /<abs path to project>/src/routes/+page.svelte?svelte&type=style&lang.css:1:1
  1  |  <script>
     |   ^
  2  |    import Greet from "$lib/Greet.svelte";
  3  |  </script>

```

### Reproduction

1. Blank install of tauri with svelte & Typescript
2. Adding tailwind described on webpage https://tailwindcss.com/docs/guides/sveltekit

### Expected behavior

We are having here an absolute path from the filesystem.
I suppose, postwind needs an url to attach url parameters on it to parse the css

?svelte&type=style&lang.css:1:1

### Platform and versions

I think any

### Stack trace

```shell
at Input.error (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/input.js:148:16)
      at Parser.unknownWord (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:540:22)
      at Parser.other (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:164:12)
      at Parser.parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:72:16)
      at parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/processor.js:28:14)
      at compileCSS (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37647:14)
      at async TransformContext.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37121:56)
      at async Object.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:42569:30)
```

**Comment by amrbashir** [comment]
I think this issue should be opened at either tailwaindss, sveltekit or vite as this is not an issue with Tauri itself (if you can confirm it is, please let me know and I will reopen).

**Comment by thinkrapido** [comment]
Reposted this problem

https://github.com/postcss/postcss/issues/1805
https://github.com/tailwindlabs/tailwindcss/issues/10081

**Comment by amrbashir** [comment]
Please note that this issue has nothing to do with tauri at all, you can try to run the web project inside the browser, and you will get the same error. This is more of an issue with integrating `tailwindcss` inside a `sveltekit` project.

**Comment by thinkrapido** [comment]
Someone from tailwind picked it up. I hope he can solve this issue.

**Comment by thinkrapido** [comment]
this is a nix related problem

**Comment by thinkrapido** [comment]
This is not a nix problem!!!
I have ubuntu 22.04 and installed all dependencies.
It's not working for `yarn tauri dev` but `yarn tauri build` creates at least a release target and starting it works out of the box with tailwindcss. But not with dev!!!
Please reopen this issue

**Comment by thinkrapido** [comment]
Where does tauri put it's temp files during dev processing?

**Comment by thinkrapido** [comment]
I don't have this issue when I start the frontend separately with `yarn dev`

I think, somehow tauri passes an absolute path to vite and the postcss where it goes worng.

**Comment by thinkrapido** [comment]
```
rm -rf src-tauri/target
rm -rf .svelte-kit
yarn tauri dev
```
fixes it

!!!SOLVED!!!

**Comment by thinkrapido** [comment]
The error reappeared!!!!!!!!! WTF

I figured out, that you need to rename the project folder.
Re-enter it and `rm -rf .svelte-kit`
Then `yarn tauri dev`. 
Now it should restart the project without the error.

(Hence, redo this to get the old folder name again.)

The vite tauri config is causing this problem.

**Comment by thinkrapido** [comment]
And `svelte.config.js` should be

```
import staticAdapter from "@sveltejs/adapter-static";
import preprocess from "svelte-preprocess";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: staticAdapter(),
  },
  preprocess: [
    preprocess()
  ]
};

export default config;
```

**Comment by thinkrapido** [comment]
wrong; it reappears again.
Guys from tauri. this is annoying

**Comment by thinkrapido** [comment]
`11:00:33 PM [vite] ✨ new dependencies optimized: @tauri-apps/api/tauri`

This line appears only sometimes and does the fix after renaming the folder. (See above)

**Comment by thinkrapido** [comment]
after this working reactivating `yarn tauri dev` it doesn't work again.

**Comment by thinkrapido** [comment]
Now it's working again, but now this message is shown now:

```
Not found: /@fs/home/jbc/Work/indi/aaa/node_modules/@sveltejs/kit/src/runtime/client/start.js
Error: Not found: /@fs/home/jbc/Work/indi/aaa/node_modules/@sveltejs/kit/src/runtime/client/start.js
    at resolve (file:///home/jbc/Work/indi/indi-desktop/node_modules/@sveltejs/kit/src/runtime/server/index.js:424:13)
    at resolve (file:///home/jbc/Work/indi/indi-desktop/node_modules/@sveltejs/kit/src/runtime/server/index.js:264:5)
    at Object.handle (file:///home/jbc/Work/indi/indi-desktop/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:396:66)
    at respond (file:///home/jbc/Work/indi/indi-desktop/node_modules/@sveltejs/kit/src/runtime/server/index.js:261:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/jbc/Work/indi/indi-desktop/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:480:22
```
as you can see here there is the current directory `indi-dektop` and it searches for `aaa` folder, which doesn't exist.

**Comment by thinkrapido** [comment]
Removing `.svelte-kit` again, fixes this error, but only once.
The next times I start `yarn tauri dev`, the first problem appears and persists.

```
1:08:55 PM [vite] Internal server error: [postcss] /home/jbc/Work/indi/indi-desktop/src/routes/+page.svelte?svelte&type=style&lang.css:1:1: Unknown word
  Plugin: vite:css
  File: /home/jbc/Work/indi/indi-desktop/src/routes/+page.svelte?svelte&type=style&lang.css:1:1
  1  |  <script>
     |   ^
  2  |    import Greet from "$lib/Greet.svelte";
  3  |  </script>
      at Input.error (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/input.js:148:16)
      at Parser.unknownWord (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:540:22)
      at Parser.other (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:164:12)
      at Parser.parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:72:16)
      at parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/processor.js:28:14)
      at compileCSS (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37647:14)
      at async TransformContext.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37121:56)
      at async Object.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:42569:30)
[postcss] /home/jbc/Work/indi/indi-desktop/src/routes/+page.svelte?svelte&type=style&lang.css:1:1: Unknown word
```

**Comment by thinkrapido** [comment]
Again. A fresh install of my project works for the first time.
Then starting it the second time fails.

**Comment by campbellcole** [comment]
I am also having this issue. I am using NixOS, but I see you've reproduced it on Ubuntu as well. If I reload the page when the error page is displayed, it just works and the error doesn't appear again for a while. Haven't figured out what triggers it to come back, but refreshing always gets it to go away for a little while. I tried running the commands you've sent and that doesn't work at all for me; the error returns on first run. I use SvelteKit + PostCSS on some other projects and this does not happen, so I'm inclined to believe this is actually a Tauri issue, but I admit I'm not an expert. 

It seems like postcss is trying to parse the contents of script tags in my svelte files for some reason.

**Comment by thinkrapido** [comment]
As I investigated it further, it happens only at the start of the application. A graceful reload of the page corrects the rendering.

(I thought it's all over persistent, but it isn't. When you reload gracefully, it is usable for development again.)

**Comment by koakh** [comment]
hi

thanks for the clues budies
I added this to my `package.json`  and is lightning fast boot tauri app, same speed :)
(is rare the case it gives the error, in that case I just reload and live with that, is only a `tauri dev` issue, if it was in production is a lot worst

```json
{
  "script": {
    "tauri:dev": "rm -rf src-tauri/target/debug/tauri-app-svelte-kit && tauri dev",
  }
}
```

**Comment by Pandananana** [comment]
I had the same issue after running the create-tauri-app for Tauri V2.

I fixed it by modifying the style tag in the offending svelte file and adding css as the language: 

`<style lang="css">`

Then it worked, also when opening the app for the first time.

**Comment by yueduz** [comment]
I have the same problem when I open it from npm run tauri dev.
I run npm run dev and open http://localhost:1420/ from chrome without any problem.
