### ISSUE TITLE
[bug] Missing top-level `package.json` breaks `tauri info`

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#5866]
### Describe the bug

When there's no `package.json` file in the current working directory the `tauri info` command panics with the following message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', /Users/jonaskruckenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-2.0.0-alpha.0/src/info.rs:566:67
```

### Reproduction

1. Scaffold a new Tauri project
2. delete the `package.json` file
3. Run `tauri info`
4. The output panics while trying to print the `@tauri-apps/api` info

### Expected behavior

![Don't panic](https://thumbs.gfycat.com/AngelicHeartfeltHog-size_restricted.gif)

### Platform and versions

(hahaha)
here's the info with a mocked package.json:
```
Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.18.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.1 (1.2.2, 2.0.0-alpha.1),
  › tauri-build [RUST]: 2.0.0-alpha.0,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.23.1,

App
  › build-type: bundle
  › CSP: img-src 'self' data: https:; style-src 'self'; font-src 'self'; media-src https:; default-src 'none'; connect-src https: wss:
  › distDir: ../elk/.output/public
  › devPath: http://localhost:5314/

App directory structure
  ├─ target
  ├─ elk
  ├─ .github
  ├─ src-tauri
  └─ .git

iOS
  › Teams: None
```

### Stack trace

```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', /Users/jonaskruckenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-2.0.0-alpha.0/src/info.rs:566:67
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: tauri_cli::info::VersionBlock::display
   4: tauri_cli::info::command
   5: tauri_cli::run
   6: cargo_tauri::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  › @tauri-apps/api [NPM]: tauri-apps%
```

**Comment by amrbashir** [comment]
Can you get the full stack trace? I am not able to reproduce it on Windows.

**Comment by lucasfernog** [comment]
Same as Amr, I can't reproduce it. Might be something specific to your project.

**Comment by JonasKruckenberg** [comment]
Hmm weird, I'll check again

**Comment by lucasfernog** [comment]
Maybe #5873 fixes it.

**Comment by renestalder** [comment]
> Maybe #5873 fixes it.

That's precisely what it might be.

I can replicate the issue by following:

1. Create new project with `pnpm create tauri-app`
2. `pnpm install`
3. Run `pnpm tauri info`

And I can fix it by:

1. `cd src-tauri`
2. `cargo generate-lockfile`
