### ISSUE TITLE
[bug] AppImage Fails on Manjaro Linux

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#5923]
### Describe the bug

When running an AppImage on Manjaro, the app fails to run due to a panic.

### Reproduction

1. Using Manjaro or Arch based distro
2. Download AppImage from https://github.com/elibroftw/modern-desktop-app-template/releases/tag/v0.2.1. The source code is also available here.
3. run  `RUST_BACKTRACE=full ./product-name_0.2.1_amd64.AppImage` in terminal

### Expected behavior

Works without flaws.

### Platform and versions

NA

### Stack trace

```shell
thread 'main' panicked at 'data.len() must fit the width, height, and row_stride', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk-pixbuf-0.15.11/src/pixbuf.rs:52:13
stack backtrace:
   0:     0x5571d2da98a3 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5571d2da98a3 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5571d2da98a3 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5571d2da98a3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5571d2cf6efe - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x5571d2d7f0e4 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x5571d2daa8ff - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5571d2daa8ff - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5571d2daa4ff - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x5571d2dab568 - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x5571d2dab568 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x5571d2dab023 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
  12:     0x5571d2daafbc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5571d2daaf91 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x5571d2c1b272 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x5571d2db475a - <T as core::convert::Into<U>>::into::h23ad5cc30d63713b
  16:     0x5571d2dca9c7 - tao::platform_impl::platform::window::Window::new::h7a0187dd7459b6ae
  17:     0x5571d2c797b8 - tauri::app::Builder<R>::build::ha84541f3d78b689a
  18:     0x5571d2cceeb5 - app::main::hdc08c5d13af47d75
  19:     0x5571d2c59227 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6a758735d1667847
  20:     0x5571d2cd1d53 - main
  21:     0x7f3b5eb44290 - <unknown>
  22:     0x7f3b5eb4434a - __libc_start_main
  23:     0x5571d2c2f9c5 - _start
  24:                0x0 - <unknown
```

**Comment by elibroftw** [comment]
Is this bug because the app was created before [April 26th](https://github.com/tauri-apps/tauri/issues/3877)?

**Comment by FabianLars** [comment]
I can't reproduce this, did the icons update commit fix it?

**Comment by elibroftw** [comment]
```sh
   ~/Downloads  ./product-name_0.2.2_amd64.AppImage                                                  ✔ 
thread 'main' panicked at 'Unsupported platform!: UnsupportedPlatform', src/main.rs:204:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  ./product-name_0.2.2_amd64.AppImage
    ~/Downloads                                                                                   IOT ✘ 
```
The icon issue was fixed but now the bug is unsupported platform?
```
f let Some(window) = app.get_window("main") {
          set_shadow(&window, true).expect("Unsupported platform!");
        }
```
Will removing the expect fix the issue?

**Comment by elibroftw** [comment]
The window shadow plugin should not have a .expect for cross platform compatability...
