### ISSUE TITLE
[bug] Android app with Yew doesn't open, just immediate crash into stacktrace

### ISSUE THREAD

**Issue by Innominus** [tauri-apps/tauri#5937]
### Describe the bug

After initializing a new app with create-tauri-app and selecting Yew, and then running cargo tauri android dev it will build and then proceed to create an app on the phone which immediately crashes when opened.

### Reproduction

To reproduce:

1. Create a new Yew Tauri app with create-tauri-app
2. Initialize with cargo tauri android init
3. Set up symlink target folder in tauri-src folder to point to workspace parent's target folder as this is needed when everything links up to create the app bundle for the phone
4. Run cargo tauri android dev
5. Once bundle is created, app will open on phone for some milliseconds and immediately crash.

### Expected behavior

App opens, doesn't crash, and shows dev server output which is the default output from create-tauri-app

### Platform and versions

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 12.22.9
  › npm: 8.5.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.68.0-nightly
  › cargo: 1.68.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
package.json not found

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ src-tauri
  ├─ public
  ├─ target
  └─ src

### Stack trace

```shell
`    Finished dev [unoptimized + debuginfo] target(s) in 1m 27s
        Info symlinking lib "/home/sloth/code/projects/androidapp/src-tauri/target/aarch64-linux-android/debug/libandroidapp.so" in jniLibs dir "/home/sloth/code/projects/androidapp/src-tauri/gen/android/androidapp/app/src/main/jniLibs/arm64-v8a"
        Info "/home/sloth/code/projects/androidapp/src-tauri/target/aarch64-linux-android/debug/libandroidapp.so" requires shared lib "libdl.so"
        Info "/home/sloth/code/projects/androidapp/src-tauri/target/aarch64-linux-android/debug/libandroidapp.so" requires shared lib "libc.so"
Performing Streamed Install
Success
Starting: Intent { cmp=com.tauri.androidapp/.MainActivity }
--------- beginning of main
12-29 11:51:07.099 27748 27748 E auri.androidap: Unknown bits set in runtime_flags: 0x40000000
        Info Watching /home/sloth/code/projects/androidapp/src-tauri for changes...
12-29 11:52:28.739 27748 27817 E auri.androidap: Loaded layer handle (17600948172823207259) for layer /my_product/lib64/libcolorx-loader.so
12-29 11:52:28.739 27748 27817 E auri.androidap: Looking for entrypoint ColorX_Check
12-29 11:52:28.739 27748 27817 E auri.androidap: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
12-29 11:52:28.740 27748 27817 E auri.androidap: Check failed
12-29 11:52:28.775 27748 27748 E auri.androidap: No implementation found for void com.tauri.androidapp.TauriActivity.create(com.tauri.androidapp.TauriActivity) (tried Java_com_tauri_androidapp_TauriActivity_create and Java_com_tauri_androidapp_TauriActivity_create__Lcom_tauri_androidapp_TauriActivity_2)
--------- beginning of crash
12-29 11:52:28.776 27748 27748 E AndroidRuntime: FATAL EXCEPTION: main
12-29 11:52:28.776 27748 27748 E AndroidRuntime: Process: com.tauri.androidapp, PID: 27748
12-29 11:52:28.776 27748 27748 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.tauri.androidapp.TauriActivity.create(com.tauri.androidapp.TauriActivity) (tried Java_com_tauri_androidapp_TauriActivity_create and Java_com_tauri_androidapp_TauriActivity_create__Lcom_tauri_androidapp_TauriActivity_2)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at com.tauri.androidapp.TauriActivity.create(Native Method)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at com.tauri.androidapp.TauriActivity.onCreate(TauriActivity.kt:52)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8129)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8109)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
12-29 11:52:28.776 27748 27748 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
`
```

### Additional context
Phone is a OnePlus 9; no emulator was tested.
_No response_

**Comment by JonasKruckenberg** [comment]
Can you check that `tauri` and `tauri-build` are also using the latest `2.0.0-alpha.x` release? Because the Tauri info you pasted says the following:
```
tauri [RUST]: 1.2.3,
tauri-build [RUST]: 1.2.1,
```
which would explain why this is not working

**Comment by Innominus** [comment]
> Can you check that `tauri` and `tauri-build` are also using the latest `2.0.0-alpha.x` release? Because the Tauri info you pasted says the following:
> 
> ```
> tauri [RUST]: 1.2.3,
> tauri-build [RUST]: 1.2.1,
> ```
> 
> which would explain why this is not working

Very strange. I followed the guide link in the mobile section of the Discord, haven't had tauri installed previously and installed it direct from the git link given. I'll try upgrading it, as that seems like the obvious fix. Thanks so much for getting back to me on this issue :)

**Comment by Innominus** [comment]
Ah, I see. It's in the build-dependencies in my cargo.toml file. No worries, thanks :)
