### ISSUE TITLE
[bug] failed to resolve app dir in android

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6054]
### Describe the bug

When running inside android calls to `app.path_resolver().app_data_dir()` will return `None`.

### Reproduction

1. Setup an Tauri android project
2. call `app.path_resolver().app_data_dir()`

### Expected behavior

Should not return `None`.

### Platform and versions

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.24.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:566:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  › @tauri-apps/api [NPM]: tauri-apps

### Stack trace

```shell
01-13 21:53:49.035 18936 19042 I RustStdoutStderr: thread 'tokio-runtime-worker' panicked at 'failed to resolve app dir', /Users/jonaskruckenberg/.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/58dd417/plugins/store/src/store.rs:176:14
01-13 21:53:49.035 18936 19042 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional context

I don't know how easy to fix this is, from a quick search on google it seems that Android really want's you to use their Kotlin `Dir` API to interact with persistent files.

**Comment by JonasKruckenberg** [comment]
So the fundamental issue here is that `dirs_next` simply doesn't support Android. I had a quick search through docs.rs and it seems like we would need to somehow use `jni` to call the `context.getFilesDir()` method in order to obtain the correct path.

`ndk-context` and `jni` can be used to access the Context class:
https://docs.rs/ndk-context/latest/ndk_context/struct.AndroidContext.html
```rust
let ctx = ndk_context::android_context();
let vm = unsafe { jni::JavaVM::from_raw(ctx.vm().cast()) }?;
let env = vm.attach_current_thread();
let class_ctx = env.find_class("android/content/Context")?;
let dir = env.call_method(class_ctx, "getFilesDir", "Ljava/io/File;")?;
```
