### ISSUE TITLE
[bug] Crash on Assertion failure on macos ventura

### ISSUE THREAD

**Issue by Sytten** [tauri-apps/tauri#6082]
### Describe the bug

One of our user reported a crash when hitting ESC a lot on Intel mac, Ventura 13.1 (22C65)

```
❯ RUST_BACKTRACE=full /Applications/Caido.app/Contents/MacOS/Caido
2023-01-17 09:52:07.047 Caido[94074:2731631] *** Assertion failure in -[NSEvent keyCode], NSEvent.m:3003
thread 'main' panicked at 'Uncaught exception <NSException: 0x600001c28270>', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/event.rs:338:12
stack backtrace:
   0:        0x107226052 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2e8cbde22b780fc
   1:        0x10724645a - core::fmt::write::hd6692086cdd356a7
   2:        0x10721ea7c - std::io::Write::write_fmt::h6043124a2486acbb
   3:        0x107227b2b - std::panicking::default_hook::{{closure}}::h87a12b8b06887dd7
   4:        0x107227837 - std::panicking::default_hook::h7f68dad17e0bfaa4
   5:        0x10722814f - std::panicking::rust_panic_with_hook::hd57427cbbfc3717a
   6:        0x107228093 - std::panicking::begin_panic_handler::{{closure}}::h33aab6d04e2bba70
   7:        0x1072264e8 - std::sys_common::backtrace::__rust_end_short_backtrace::h0e7a76f927db9964
   8:        0x107227d5d - _rust_begin_unwind
   9:        0x10726f423 - core::panicking::panic_fmt::hcf6f3c517c6f3cb3
  10:        0x10708012b - core::panicking::panic_display::h4f4ce2dfcd1f5a69
  11:        0x107081fc3 - tao::platform_impl::platform::event::create_key_event::hcc46ee62bbe701ba
  12:        0x1070699e9 - tao::platform_impl::platform::view::cancel_operation::h73473d5ccb497dbf
  13:     0x7ff9076cb51d - <unknown>
  14:     0x7ff907735512 - <unknown>
  15:     0x7ff9077fe862 - <unknown>
  16:     0x7ff907c792c3 - <unknown>
  17:     0x7ff9076db4eb - <unknown>
  18:     0x7ff9078f025e - <unknown>
  19:     0x7ff9076d2e8d - <unknown>
  20:     0x7ff9076cf460 - <unknown>
  21:     0x7ff9076d463d - <unknown>
  22:     0x7ff820db7f6f - <unknown>
  23:     0x7ff820db885a - <unknown>
  24:     0x7ff807139b98 - <unknown>
  25:     0x7ff807139b47 - <unknown>
  26:     0x7ff807139921 - <unknown>
  27:     0x7ff80713859b - <unknown>
  28:     0x7ff807137b80 - <unknown>
  29:     0x7ff810a7c766 - <unknown>
  30:     0x7ff810a7c396 - <unknown>
  31:     0x7ff810a7c2b3 - <unknown>
  32:     0x7ff80a283f33 - <unknown>
  33:     0x7ff80a282db4 - <unknown>
  34:     0x7ff80a2753f7 - <unknown>
  35:        0x106da76c9 - objc_exception::try_no_ret::try_objc_execute_closure::h1b3e62b4774176a9
  36:        0x1070c38c2 - _RustObjCExceptionTryCatch
  37:        0x106db6cad - objc::message::platform::send_unverified::hb74bd746ecde604a
  38:        0x106cba1e9 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::h44acce1761be1b7b
  39:        0x106d69bd3 - tao::event_loop::EventLoop<T>::run::heee933efdc567a5e
  40:        0x106d8648c - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::hccc8ac067e3bfb25
  41:        0x106e6db40 - caido::main::hd646ea77b7c01976
  42:        0x106cf3476 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e5cd686432cede4
  43:        0x106d9a36c - std::rt::lang_start::{{closure}}::hc26c3dba13a584b3
  44:        0x10721abae - std::rt::lang_start_internal::ha5deaf08dab8765b
  45:        0x106e705ff - _main
  46:     0x7ff806d2b310 - <unknown>
```

### Platform and versions

- Intel mac, Ventura 13.1 (22C65)
- tauri: 1.2.0

### Additional context

Original issue: https://github.com/caido/caido/issues/345

**Comment by dolsup** [comment]
I am also experiencing the same issue on my M1 mac, macOS Monterey. The stack backtrace is identical. 
It can easily be reproduced by just holding down the ESC key for a while.

**Comment by Sytten** [comment]
I got also a different stack trace:
```
2023-05-11 09:37:25.371 Caido[7541:106674] *** Assertion failure in -[NSEvent keyCode], NSEvent.m:3185
thread 'main' panicked at 'Uncaught exception <NSException: 0x7fe822cc8120>', /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/event.rs:338:12
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: tao::platform_impl::platform::event::get_scancode
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/event.rs:338:12
   4: tao::platform_impl::platform::event::create_key_event
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/event.rs:140:18
   5: tao::platform_impl::platform::view::cancel_operation
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/view.rs:892:16
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <() as objc::message::MessageArguments>::invoke
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  29: objc::message::platform::send_unverified::{{closure}}
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  30: objc_exception::try::{{closure}}
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:68:31
  31: objc_exception::try_no_ret::try_objc_execute_closure
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:34:9
  32: RustObjCExceptionTryCatch
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/extern/exception.m:10:9
  33: objc_exception::try_no_ret
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:44:19
  34: objc_exception::try
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:67:9
  35: objc::exception::try
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/exception.rs:8:5
  36: objc::message::platform::send_unverified
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:26:5
  37: objc::message::send_message
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  38: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/event_loop.rs:188:16
  39: tao::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/platform_impl/macos/event_loop.rs:155:21
  40: tao::event_loop::EventLoop<T>::run
             at /Users/Sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.3/src/event_loop.rs:179:5
  41: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run
             at /Users/Sytten/.cargo/git/checkouts/dependency-tauri-987ac6e2d82e2314/f73dc64/core/tauri-runtime-wry/src/lib.rs:2129:5
  42: tauri::app::App<R>::run
             at /Users/Sytten/.cargo/git/checkouts/dependency-tauri-987ac6e2d82e2314/f73dc64/core/tauri/src/app.rs:832:5
  43: caido::main
             at ./src/main.rs:61:5
  44: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
```

**Comment by Sytten** [comment]
We traced the issue to the fact that if you maintain the ESC and do a mouse activity, it triggers an event that is non-keyboard event so if you call `keyCode` on it will send an exception as said in the doc: https://developer.apple.com/documentation/appkit/nsevent/1534513-keycode

**Comment by Sytten** [comment]
Further observations:
- Gecko flat out decided to not handle the `cancelOperation `(https://hg.mozilla.org/mozilla-central/log/tip/widget/cocoa/nsCocoaWindow.mm?patch=&linerange=3570:3572) and supposedly that prevents webkit from stealing the `CMD+.`
- The assumptions of that code are now wrong because since sierra `ESC` also maps to `cancelOperation` but the code seems to assume its only `CMD+.` (the referenced eclipse code is 2010, pre-sierra)

**Comment by Sytten** [comment]
Continuing digging, it looks like the most recent version of tao changed something so that now `ESC` is handled by the on-key down and not the `cancelOperation`. This most likely fixes the issue but I am unsure what the exact change was, maybe the `do_command_by_selector` inner code removal. The following snippet was also removed in on key down:
```
unsafe {
    let responder: id = msg_send![this, nextResponder];
    if !responder.is_null() {
      let () = msg_send![responder, doCommandBySelector: command];
    }
  }
```
But this only remove the bip sound the OS makes when invalid key is pressed.

**Comment by Sytten** [comment]
So I updated tao to 0.15.8 and wry to 0.22.6 and the issue is gone. So I expect this is due to the fact that the `cancel_operation` is not called. I can't reproduce the bug with pressing `CMD+.` and trying to do other mouse events.
Still we should probably add a bit of protection code just to make sure it doesn't come back since it looks like it was a side effect of another piece of code. Most likely in the `NSResponder` chain if you don't handle the event on key down it might fall back to a cancel operation.

**Comment by Sytten** [comment]
To reproduce the issue use tao 0.15.3 and wry 0.22.0, it might affect other versions but those versions are known to not be working.
EDIT: It looks like in 0.15.3 the **empty** `do_command_by_selector` was not present, so this was likely the bug. It must be kept otherwise the bug will re-appear.

**Comment by Sytten** [comment]
The more I dig around it, it does look like having an empty `doCommandBySelector` (https://developer.apple.com/documentation/appkit/nstextinput/1412853-docommandbyselector) is in fact a hack since it will block the command from being forwarded to the responder chain so the `ESC` will be treated only as a key down.
It's interesting choice since that means that tao doesn't deal with the quit event anymore (CMD+Q doesn't work on the tao examples), but wry does. This should really be documented in the code otherwise someone is bound to remove that empty method in the future by accident.

**Comment by wusyong** [comment]
Is there a reproduction step for this? Or a single blank tauri window will trigger it?

**Comment by Sytten** [comment]
A blank tauri page should trigger it if you have the right tao and wry versions.
Though we kinda know why this happens, so mostly I would suggest removing the commented code in tao here https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/view.rs#L578-L612 and add a comment to the effect of what I said in my comment above (https://github.com/tauri-apps/tauri/issues/6082#issuecomment-1544324800)

**Comment by Sytten** [comment]
@wusyong It seems like all shutcuts are broken in release mode, dev is working
https://github.com/tauri-apps/tauri/issues/5669
