### ISSUE TITLE
tauri runner loads html from filesystem instead of asset when embeddedServer is not active

### ISSUE THREAD

**Issue by spacemeowx2** [tauri-apps/tauri#633]
**Describe the bug**
https://github.com/tauri-apps/tauri/blob/7a1a3d60d9fa0859b2d36169e18e4bfda3565cec/tauri/src/app/runner.rs#L80-L85

tauri runner loads html from filesystem instead of asset when `embeddedServer` is not active

**To Reproduce**
1. Make a hello world tauri project
2. Set `tauri.embeddedServer.active` to `false`
3. `yarn tauri build`
4. Remove or rename `../dist/index.tauri.html`
5. Click `app.exe`, the there is nothing happend. If build with `--debug` you will see a panic:

```
thread 'main' panicked at 'Failed to build webview: Error(Io(Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。(File not found)" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src\libcore\result.rs:1188:5
```

**Expected behavior**
tauri should load html from packed asset like what embedded server did

https://github.com/tauri-apps/tauri/blob/7a1a3d60d9fa0859b2d36169e18e4bfda3565cec/tauri/src/app/runner.rs#L138

**Platform and Versions (please complete the following information):**

```
[tauri]: running info

Operating System - Windows_NT(10.0.19041) - win32/x64

Node.js environment
  Node.js - 13.11.0
  tauri.js - 0.6.2

Rust environment
  rustc - 1.41.1
  cargo - 1.41.0
  tauri-bundler - 0.6.0

Global packages
  NPM - 6.14.2
  yarn - 1.22.4

App directory structure
/.cache
/.git
/dist
/node_modules
/src
/src-tauri

App
  tauri - 0.5
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000
```

**Additional context**

**Stack Trace**
```
thread 'main' panicked at 'Failed to build webview: Error(Io(Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\backtrace-0.3.48\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized<closure-0>
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\backtrace-0.3.48\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<closure-0>
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\backtrace-0.3.48\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\backtrace-0.3.48\src\capture.rs:164
   4: backtrace::capture::Backtrace::new_unresolved
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\backtrace-0.3.48\src\capture.rs:158
   5: error_chain::backtrace::imp::InternalBacktrace::new
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\error-chain-0.12.2\src\backtrace.rs:56
   6: error_chain::{{impl}}::default
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\error-chain-0.12.2\src\lib.rs:687
   7: tauri::Error::from_kind
             at <::error_chain::error_chain::impl_error_chain_processed macros>:96
   8: tauri::{{impl}}::from
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-0.5.2\src\lib.rs:29
   9: tauri::app::runner::setup_content
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-0.5.2\src\app\runner.rs:84
  10: tauri::app::runner::run
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-0.5.2\src\app\runner.rs:17
  11: tauri::app::App::run
             at C:\Users\space\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-0.5.2\src\app.rs:16

...
```

**Comment by lucasfernog** [comment]
This has been wrong for so long, thanks for catching it!

**Comment by spacemeowx2** [comment]
Reopen this since this issue is still there on v0.5.3

#632 

https://github.com/tauri-apps/tauri/pull/632/files#diff-40bea23f5108bd99afc8e8285d342b21R96-R105
