### ISSUE TITLE
[bug] `CoInitializeEx` called when the documentation says it shouldn't be

### ISSUE THREAD

**Issue by stephen-h-d** [tauri-apps/tauri#6485]
### Describe the bug

The `tao` library calls `CoInitializeEx` called with a value of `COINIT_APARTMENTTHREADED` when the documentation says it shouldn't be.  The documentation in `tao` for the `fn with_drag_and_drop(self, flag: bool) -> WindowBuilder` function says "If you need COM API with `COINIT_MULTITHREADED` you must initialize it before calling any tao functions.".  Yet when the window configuration has `fileDropEnabled` set to false, and `CoInitializeEx` has already been called with a value of `COINIT_MULTITHREADED`,  `CoInitializeEx` called with a value of `COINIT_APARTMENTTHREADED`, causing a panic.  

### Reproduction

Write this main function in a Tauri app:

```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

use windows::{
    Win32::{
        System::{Com::*},
    },
};

fn main() {
    unsafe {
        match CoInitializeEx(None, COINIT_MULTITHREADED) {
            Ok(()) => { println!("initialized.") }
            Err(_) => { panic!("Failed to initialize") }
        }

        tauri::Builder::default()
            .invoke_handler(tauri::generate_handler![greet])
            .run(tauri::generate_context!())
            .expect("error while running tauri application");
    }
}

```

Modify `tauri.conf.json` to have a `fileDropEnabled` value of false, like so:

```json
...
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "example-com-init-issue",
        "width": 800,
        "height": 600,
        "fileDropEnabled": false
      }
    ]
...
```

I can provide a link to a full repo if needed.

### Expected behavior

I expect when when the window configuration has `fileDropEnabled` set to false, the Tauri app should be able to start and either not call  `CoInitializeEx` or, possibly, call it with a value of  `COINIT_MULTITHREADED` (though I am not sure if that will still cause a panic).

### Platform and versions

```text
$ cargo tauri info

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 110.0.1587.69
  › MSVC:
      - Visual Studio Build Tools 2019
      - Visual Studio Build Tools 2022
  › Node.js: 18.15.0
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ .git
  ├─ .idea
  ├─ .vscode
  ├─ src
  ├─ src-tauri
  └─ ui
```

### Stack trace

```text
thread 'main' panicked at 'error while running tauri application: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80010106, message: Cannot change thread mode after it is set. }))))', src\main.rs:26:14
stack backtrace:
   0:     0x7ff75551e522 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff75551e522 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff75551e522 - std::sys_common::backtrace::_print_fmt
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff75551e522 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff75553cbab - core::fmt::write
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\fmt\mod.rs:1213
   5:     0x7ff75551982a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\io\mod.rs:1682
   6:     0x7ff75551e26b - std::sys_common::backtrace::_print
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff75551e26b - std::sys_common::backtrace::print
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff755520e79 - std::panicking::default_hook::closure$1
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:267
   9:     0x7ff755520afb - std::panicking::default_hook
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:286
  10:     0x7ff755521710 - std::panicking::rust_panic_with_hook
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:688
  11:     0x7ff75552149e - std::panicking::begin_panic_handler::closure$0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:579
  12:     0x7ff75551f21f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\sys_common\backtrace.rs:137
  13:     0x7ff755521150 - std::panicking::begin_panic_handler
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:575
  14:     0x7ff755547205 - core::panicking::panic_fmt
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\panicking.rs:64
  15:     0x7ff755547726 - core::result::unwrap_failed
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\result.rs:1790
  16:     0x7ff754ed7bab - enum2$<core::result::Result<tuple$<>,enum2$<tauri::error::Error> > >::expect<tuple$<>,enum2$<tauri::error::Error> >
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\core\src\result.rs:1069
  17:     0x7ff754ef7cb4 - example_com_init_issue::main
                               at C:\Users\holden\repos\example-com-init-issue\src-tauri\src\main.rs:23
  18:     0x7ff754ec688b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\core\src\ops\function.rs:250
  19:     0x7ff754f7937e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\std\src\sys_common\backtrace.rs:121
  20:     0x7ff754f7937e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\std\src\sys_common\backtrace.rs:121
  21:     0x7ff754f65a01 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\std\src\rt.rs:166
  22:     0x7ff755513cae - core::ops::function::impls::impl$2::call_once
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\ops\function.rs:287
  23:     0x7ff755513cae - std::panicking::try::do_call
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:483
  24:     0x7ff755513cae - std::panicking::try
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:447
  25:     0x7ff755513cae - std::panic::catch_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panic.rs:140
  26:     0x7ff755513cae - std::rt::lang_start_internal::closure$2
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\rt.rs:148
  27:     0x7ff755513cae - std::panicking::try::do_call
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:483
  28:     0x7ff755513cae - std::panicking::try
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:447
  29:     0x7ff755513cae - std::panic::catch_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panic.rs:140
  30:     0x7ff755513cae - std::rt::lang_start_internal
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\rt.rs:148
  31:     0x7ff754f659da - std::rt::lang_start<tuple$<> >
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\std\src\rt.rs:165
  32:     0x7ff754ef8b39 - main
  33:     0x7ff755544c0c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  34:     0x7ff755544c0c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  35:     0x7ffd92407614 - BaseThreadInitThunk
  36:     0x7ffd937426a1 - RtlUserThreadStart
```

### Additional context

Original Discord conversation:

https://discordapp.com/channels/616186924390023171/1086022637504966656/1086022637504966656

**Comment by amrbashir** [comment]
A bit of bad news, I tracked this down to WebView2 APIs itself specifically the `CreateCoreWebView2Environment` API, seems like it is calling `CoInitializeEx` with `COINIT_APARTMENTTHREADED`. I can't confirm since webview2 is closed source but as far as my tracing went, it failed at this API call. Looks like you can't initialize COM on the current thread with `COINIT_MULTITHREADED`, so your only option is probably use `std::thread::spawn` and initialize COM there with `COINIT_MULTITHREADED`. and If you really need it to be on the same thread, feel free to open a bug report at https://github.com/MicrosoftEdge/WebView2Feedback repo

**Comment by Vlad-Shcherbina** [comment]
Thank you. The workaround with moving the thing that calls `CoInitializeEx(COINIT_MULTITHREADED)` to a separate thread appears to work.
