### ISSUE TITLE
[bug] tauri-driver errors when trying .click(), .setValue()

### ISSUE THREAD

**Issue by Sheap** [tauri-apps/tauri#6541]
### Describe the bug

When trying to use webdriver.io for e2e testing, many basic functions do not work, and simply return `Request failed with status 500 due to unsupported operation: unknown error`

There are workarounds (using `browser.execute`, but having to manually replace these basic functions is tedious, and they are not exactly the same behaviourally.

### Reproduction

1. extend [hello_tauri](https://github.com/chippers/hello_tauri) with a button which changes it's contents on click:
```html
    <script type="text/javascript">
        function handleClick() {
            document.getElementById("click-test").innerHTML = "Thank you"
        }
    </script>
...
    <button id="click-test" onClick="handleClick()">Click me</button>
```
2. Add a test for this button:
```javascript
  it("should click button", async () => {
    const button = await $("#click-test");
    await button.waitForClickable();
    await button.click();
    expect(button.getText()).toMatch("Thank you");
  });
```

### Expected behavior

The test should pass

### Platform and versions

```text
Environment
  › OS: Fedora 37 X64
  › Node.js: 18.14.2
  › npm: 9.5.0
  › pnpm: 7.27.0
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.3,
  › tauri-build [RUST]: 1.0.0-rc.3,
  › tao [RUST]: 0.6.2,
  › wry [RUST]: 0.13.2,

App
  › build-type: build
  › CSP: unset
  › distDir: dist
  › devPath: dist

App directory structure
  ├─ selenium
  ├─ webdriverio
  └─ node_modules
```

### Stack trace

```text
[0-0] 2023-03-24T08:12:25.996Z INFO webdriver: RESULT true
[0-0] 2023-03-24T08:12:25.996Z INFO webdriver: COMMAND elementClick("node-2E82D59D-A27A-4CAD-AE82-37C8E442F334")
[0-0] 2023-03-24T08:12:25.997Z INFO webdriver: [POST] http://127.0.0.1:4444/session/5194703d-38d0-477a-ae51-a9495d5fa0cd/element/node-2E82D59D-A27A-4CAD-AE82-37C8E442F334/click
[0-0] 2023-03-24T08:12:26.001Z WARN webdriver: Request failed with status 500 due to unknown error
[0-0] 2023-03-24T08:12:26.001Z INFO webdriver: Retrying 1/3
[0-0] 2023-03-24T08:12:26.001Z INFO webdriver: [POST] http://127.0.0.1:4444/session/5194703d-38d0-477a-ae51-a9495d5fa0cd/element/node-2E82D59D-A27A-4CAD-AE82-37C8E442F334/click
[0-0] 2023-03-24T08:12:26.044Z WARN webdriver: Request failed with status 500 due to unknown error
[0-0] 2023-03-24T08:12:26.044Z INFO webdriver: Retrying 2/3
[0-0] 2023-03-24T08:12:26.044Z INFO webdriver: [POST] http://127.0.0.1:4444/session/5194703d-38d0-477a-ae51-a9495d5fa0cd/element/node-2E82D59D-A27A-4CAD-AE82-37C8E442F334/click
[0-0] 2023-03-24T08:12:26.048Z WARN webdriver: Request failed with status 500 due to unknown error
[0-0] 2023-03-24T08:12:26.048Z INFO webdriver: Retrying 3/3
[0-0] 2023-03-24T08:12:26.048Z INFO webdriver: [POST] http://127.0.0.1:4444/session/5194703d-38d0-477a-ae51-a9495d5fa0cd/element/node-2E82D59D-A27A-4CAD-AE82-37C8E442F334/click
[0-0] 2023-03-24T08:12:26.093Z ERROR webdriver: Request failed with status 500 due to unsupported operation: unknown error
[0-0] unsupported operation in "Hello Tauri should click button"
unsupported operation: unknown error
    at Object.getErrorFromResponseBody (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/webdriver/build/utils.js:189:12)
    at NodeJSRequest._request (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/webdriver/build/request/index.js:157:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
    at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
    at async Element.elementErrorHandlerCallbackFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/runner/node_modules/webdriverio/build/middlewares.js:23:32)
    at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
    at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
    at async Element.elementErrorHandlerCallbackFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/runner/node_modules/webdriverio/build/middlewares.js:23:32)
    at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
[0-0] 2023-03-24T08:12:26.095Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-03-24T08:12:26.095Z INFO webdriver: [DELETE] http://127.0.0.1:4444/session/5194703d-38d0-477a-ae51-a9495d5fa0cd
[0-0] FAILED in undefined - /test/specs/example.e2e.js
2023-03-24T08:12:26.214Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[wry 0.13.2 linux #0-0] Running: wry (v0.13.2) on linux
[wry 0.13.2 linux #0-0] Session ID: 5194703d-38d0-477a-ae51-a9495d5fa0cd
[wry 0.13.2 linux #0-0]
[wry 0.13.2 linux #0-0] » /test/specs/example.e2e.js
[wry 0.13.2 linux #0-0] Hello Tauri
[wry 0.13.2 linux #0-0]    ✓ should be cordial
[wry 0.13.2 linux #0-0]    ✓ should be excited
[wry 0.13.2 linux #0-0]    ✓ should be easy on the eyes
[wry 0.13.2 linux #0-0]    ✖ should click button
[wry 0.13.2 linux #0-0]
[wry 0.13.2 linux #0-0] 3 passing (460ms)
[wry 0.13.2 linux #0-0] 1 failing
[wry 0.13.2 linux #0-0]
[wry 0.13.2 linux #0-0] 1) Hello Tauri should click button
[wry 0.13.2 linux #0-0] unknown error
[wry 0.13.2 linux #0-0] unsupported operation: unknown error
[wry 0.13.2 linux #0-0]     at Object.getErrorFromResponseBody (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/webdriver/build/utils.js:189:12)
[wry 0.13.2 linux #0-0]     at NodeJSRequest._request (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/webdriver/build/request/index.js:157:31)
[wry 0.13.2 linux #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[wry 0.13.2 linux #0-0]     at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
[wry 0.13.2 linux #0-0]     at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
[wry 0.13.2 linux #0-0]     at async Element.elementErrorHandlerCallbackFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/runner/node_modules/webdriverio/build
/middlewares.js:23:32)
[wry 0.13.2 linux #0-0]     at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
[wry 0.13.2 linux #0-0]     at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
[wry 0.13.2 linux #0-0]     at async Element.elementErrorHandlerCallbackFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/runner/node_modules/webdriverio/build
/middlewares.js:23:32)
[wry 0.13.2 linux #0-0]     at async Element.wrapCommandFn (/home/stuart/motius-projects/aumovis/hello_tauri/webdriver/node_modules/@wdio/utils/build/shim.js:103:29)
```

### Additional context

.setValue() had similar issues for me, and the workaround (at least in a svelte app) were more complicated, as you also need to get events to fire properly. I used click as the example here as it is simpler.

For others having trouble with this issue, here are my current workarounds:
## click
```typescript
async function findAndClick (selector: string, timeout?: number) {
  const button = await $(selector);
  await button.waitForClickable({
    timeout,
  });
  await browser.execute('arguments[0].click();', button);
}
```

## setValue
```typescript
async function setValue (selector: string, value: number | string) {
  const field = await $(selector);
  await browser.execute(`arguments[0].value="${value}"`, field);
  await browser.execute('arguments[0].dispatchEvent(new Event("input", { bubbles: true }))', field);
}
```

**Comment by Sheap** [comment]
Note: I'm not 100% sure I understand the boundary here between webdriver and tauri-driver. I suspect this issue is on the tauri driver end, as the error is coming back from the http request to the tauri-driver port. I can recreate it by making the same request directly using postman, but perhaps the request itself is incorrect.

**Comment by AlexTMjugador** [comment]
I can reproduce this issue too.

After some investigation, I came up with the conclusions that, in WebDriver spec parlance, `tauri-driver` is just an [intermediary node](https://w3c.github.io/webdriver/#dfn-intermediary-nodes) (i.e., proxy) that launches the corresponding OS webview driver binary listening on a non-default port, and then forwards messages as-is to such driver, only mangling [capabilities](https://w3c.github.io/webdriver/#capabilities) to be driver-neutral. On Linux, it launches the WebKit GTK driver (`WebKitWebDriver`), while on Windows it launches the MS Edge driver (`msedgedriver.exe`).

The issue at hand is **not** caused due to `tauri-driver`'s interference: I've confirmed using Wireshark that the affected requests are responses are passed verbatim to the underlying driver. In other words, the issue would happen even if Webdriver IO used the underlying driver directly.

My best guess about the root cause of the issue is that some Wry security feature or incompatibility is preventing the WebKit driver from doing its work. Given that E2E testing is a pretty advanced topic that doesn't tend to get much developer attention, it's likely that the driver stopped working at some point but almost nobody noticed. I'll update this comment if I get to dig further into this.

**Comment by chippers** [comment]
Adding e2e tests is something we as a team have discussed before, but have not implemented. I think it would be really valuable, but we are also cautious of requiring non-rust things to build the repo. This is why many examples are ignored. I think having a separate process for e2e would be perfectly fine, but requires maintenance.

Thank you @AlexTMjugador for the writeup, it's quite accurate. If you are interested in joining the working group, reach out on discord and I can help with that

**Comment by amosjyng** [comment]
I've just encountered this myself as well. Thank you for the workaround @Sheap , you just saved me a lot of time with the `bubbles: true` trick :P

**Comment by srsholmes** [comment]
If you're still hitting these issues with tauri-driver — I took a different approach and built a Playwright plugin for Tauri that bypasses tauri-driver entirely. It injects a socket server via a Rust plugin and executes commands directly in the webview with auto-waiting built in.

https://github.com/srsholmes/tauri-playwright

Might save some headaches for those who need reliable click/fill/setValue in their E2E tests.

**Comment by jwatt** [comment]
This issue essentially occurs because distros build the webkit lib twice, once to build a GTK3 lib and once to build a GTK4 lib, but they only want to install one `WebKitWebDriver` binary. As a result they make a choice about which of the builds should create that binary, doing that by building only one of the libs with `-DENABLE_WEBDRIVER=ON`. However, an unfortunate side effect of this decision is that some of the functionality for the REST API is missing from  the "other" lib, and anything linking against that version can't fully be driven by the `WebKitWebDriver` binary.

For this issue specifically it's relevant that `wry` is built against GTK3 (there's an open issue to [port it to GTK4/WebKit6](https://github.com/tauri-apps/wry/issues/1474)), so `wry` links against webkit2gtk4.1 (GTK3) rather than webkitgtk6.0 (GTK4).

On Fedora:
- webkit2gtk4.1 is built with `-DENABLE_WEBDRIVER=OFF`, per the [spec file](https://src.fedoraproject.org/rpms/webkitgtk/raw/rawhide/f/webkitgtk.spec) (webkitgtk6.0 is not, so [defaults to ENABLE_WEBDRIVER=ON](https://github.com/WebKit/WebKit/blob/7acdf5e11af175e98cf7dcfcbcfcde11a50bc6ce/Source/cmake/OptionsGTK.cmake#L108) instead)
- because `ENABLE_WEBDRIVER` is not turned on for webkit2gtk4.1, `ENABLE_WEBDRIVER_MOUSE_INTERACTIONS` etc. are also [not turned on by default](https://github.com/WebKit/WebKit/blob/7acdf5e11af175e98cf7dcfcbcfcde11a50bc6ce/Source/cmake/OptionsGTK.cmake#L293-L298)
- because `ENABLE_WEBDRIVER_MOUSE_INTERACTIONS` is not turned on, [WebAutomationSession::performMouseInteraction fails](https://github.com/WebKit/WebKit/blob/7acdf5e11af175e98cf7dcfcbcfcde11a50bc6ce/Source/WebKit/UIProcess/Automation/WebAutomationSession.cpp#L2355-L2360) with `NotImplemented`
- the [WebDriver code](https://github.com/WebKit/WebKit/blob/7acdf5e11af175e98cf7dcfcbcfcde11a50bc6ce/Source/WebDriver/CommandResult.cpp#L91-L92) then converts `NotImplemented` to the "unsupported operation" error reported via the REST API

On Ubuntu/Debian this issue does NOT occur because:
- they [make the opposite choice](https://git.launchpad.net/ubuntu/+source/webkit2gtk/tree/debian/rules?h=ubuntu/noble&id=5256c46cce55f4d6aeff2a711f04409ff3ffaf72#n209) regarding which lib is built with `ENABLE_WEBDRIVER=ON`
- so `WebKitWebDriver` is built from the GTK3 build
- as a side effect the GTK3 lib is the one that gets `ENABLE_WEBDRIVER_MOUSE_INTERACTIONS` etc. turned on
- and this issue doesn't occur

Possible solution:

Distros could potentially build whichever of the two libs is NOT built with `-DENABLE_WEBDRIVER=ON` with the individual `ENABLE_WEBDRIVER_*_INTERACTIONS` defines turned on instead:

```
-DENABLE_WEBDRIVER_MOUSE_INTERACTIONS=ON \
-DENABLE_WEBDRIVER_KEYBOARD_INTERACTIONS=ON \
-DENABLE_WEBDRIVER_WHEEL_INTERACTIONS=ON
```

**Comment by jwatt** [comment]
Filed upstream https://bugzilla.redhat.com/show_bug.cgi?id=2493782

**Comment by jwatt** [comment]
Re-filed even further upstream as [WebKit issue 318171](https://bugs.webkit.org/show_bug.cgi?id=318171), then the [fix by Michael Catanzaro](https://github.com/WebKit/WebKit/pull/72161) landed on `main` a couple of days ago. That fix was [backported to `webkitglib/2.54`](https://github.com/WebKit/WebKit/pull/72161#issuecomment-5653009415).
