### ISSUE TITLE
[bug] `tauri ios dev` fails to build a project

### ISSUE THREAD

**Issue by lok52** [tauri-apps/tauri#6545]
### Describe the bug

When I run `yarn tauri ios dev` frontend development server starts successfully, but rust build fails with `unable to load standard library for target 'x86_64-apple-ios13.0-simulator'`.

### Reproduction

1. Run `yarn create tauri-app` with any UI framework (`svelte` in my case)
2. Run `yarn`
3. Run `yarn tauri ios init`
4. Run `yarn tauri ios dev`

### Expected behavior

Normal development build launch in a simulator.

### Platform and versions

```text
Environment
  › OS: Mac OS 13.2.1 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.1
  › cargo: 1.68.1
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.4
  › @tauri-apps/api [NPM]: 2.0.0-alpha.1
  › tauri [RUST]: 2.0.0-alpha.4,
  › tauri-build [RUST]: 2.0.0-alpha.2,
  › tao [RUST]: 0.18.3,
  › wry [RUST]: 0.27.1,
```
```


### Stack trace

```text
error: failed to run custom build command for `tauri v2.0.0-alpha.4`

Caused by:
  process didn't exit successfully: `/Users/leonidtyurin/projects/tauri-prover-bench/src-tauri/target/debug/build/tauri-d29f8b8006393424/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=dev
  cargo:rustc-cfg=mobile
  cargo:rustc-cfg=shell_open
  cargo:rustc-cfg=shell_any
  cargo:rustc-cfg=shell_scope
  cargo:rustc-link-search=native=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator
  cargo:rustc-link-search=native=/usr/lib/swift
  cargo:rustc-link-lib=clang_rt.ios
  cargo:rustc-link-search=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/lib/darwin
  [0/1] Planning build
  Building for debugging...
  warning: inferring simulator environment for target 'x86_64-apple-ios13.0'; use '-target x86_64-apple-ios13.0-simulator' insteaderror: emit-module command failed with exit code 1 (use -v to see invocation)[1/3] Emitting module SwiftRs
  <unknown>:0: error: unable to load standard library for target 'x86_64-apple-ios13.0-simulator'
  [2/3] Compiling SwiftRs lib.swift
  <unknown>:0: error: unable to load standard library for target 'x86_64-apple-ios13.0-simulator'

  --- stderr
  thread 'main' panicked at 'Failed to compile swift package Tauri', /Users/leonidtyurin/.cargo/registry/src/github.com-1ecc6299db9ec823/swift-rs-1.0.3/src-rs/build.rs:270:17
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
     2: swift_rs::build::SwiftLinker::link
               at /Users/leonidtyurin/.cargo/registry/src/github.com-1ecc6299db9ec823/swift-rs-1.0.3/src-rs/build.rs:270:17
     3: tauri_build::mobile::link_swift_library
               at /Users/leonidtyurin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-2.0.0-alpha.2/src/mobile.rs:106:3
     4: build_script_build::main
               at /Users/leonidtyurin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-2.0.0-alpha.4/build.rs:186:7
     5: core::ops::function::FnOnce::call_once
               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
       Error [tauri_cli_node] Failed to run `cargo build`: Command "cargo build --package tauri-prover-bench --manifest-path /Users/leonidtyurin/projects/tauri-prover-bench/src-tauri/Cargo.toml --target x86_64-apple-ios --no-default-features --color always" didn't complete successfully, exiting with code 101.

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Build\ Rust\ Code /Users/leonidtyurin/Library/Developer/Xcode/DerivedData/tauri-prover-bench-busjdhrundcxalbdqvdqdicgdcxn/Build/Intermediates.noindex/tauri-prover-bench.build/debug-iphonesimulator/tauri-prover-bench_iOS.build/Script-E5206DFCD1D7CE996BA29651.sh (in target 'tauri-prover-bench_iOS' from project 'tauri-prover-bench')
(1 failure)
       Error command ["xcodebuild"] exited with code 65
```
```


### Additional context

This error started to appear after upgrading tauri from version `2.0.0-alpha.3` to `2.0.0-alpha.4`

**Comment by elliotwaite** [comment]
I'm getting the same error.

**Comment by lok52** [comment]
Discussion for this issue: https://github.com/Brendonovich/swift-rs/issues/42. Very much waiting for next Tauri update to include this fix.

**Comment by DaAitch** [comment]
Mac x86 here, `npm run tauri ios dev` works, **but I'm using a device**.

I get the same error w/o device: `<unknown>:0: error: unable to load standard library for target 'x86_64-apple-ios13.0-simulator'` although I selected iPhone 11 Pro Max iOS 14.5.

**Comment by lok52** [comment]
> Mac x86 here, `npm run tauri ios dev` works, **but I'm using a device**.
> 
> I get the same error w/o device: `<unknown>:0: error: unable to load standard library for target 'x86_64-apple-ios13.0-simulator'` although I selected iPhone 11 Pro Max iOS 14.5.

Yeah, this error appears only when you try to use a simulator, because currently used `swift-rs` version incorrectly infers simulator SDK path.

**Comment by lucasfernog** [comment]
The fix was released in swift-rs, just run `cargo update -p swift-rs` in the `src-tauri` folder.

**Comment by Horsty80** [comment]
> The fix was released in swift-rs, just run `cargo update -p swift-rs` in the `src-tauri` folder.

I confirm, same error, and `cargo update -p swift-rs` inside `src-tauri` solved this issue
