### ISSUE TITLE
[bug] Android application built in release mode crashes at startup

### ISSUE THREAD

**Issue by fibremint** [tauri-apps/tauri#6560]
### Describe the bug

After updating Tauri from `2.0.0-alpha.2` to `2.0.0-alpha.4`, there is a problem that Android application built in release mode crashes at startup.

And while checking the crash logs through `logcat`, I was able to catch the error messages when creating the `TauriActivity`.
```
03-25 22:53:23.629 20855 20855 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.fibremint.app.TauriActivity.y(com.fibremint.app.TauriActivity) (tried Java_com_fibremint_app_TauriActivity_y and Java_com_fibremint_app_TauriActivity_y__Lcom_fibremint_app_TauriActivity_2)
03-25 22:53:23.629 20855 20855 E AndroidRuntime:        at com.fibremint.app.TauriActivity.y(Native Method)
03-25 22:53:23.629 20855 20855 E AndroidRuntime:        at com.fibremint.app.TauriActivity.onCreate(SourceFile:4)
```

An error message showed that some method name in `TauriActivity` was truncated to `y` (probably it was `onDestroy` or `onLowMemory`?).

And while looking for the cause of the method's name being truncated, I found that the minimization of Kotlin code on `release` mode was introducesd in this Tauri `2.0.0-alpha.4`.

**./src-tauri/gen/android/app/app/proguard-tauri.pro**
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

-keep class com.fibremint.app.TauriActivity {
  getAppClass(...);
  getVersion();
}

-keep class com.fibremint.app.RustWebView {
  public <init>(...);
  loadUrlMainThread(...);
}

-keep class com.fibremint.app.Ipc {
  public <init>(...);
  @android.webkit.JavascriptInterface public <methods>;
}

-keep class com.fibremint.app.RustWebChromeClient,com.fibremint.app.RustWebViewClient {
  public <init>(...);
}

-keep class com.fibremint.app.MainActivity {
  public getPluginManager();
}

```

**./src-tauri/gen/android/app/app/build.gradle.kts**
```
android {
    // ...
    buildTypes {
        getByName("debug") {
            manifestPlaceholders["usesCleartextTraffic"] = "true"
            isDebuggable = true
            isJniDebuggable = true
            isMinifyEnabled = false
            packagingOptions {
                jniLibs.keepDebugSymbols.add("*/arm64-v8a/*.so")

                jniLibs.keepDebugSymbols.add("*/armeabi-v7a/*.so")

                jniLibs.keepDebugSymbols.add("*/x86/*.so")

                jniLibs.keepDebugSymbols.add("*/x86_64/*.so")
            }
        }
        getByName("release") {
            isMinifyEnabled = true
            val proguards = fileTree(".") {
              include("*.pro")
            }
        }
    }
    // ...
```

And by turning off code minimization, an issue of the crash was resolved.
```
getByName("release") {
    isMinifyEnabled = false
}
```

Therefore, I think the problem is caused by the auto-generated proguard file misses some sections, and it leads to truncation of method names on `TauriActivity`.

Related topics on Android docs:
- [Why didn't FindClass find my class?](https://developer.android.com/training/articles/perf-jni#faq:-why-didnt-findclass-find-my-class)
- [Customize which code to keep](https://developer.android.com/studio/build/shrink-code#keep-code)

### Reproduction

1. Update dependencies
```
$ yarn upgrade @tauri-apps/cli@next @tauri-apps/api@next
$ cargo add tauri@2.0.0-alpha.4
$ cargo add tauri-build@2.0.0-alpha.2 --build
$ cargo install tauri-cli --version "^2.0.0-alpha"
```
2. Initialize Android project
```
$ rm -r src-tauri/gen
$ tauri android init
```
3. Build Tauri Android application with release mode
```
$ yarn tauri android build
```
4. Sign created Tauri application apk with `apksigner`
5. Install apk to Android device

### Expected behavior

Tauri Android application built in release mode runs without crashes at startup.

### Platform and versions

```text
`$ yarn tauri info`

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 111.0.1661.51
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-gnu 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.4
  › @tauri-apps/api [NPM]: 2.0.0-alpha.1
  › tauri [RUST]: 2.0.0-alpha.4,
  › tauri-build [RUST]: 2.0.0-alpha.2,
  › tao [RUST]: 0.18.3,
  › wry [RUST]: 0.27.1,

App
  › build-type: bundle
  › CSP: style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; default-src 'self' customprotocol: asset:; img-src 'self' asset: https://asset.localhost blob: data:
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ assets-src
  ├─ dist
  ├─ isolation-dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```text
// adb logcat

03-25 22:53:23.629 20855 20855 E m.fibremint.app: No implementation found for void com.fibremint.app.TauriActivity.y(com.fibremint.app.TauriActivity) (tried Java_com_fibremint_app_TauriActivity_y and Java_com_fibremint_app_TauriActivity_y__Lcom_fibremint_app_TauriActivity_2)
03-25 22:53:23.629 20855 20855 E AndroidRuntime: Process: com.fibremint.app, PID: 20855
03-25 22:53:23.629 20855 20855 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.fibremint.app.TauriActivity.y(com.fibremint.app.TauriActivity) (tried Java_com_fibremint_app_TauriActivity_y and Java_com_fibremint_app_TauriActivity_y__Lcom_fibremint_app_TauriActivity_2)
03-25 22:53:23.629 20855 20855 E AndroidRuntime:        at com.fibremint.app.TauriActivity.y(Native Method)
03-25 22:53:23.629 20855 20855 E AndroidRuntime:        at com.fibremint.app.TauriActivity.onCreate(SourceFile:4)
03-25 22:53:23.639  1304  6427 W ActivityManager: crash : com.fibremint.app,10416
03-25 22:53:23.639  1304  6427 W ActivityTaskManager:   Force finishing activity com.fibremint.app/.MainActivity

```

**Comment by fibremint** [comment]
Tested and confirmed that issue was resolved with this **PR #6588**. Thanks for the contributions!
