### ISSUE TITLE
[bug] Android release flash back

### ISSUE THREAD

**Issue by silent-rain** [tauri-apps/tauri#6914]
## Android release flash back
Using the latest tauri v2.0.0-alpha. 8 version, the APK software package compiled from the cargo tauri Android build will flash when opened.

## Running Platform
- android studio AVD Pixel_6_API_33
- Mobile Android 13

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.38.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.71.0-nightly (2f2c438dc 2023-05-08)
    ✔ Cargo: 1.71.0-nightly (569b648b5 2023-05-05)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.20.0
    - yarn: 1.22.19
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.8
    - tauri-build [RUST]: 2.0.0-alpha.4
    - wry [RUST]: 0.27.3
    - tao [RUST]: 0.18.3
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.8

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../web/dist
    - devPath: http://localhost:5173/
```

### Stack trace

```text
--------- beginning of crash
05-09 08:23:18.903 30351 30351 E AndroidRuntime: FATAL EXCEPTION: main
05-09 08:23:18.903 30351 30351 E AndroidRuntime: Process: com.chatgpt.chat_gpt, PID: 30351
05-09 08:23:18.903 30351 30351 E AndroidRuntime: java.lang.NoSuchMethodError: no non-static method "Lcom/chatgpt/chat_gpt/RustWebView;.setAutoPlay(Z)V"
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:335)
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:183)
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-09 08:23:18.903 30351 30351 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Additional context

adb logcat -v color -s chat_gpt:D RustStdoutStderr：

--------- beginning of main
--------- beginning of kernel
--------- beginning of system
05-09 08:23:18.784 30351 30376 I RustStdoutStderr: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/com.chatgpt.chat_gpt/cache/We
bView/Crashpad: No such file or directory (2)
05-09 08:23:18.812 30351 30376 I RustStdoutStderr: [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
--------- beginning of crash

**Comment by amrbashir** [comment]
This is already fixed in the next release, for now you can disable minification for your release build in `gen/android/<app-name>/app/build.gradle.kts`
