### ISSUE TITLE
Failed to build AppImage

### ISSUE THREAD

**Issue by Fozei** [tauri-apps/tauri#7172]
### Describe the bug

Build Windwos exe and Linux deb success,but failed to build AppImage.I went through the existing issues about `error running appimage.sh`,but I did not find any one sames to mine. I already build with the --verbose param, and attatched the cli output. Thanks a lot.

### Platform and versions

```text
> family-tree@0.0.0 tauri /home/fozei/code/tauri/FamilyConnection
> tauri "info"


Environment
  › OS: Linux 20.9 X64
  › Node.js: 14.16.1
  › npm: 6.14.12
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ node_modules
  ├─ public
  ├─ src
  ├─ .vscode
  ├─ dist
  └─ docs
```

### Stack trace

```text
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/fozei/node/node-v14.16.1-linux-x64/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'run',
npm verb cli   'tauri',
npm verb cli   'build',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.12
npm info using node@v14.16.1
npm verb run-script [ 'pretauri', 'tauri', 'posttauri' ]
npm info lifecycle family-tree@0.0.0~pretauri: family-tree@0.0.0
npm info lifecycle family-tree@0.0.0~tauri: family-tree@0.0.0

> family-tree@0.0.0 tauri /home/fozei/code/tauri/FamilyConnection
> tauri "build"

     Running beforeBuildCommand `npm run build`
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/fozei/node/node-v14.16.1-linux-x64/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'run',
npm verb cli   'build'
npm verb cli ]
npm info using npm@6.14.12
npm info using node@v14.16.1
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle family-tree@0.0.0~prebuild: family-tree@0.0.0
npm info lifecycle family-tree@0.0.0~build: family-tree@0.0.0

> family-tree@0.0.0 build /home/fozei/code/tauri/FamilyConnection
> vite build

vite v4.1.4 building for production...
✓ 3727 modules transformed.
dist/index.html                        0.46 kB
dist/assets/image-365fbcfa.webp       29.07 kB
dist/assets/pattern-e682dec6.webp     48.65 kB
dist/assets/index-e6be3df1.css       601.36 kB │ gzip:  70.68 kB
dist/assets/index-143bc9b0.js      2,711.71 kB │ gzip: 988.26 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
npm verb lifecycle family-tree@0.0.0~build: unsafe-perm in lifecycle true
npm verb lifecycle family-tree@0.0.0~build: PATH: /home/fozei/node/node-v14.16.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fozei/code/tauri/FamilyConnection/node_modules/.bin:/home/fozei/node/node-v14.16.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fozei/code/tauri/FamilyConnection/node_modules/.bin:/home/fozei/.local/bin:/home/fozei/.cargo/bin:/home/fozei/flutter/flutter305/bin:/home/fozei/.local/bin:/data/home/fozei/jdk/jdk-11.0.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/home/fozei/Android/Sdk/tools:/home/fozei/Android/Sdk/platform-tools
npm verb lifecycle family-tree@0.0.0~build: CWD: /home/fozei/code/tauri/FamilyConnection
npm info lifecycle family-tree@0.0.0~postbuild: family-tree@0.0.0
npm verb exit [ 0, true ]
npm timing npm Completed in 24004ms
npm info ok 
   Compiling family-connection v0.0.0 (/home/fozei/code/tauri/FamilyConnection/src-tauri)
    Finished release [optimized] target(s) in 25.04s
    Bundling family-tree_0.0.0_amd64.deb (/home/fozei/code/tauri/FamilyConnection/src-tauri/target/release/bundle/deb/family-tree_0.0.0_amd64.deb)
    Bundling family-tree_0.0.0_amd64.AppImage (/home/fozei/code/tauri/FamilyConnection/src-tauri/target/release/bundle/appimage/family-tree_0.0.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /home/fozei/code/tauri/FamilyConnection/src-tauri/target/release/bundle/appimage/build_appimage.sh`
npm verb lifecycle family-tree@0.0.0~tauri: unsafe-perm in lifecycle true
npm verb lifecycle family-tree@0.0.0~tauri: PATH: /home/fozei/node/node-v14.16.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fozei/code/tauri/FamilyConnection/node_modules/.bin:/home/fozei/.local/bin:/home/fozei/.cargo/bin:/home/fozei/flutter/flutter305/bin:/home/fozei/.local/bin:/data/home/fozei/jdk/jdk-11.0.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/home/fozei/Android/Sdk/tools:/home/fozei/Android/Sdk/platform-tools
npm verb lifecycle family-tree@0.0.0~tauri: CWD: /home/fozei/code/tauri/FamilyConnection
npm info lifecycle family-tree@0.0.0~tauri: Failed to exec tauri script
npm verb stack Error: family-tree@0.0.0 tauri: `tauri "build"`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/fozei/node/node-v14.16.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/home/fozei/node/node-v14.16.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid family-tree@0.0.0
npm verb cwd /home/fozei/code/tauri/FamilyConnection
npm verb Linux 5.15.77-amd64-desktop
npm verb argv "/home/fozei/node/node-v14.16.1-linux-x64/bin/node" "/usr/bin/npm" "run" "tauri" "build" "--verbose"
npm verb node v14.16.1
npm verb npm  v6.14.12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! family-tree@0.0.0 tauri: `tauri "build"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the family-tree@0.0.0 tauri script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 52147ms
```

**Comment by FabianLars** [comment]
npm needs an extra `--` to forward the verbose flag to tauri, so could you run `npm run tauri build -- --verbose` and post the logs too please?

**Comment by Fozei** [comment]
> npm needs an extra `--` to forward the verbose flag to tauri, so could you run `npm run tauri build -- --verbose` and post the logs too please?

Thanks a lot,  after `npm run tauri build -- --verbose`   I think this issue is because my network condition that failed to download some dependences. Below is my cmd log,I well close this issue.

```
     Running [tauri_bundler::bundle::common] Command `/home/fozei/code/tauri/FamilyConnection/src-tauri/target/release/bundle/appimage/build_appimage.sh `
+ export ARCH=x86_64
+ ARCH=x86_64
+ APPIMAGE_BUNDLE_XDG_OPEN=1
+ APPIMAGE_BUNDLE_GSTREAMER=0
+ TRAY_LIBRARY_PATH=0
+ '[' x86_64 == i686 ']'
+ linuxdeploy_arch=x86_64
+ mkdir -p family-tree.AppDir
+ cp -r ../appimage_deb/data/usr family-tree.AppDir
+ cd family-tree.AppDir
+ mkdir -p usr/bin
+ mkdir -p usr/lib
+ [[ 1 != \0 ]]
+ [[ -f /usr/bin/xdg-open ]]
+ echo 'Copying /usr/bin/xdg-open'
+ cp /usr/bin/xdg-open usr/bin
Copying /usr/bin/xdg-open
+ [[ 0 != \0 ]]
++ dirname '{}'
+ find /usr/lib /usr/lib32 /usr/lib64 /usr/libexec /usr/libx32 -name WebKitNetworkProcess -exec mkdir -p . ';' -exec cp --parents '{}' . ';'
++ dirname '{}'
+ find /usr/lib /usr/lib32 /usr/lib64 /usr/libexec /usr/libx32 -name WebKitWebProcess -exec mkdir -p . ';' -exec cp --parents '{}' . ';'
++ dirname '{}'
+ find /usr/lib /usr/lib32 /usr/lib64 /usr/libexec /usr/libx32 -name libwebkit2gtkinjectedbundle.so -exec mkdir -p . ';' -exec cp --parents '{}' . ';'
+ cd /home/fozei/.cache/tauri
+ wget -q -4 -N https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
+ wget -q -4 -N https://github.com/AppImage/AppImageKit/releases/download/12/AppRun-x86_64
       Error [tauri_cli_node] failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /home/fozei/code/tauri/FamilyConnection/src-tauri/target/release/bundle/appimage/build_appimage.sh`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! family-tree@0.0.0 tauri: `tauri "build" "--verbose"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the family-tree@0.0.0 tauri script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fozei/.npm/_logs/2023-06-25T06_33_46_224Z-debug.log
```
