### ISSUE TITLE
[bug] can't run tauri ios dev command

### ISSUE THREAD

**Issue by fernandolguevara** [tauri-apps/tauri#7580]
### Describe the bug

can't run `cargo tauri ios dev` command

### Reproduction

- `git clone github.com/Adimac93/tauri-mobile-apple-ecosystem`
- `cargo tauri ios dev`

### Platform and versions

```text
macbook M1
tauri v2.0.0-alpha.10
```

### Stack trace

```text
error: failed to run custom build command for `tauri v2.0.0-alpha.10`

Caused by:
  process didn't exit successfully: `/Users/x/projects/x/src-tauri/target/debug/build/tauri-32f721b68658294a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=dev
  cargo:rustc-cfg=mobile

  --- stderr
  thread 'main' panicked at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.6/src-rs/build.rs:42:56:
  called `Result::unwrap()` on an `Err` value: Error("expected ident", line: 1, column: 2)
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/panicking.rs:617:5
     1: core::panicking::panic_fmt
               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/core/src/panicking.rs:67:14
     2: core::result::unwrap_failed
               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/core/src/result.rs:1652:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/core/src/result.rs:1077:23
     4: swift_rs::build::SwiftEnv::new
               at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.6/src-rs/build.rs:42:9
     5: swift_rs::build::SwiftLinker::link
               at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.6/src-rs/build.rs:215:25
     6: tauri_build::mobile::link_swift_library
               at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-build-2.0.0-alpha.6/src/mobile.rs:104:3
     7: build_script_build::main
               at ./build.rs:130:7
     8: core::ops::function::FnOnce::call_once
               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
       Error [tauri_cli] Failed to run `cargo build`: command ["cargo", "build", "--package", "template", "--manifest-path", "/Users/x/projects/x/src-tauri/Cargo.toml", "--target", "aarch64-apple-ios", "--features", "tauri/rustls-tls", "--lib", "--no-default-features"] exited with code 101
Command PhaseScriptExecution failed with a nonzero exit code

note: Run script build phase 'Build Rust Code' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'template_iOS' from project 'template')
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution Build\ Rust\ Code /Users/x/Library/Developer/Xcode/DerivedData/template-abtzuxdqpivxmgeyehbyindqgioh/Build/Intermediates.noindex/template.build/debug-iphoneos/template_iOS.build/Script-B0E8D7CC83E4566C98BEC8CE.sh (in target 'template_iOS' from project 'template')
(1 failure)
       Error command ["xcodebuild"] exited with code 65
```
```


### Additional context

_No response_

**Comment by pewsheen** [comment]
Looked into `swift-rs` [source code](https://github.com/Brendonovich/swift-rs/blob/b5ed223fcdab165bc21219c1925dc1e77e2bef5e/src-rs/build.rs#L42), it might be failed to parse the command:

```
swift -target aarch64-apple-ios -print-target-info
```

I think this should be `swift-rs`'s issue.
Could you provide the output from the command and your macOS and Xcode versions?
