### ISSUE TITLE
[bug] UnsupportedOperationError on element click method in Selenium E2E testing

### ISSUE THREAD

**Issue by ianFar96** [tauri-apps/tauri#7667]
### Describe the bug

Having setup the Selenium e2e testing in a project when thr test contains a `click` action the error `UnsupportedOperationError` is thrown

![image](https://github.com/tauri-apps/tauri/assets/30315670/8cbab4dc-1aaf-4c16-b4d7-20bfb296efcb)

### Reproduction

- clone the e2e-testing branch from [this project](https://github.com/ianFar96/kafka_panel/tree/e2e-testing)
- run `npm run tauri build`
- run `npm t`

### Expected behavior

`click` method should work as expected

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.40.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.17.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.2.4
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.4.0)
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

```text
UnsupportedOperationError
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async WebDriver.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
      at async Context.<anonymous> (file:///home/mia/Private/kafka_panel/e2e/topics.test.ts:73:3)
```

**Comment by ianFar96** [comment]
I also tried using WebDriverIo instead of selenium and the same error occurs
![image](https://github.com/tauri-apps/tauri/assets/30315670/9c2dba6b-ce6a-4e98-bccf-08bd33c7b791)

```shell
[0-0] 2023-08-22T16:23:53.632Z ERROR webdriver: Request failed with status 500 due to unsupported operation: unknown error
[0-0] unsupported operation in "Topics.should see topics list"
unsupported operation: unknown error
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (file:///home/mia/Private/kafka_panel/tests/e2e/specs/topics.spec.ts:11:3)
```

to reproduce it clone the branch e2e-testing-wdio on the same project
