### ISSUE TITLE
[bug] App crashes with java.lang.NoSuchMethodError: no non-static method

### ISSUE THREAD

**Issue by 64bit** [tauri-apps/tauri#7678]
### Describe the bug

App crashes on older Android versions but runs on latest version:

```
--------- beginning of crash
08-22 20:17:12.742 12165 12165 E AndroidRuntime: FATAL EXCEPTION: main
08-22 20:17:12.742 12165 12165 E AndroidRuntime: Process: com.tauri.second, PID: 12165
08-22 20:17:12.742 12165 12165 E AndroidRuntime: java.lang.NoSuchMethodError: no non-static method "Lcom/tauri/second/MainActivity;.setWebView(Lcom/tauri/second/RustWebView;)V"
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:325)
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:147)
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6735)
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-22 20:17:12.742 12165 12165 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
08-22 20:17:12.744 12165 12165 W zygote64: Attempt to remove non-JNI local reference, dumping thread
```

### Reproduction

❯ cargo create-tauri-app --alpha
✔ Project name · second
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm)
✔ Choose your package manager · npm
✔ Choose your UI template · React - (https://reactjs.org/)
✔ Choose your UI flavor · TypeScript
✔ Would you like to setup the project for mobile as well? · yes

cd second
npm i
// change bundle identifer to com.second.dev
npm run tauri android init
npm run tauri android dev

### Expected behavior

App should not crash given that  Android (minSdk = 24) version is supported in files generated in `gen/android`

### Platform and versions

```text
❯ npm run tauri info

> second@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.40.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.13.0
    - yarn: 1.22.19
    - npm: 8.19.3

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.11
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.31.1
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 2.0.0-alpha.6
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
Performing Streamed Install
Success
Starting: Intent { cmp=com.tauri.second/.MainActivity }
--------- beginning of main
08-22 20:17:11.542 12165 12165 I zygote64: Late-enabling -Xcheck:jni
08-22 20:17:12.102 12165 12226 I OpenGLRenderer: Initialized EGL, version 1.4
08-22 20:17:12.118 12165 12226 I OpenGLRenderer: Get disable program binary service property (0)
08-22 20:17:12.118 12165 12226 I OpenGLRenderer: Initializing program atlas...
08-22 20:17:12.119 12165 12226 I ProgramBinary/Service: ProgramBinaryService client side disable debugging.
08-22 20:17:12.120 12165 12226 I ProgramBinary/Service: ProgramBinaryService client side disable binary content debugging.
08-22 20:17:12.121 12165 12226 I OpenGLRenderer: Program binary detail: Binary length is 165592, program map length is 104.
08-22 20:17:12.122 12165 12226 I OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 63, and path is /dev/ashmem.
08-22 20:17:12.122 12165 12226 I OpenGLRenderer: No need to use file discriptor anymore, close fd(63).
08-22 20:17:12.202 12165 12165 I WebViewFactory: Loading com.android.chrome version 116.0.5845.92 (code 584509221)
08-22 20:17:12.218 12165 12165 W linker  : "/data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: type 0x70000001 arg 0x0
08-22 20:17:12.219 12165 12218 I RustStdoutStderr: WARNING: linker: "/data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: type 0x70000001 arg 0x0
08-22 20:17:12.262 12165 12165 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<cn2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-22 20:17:12.262 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
08-22 20:17:12.262 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
08-22 20:17:12.262 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:153)
08-22 20:17:12.262 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:443)
08-22 20:17:12.262 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:208)
08-22 20:17:12.262 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2793)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2788)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2859)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context) (View.java:4576)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4718)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:622)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:637)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:620)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:607)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:597)
08-22 20:17:12.262 12165 12165 I zygote64:   at void com.tauri.second.RustWebView.<init>(android.content.Context) (RustWebView.kt:15)
08-22 20:17:12.262 12165 12165 I zygote64:   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
08-22 20:17:12.262 12165 12165 I zygote64:   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.os.Looper.loop() (Looper.java:147)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6735)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
08-22 20:17:12.263 12165 12165 I zygote64:   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
08-22 20:17:12.263 12165 12165 I zygote64:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:845)
08-22 20:17:12.263 12165 12165 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/lib/arm64, /data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:153)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:443)
08-22 20:17:12.263 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:208)
08-22 20:17:12.263 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2793)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2788)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2859)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context) (View.java:4576)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4718)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:622)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:637)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:620)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:607)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:597)
08-22 20:17:12.263 12165 12165 I zygote64:   at void com.tauri.second.RustWebView.<init>(android.content.Context) (RustWebView.kt:15)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
08-22 20:17:12.263 12165 12165 I zygote64:   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.os.Looper.loop() (Looper.java:147)
08-22 20:17:12.263 12165 12165 I zygote64:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6735)
08-22 20:17:12.263 12165 12165 I zygote64:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
08-22 20:17:12.263 12165 12165 I zygote64:   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
08-22 20:17:12.263 12165 12165 I zygote64:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:845)
08-22 20:17:12.263 12165 12165 I zygote64: 
08-22 20:17:12.265 12165 12165 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<cn2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:153)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:443)
08-22 20:17:12.265 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:208)
08-22 20:17:12.265 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2793)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2788)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2859)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context) (View.java:4576)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4718)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:622)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:637)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:620)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:607)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:597)
08-22 20:17:12.265 12165 12165 I zygote64:   at void com.tauri.second.RustWebView.<init>(android.content.Context) (RustWebView.kt:15)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
08-22 20:17:12.265 12165 12165 I zygote64:   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.os.Looper.loop() (Looper.java:147)
08-22 20:17:12.265 12165 12165 I zygote64:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6735)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
08-22 20:17:12.265 12165 12165 I zygote64:   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
08-22 20:17:12.265 12165 12165 I zygote64:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:845)
08-22 20:17:12.265 12165 12165 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/lib/arm64, /data/app/com.android.chrome-FL6wQ-1G0dSAAiokPMretw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:153)
08-22 20:17:12.265 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:443)
08-22 20:17:12.265 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:208)
08-22 20:17:12.266 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2793)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2788)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2859)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context) (View.java:4576)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4718)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:622)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:637)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:620)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:607)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:597)
08-22 20:17:12.266 12165 12165 I zygote64:   at void com.tauri.second.RustWebView.<init>(android.content.Context) (RustWebView.kt:15)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
08-22 20:17:12.266 12165 12165 I zygote64:   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.os.Looper.loop() (Looper.java:147)
08-22 20:17:12.266 12165 12165 I zygote64:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6735)
08-22 20:17:12.266 12165 12165 I zygote64:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
08-22 20:17:12.266 12165 12165 I zygote64:   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
08-22 20:17:12.266 12165 12165 I zygote64:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:845)
08-22 20:17:12.266 12165 12165 I zygote64: 
08-22 20:17:12.266 12165 12165 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<cn2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
08-22 20:17:12.267 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
08-22 20:17:12.267 12165 12165 I zygote64:   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
08-22 20:17:12.267 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:153)
08-22 20:17:12.267 12165 12165 I zygote64:   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:443)
08-22 20:17:12.267 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:208)
08-22 20:17:12.267 12165 12165 I zygote64:   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2793)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2788)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2859)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context) (View.java:4576)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4718)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:622)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
08-22 20:17:12.267 12165 12165 I zygote64:   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
```

### Additional context

Crash happens on older Android:
- Android 8.0 (API 26) 
- Android 7.0 (API 24)

But app works on:
- latest virtual device Android API 34
- Android 12 (API 31)

**Comment by sudormrfbin** [comment]
Workaround seems to be

> changing `isMinifyEnabled = true` to `isMinifyEnabled = false` in `src-tauri/gen/<app-name>/app/build.gradle.kts`

from https://github.com/tauri-apps/tauri/issues/6790#issuecomment-1523615825
