### ISSUE TITLE
[bug] `inputType` is `undefined` for `input` event

### ISSUE THREAD

**Issue by bicarlsen** [tauri-apps/tauri#7821]
### Describe the bug

For an `input` event on `<input type='number'>` if you click the up/down arrows to increment/decrement the value and try to get the [`inputType`](https://docs.rs/web-sys/latest/web_sys/struct.InputEvent.html#method.input_type) an `Uncaught TypeError: Cannot read properties of undefined (reading 'length')` error is thrown. 

### Reproduction

https://github.com/bicarlsen/input_type-tauri

### Expected behavior

The `inputType` should be `InsertReplacementText`.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 116.0.1938.76
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Build Tools 2019
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)  
    - node: 18.17.1
    - pnpm: 8.7.0
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.0 (outdated, latest: 1.4.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

### Stack trace

```text
number_test-ui-121192826a78ebe7.js:142  Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at passStringToWasm0 (number_test-ui-121192826a78ebe7.js:142:19)
    at imports.wbg.__wbg_inputType_108fe2e7159ba07a (number_test-ui-121192826a78ebe7.js:514:22)
    at web_sys::features::gen_InputEvent::InputEvent::input_type::ha0492242d6d863ed (number_test-ui-121192826a78ebe7_bg.wasm:0xc7d92)
    at <number_test_ui::app::App as yew::functional::FunctionProvider>::run::app::{{closure}}::h1650b4887f2e51e8 (number_test-ui-121192826a78ebe7_bg.wasm:0x9e64e)
    at yew::callback::Callback<IN,OUT>::emit::h4bd1a416370724a6 (number_test-ui-121192826a78ebe7_bg.wasm:0xb7bc5)
    at <yew::html::listener::events::oninput::Wrapper as yew::virtual_dom::listeners::Listener>::handle::hf698fb6cbb13b396 (number_test-ui-121192826a78ebe7_bg.wasm:0xd88e2)
    at yew::dom_bundle::btag::listeners::Registry::get_handler::{{closure}}::h1589b5adcba83c32 (number_test-ui-121192826a78ebe7_bg.wasm:0x71205)
    at yew::dom_bundle::subtree_root::SubtreeData::handle::{{closure}}::h79812b68bc2dfc45 (number_test-ui-121192826a78ebe7_bg.wasm:0x7e85f)
    at yew::dom_bundle::subtree_root::SubtreeData::handle::h5d5783dd775fdbc1 (number_test-ui-121192826a78ebe7_bg.wasm:0x4d129)
    at yew::dom_bundle::subtree_root::SubtreeData::add_listener::{{closure}}::hc766f432e874b453 (number_test-ui-121192826a78ebe7_bg.wasm:0xbb1b4)
passStringToWasm0 @ number_test-ui-121192826a78ebe7.js:142
imports.wbg.__wbg_inputType_108fe2e7159ba07a @ number_test-ui-121192826a78ebe7.js:514
$web_sys::features::gen_InputEvent::InputEvent::input_type::ha0492242d6d863ed @ number_test-ui-121192826a78ebe7_bg.wasm:0xc7d92
$<number_test_ui::app::App as yew::functional::FunctionProvider>::run::app::{{closure}}::h1650b4887f2e51e8 @ number_test-ui-121192826a78ebe7_bg.wasm:0x9e64e
$yew::callback::Callback<IN,OUT>::emit::h4bd1a416370724a6 @ number_test-ui-121192826a78ebe7_bg.wasm:0xb7bc5
$<yew::html::listener::events::oninput::Wrapper as yew::virtual_dom::listeners::Listener>::handle::hf698fb6cbb13b396 @ number_test-ui-121192826a78ebe7_bg.wasm:0xd88e2
$yew::dom_bundle::btag::listeners::Registry::get_handler::{{closure}}::h1589b5adcba83c32 @ number_test-ui-121192826a78ebe7_bg.wasm:0x71205
$yew::dom_bundle::subtree_root::SubtreeData::handle::{{closure}}::h79812b68bc2dfc45 @ number_test-ui-121192826a78ebe7_bg.wasm:0x7e85f
$yew::dom_bundle::subtree_root::SubtreeData::handle::h5d5783dd775fdbc1 @ number_test-ui-121192826a78ebe7_bg.wasm:0x4d129
$yew::dom_bundle::subtree_root::SubtreeData::add_listener::{{closure}}::hc766f432e874b453 @ number_test-ui-121192826a78ebe7_bg.wasm:0xbb1b4
$<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h98bf0333724cf1a6 @ number_test-ui-121192826a78ebe7_bg.wasm:0xa30d7
__wbg_adapter_19 @ number_test-ui-121192826a78ebe7.js:216
real @ number_test-ui-121192826a78ebe7.js:189
```

### Additional context

The error does not occur in Firefox using `trunk serve` instead of Tauri.

**Comment by pewsheen** [comment]
I think there's only Firefox would return `InsertReplacementText` and the behavior seemed not to be a common standard between browsers.

**Comment by bicarlsen** [comment]
Okay, so it seems that this is then an issue with `web-sys` in that [`input_type`](https://docs.rs/web-sys/latest/web_sys/struct.InputEvent.html#method.input_type) should return an `Option<String>` instead of `String`.

Shall we close the issue here and move it to the `wasm-bindgen` repo?
