### ISSUE TITLE
[bug] Cannot init for IOS with outdated openssl

### ISSUE THREAD

**Issue by seongs1024** [tauri-apps/tauri#8030]
### Describe the bug

Made a project from the starter template with mobile flag which is solid-ts and package manager is pnpm.
Cannot initialize the project...

```
@mango3 % pnpm tauri ios init

> mango3@0.0.0 tauri /mango3
> tauri "ios" "init"

/mango3/node_modules/.pnpm/@tauri-apps+cli@2.0.0-alpha.15/node_modules/@tauri-apps/cli/index.js:254
    throw loadError
    ^

Error: dlopen(/mango3/node_modules/.pnpm/@tauri-apps+cli-darwin-x64@2.0.0-alpha.15/node_modules/@tauri-apps/cli-darwin-x64/cli.darwin-x64.node, 1): Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: /mango3/node_modules/.pnpm/@tauri-apps+cli-darwin-x64@2.0.0-alpha.15/node_modules/@tauri-apps/cli-darwin-x64/cli.darwin-x64.node
  Reason: image not found
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/mango3/node_modules/.pnpm/@tauri-apps+cli@2.0.0-alpha.15/node_modules/@tauri-apps/cli/index.js:131:29)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.18.2
 ELIFECYCLE  Command failed with exit code 1.
```

It seems like my openssl library is out dated, whose version is `LibreSSL 2.8.3` and the requirement may be supposed to be over `3.0.0`.
Can I use tauri mobile without updating my ssl?

### Reproduction

```
cargo create-tauri-app mango3 -t solid-ts -m pnpm --alpha --mobile
cd mango3
pnpm install
pnpm ios init
```

### Platform and versions

```text
Cannot execute `pnpm run tauri info`
It returns the error again...


> mango3@0.0.0 tauri /mango3
> tauri "info"

/mango3/node_modules/.pnpm/@tauri-apps+cli@2.0.0-alpha.15/node_modules/@tauri-apps/cli/index.js:254
    throw loadError
    ^

Error: dlopen(/mango3/node_modules/.pnpm/@tauri-apps+cli-darwin-x64@2.0.0-alpha.15/node_modules/@tauri-apps/cli-darwin-x64/cli.darwin-x64.node, 1): Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: /mango3/node_modules/.pnpm/@tauri-apps+cli-darwin-x64@2.0.0-alpha.15/node_modules/@tauri-apps/cli-darwin-x64/cli.darwin-x64.node
  Reason: image not found
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/mango3/node_modules/.pnpm/@tauri-apps+cli@2.0.0-alpha.15/node_modules/@tauri-apps/cli/index.js:131:29)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.18.2
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dearfat** [comment]
I have same err when run 'pnpm tauri dev'
