### ISSUE TITLE
[bug] `clearMocks` is undefined or null after upgrading from 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by MGough** [tauri-apps/tauri#8179]
### Describe the bug

Calling `clearMocks()` when using Tauri 1.5.1 results in:
```
TypeError: Cannot convert undefined or null to object
```

This wasn't happening in 1.5.0, my tests have remained unchanged but have started failing because of this.

### Reproduction

The example [from the documentation](https://tauri.app/v1/api/js/mocks#mockipc) can reproduce this error.

I've also reproduced it using my own code sample:
```js
import { mockIPC, clearMocks } from "@tauri-apps/api/mocks";

describe("my test suite", () => {
  afterEach(async () => {
    clearMocks();
  });

  test("it runs", async () => {
    mockIPC((cmd) => {
      if (cmd === "do_thing") {
        return;
      }
    });

    expect(true).toBe(true)
  });
});
```

### Expected behavior

`clearMocks` should not throw an error.

### Platform and versions

```text
[⚠] Environment
    - OS: Mac OS 13.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13) (Homebrew)
    ✔ Cargo: 1.72.1
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 16.20.2
    - yarn: 3.6.3
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0 (outdated, latest: 1.5.1)
    - @tauri-apps/cli [NPM]: 1.5.2 (outdated, latest: 1.5.6)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React (Next.js)
    - bundler: Webpack
```
Not sure why rust isn't showing as installed, it's not particularly relevant for this issue as far as I'm aware, but it is all installed and working.

### Stack trace

```text

FAIL   Desktop Unit Tests (JSDOM Environment)  src/modules/x/__tests__/TauriMocks.test.ts
  ● mocked command

    TypeError: Cannot convert undefined or null to object

      3 |
      4 | afterEach(() => {
    > 5 |    clearMocks()
        |              ^
      6 | })
      7 |
      8 | test("mocked command", () => {

      at __TAURI__ (../../node_modules/@tauri-apps/api/mocks.cjs:1:1034)
      at Object.<anonymous> (src/modules/x/__tests__/TauriMocks.test.ts:5:14)

```

### Additional context

It looks like a fix was pushed into v2, but hasn't been backported to v1.x -https://github.com/tauri-apps/tauri/pull/8071

Originally raised in discord - https://discord.com/channels/616186924390023171/1169597436705128458/1169597436705128458

**Comment by MGough** [comment]
I'm going to try to take a look into backporting the fix and opening a PR now that I have some time to spare.

**Comment by MGough** [comment]
Backport of that PR opened here: https://github.com/tauri-apps/tauri/pull/8219
