### ISSUE TITLE
[bug] Cannot read properties of undefined (reading '__currentWindow')

### ISSUE THREAD

**Issue by Sahasrara** [tauri-apps/tauri#8357]
### Describe the bug

I'm just starting a new app and decided to use Alpha since it has many features I'll need and won't be done developing for a year or two.

I'm not able to get a reference to the window early on in the application lifecycle and I don't know why.

### Reproduction

I just went through the Tauri project creation and added this to main.ts:

```
import { getCurrent, type Window } from '@tauri-apps/plugin-window';

// Module initialization
const currentWindow: Window = getCurrent();
```

### Expected behavior

I would expect to get an instance of the window.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 119.0.2151.97
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.2.0
    - pnpm: 8.11.0
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.18
    - tauri-build [RUST]: 2.0.0-alpha.12
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.12
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.18

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
Uncaught TypeError: Cannot read properties of undefined (reading '__currentWindow')
    at getCurrent (index.min.js:126:49)
    at window.ts:6:37
```

**Comment by Sahasrara** [comment]
Setting index.html to this seems to serve as a workaround, but clearly not ideal:

```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<link rel="icon" type="image/svg+xml" href="/svelte.svg" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>GameScript</title>
		<script type="module">
			console.log('https://github.com/tauri-apps/tauri/issues/8357');
			window.__TAURI_METADATA__ = Object.keys(window.__TAURI_INTERNALS__.metadata).reduce(
				(metadata, property) => {
					metadata[`__${property}`] = window.__TAURI_INTERNALS__.metadata[property];
					return metadata;
				},
				{},
			);
			window.__TAURI_INVOKE__ = window.__TAURI_INTERNALS__.invoke;
			window.__TAURI_IPC__ = window.__TAURI_INTERNALS__.ipc;

			// Create application
			import('/src/main.ts');
		</script>
	</head>
	<body></body>
</html>
```

**Comment by Sahasrara** [comment]
And here's my package.json:
```
{
  "name": "gamescript",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "tauri": "tauri"
  },
  "dependencies": {
    "@tauri-apps/api": "^2.0.0-alpha.11",
    "@tauri-apps/plugin-shell": "^2.0.0-alpha.3",
    "@tauri-apps/plugin-window": "2.0.0-alpha.1"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^2.4.2",
    "@tauri-apps/cli": "^2.0.0-alpha.17",
    "@tsconfig/svelte": "^5.0.0",
    "@types/node": "^20.10.4",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.55.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-svelte": "^2.35.1",
    "postcss": "^8.4.32",
    "prettier": "^3.1.0",
    "prettier-plugin-svelte": "^3.1.2",
    "prettier-plugin-tailwindcss": "^0.5.9",
    "svelte": "^4.0.5",
    "svelte-check": "^3.4.6",
    "tailwindcss": "^3.3.6",
    "tslib": "^2.6.0",
    "typescript": "^5.0.2",
    "vite": "^4.4.4"
  }
}
```

**Comment by FabianLars** [comment]
Can you drop the window plugin? It's now part of the general api npm package again (i know we haven't updated the template yet)

**Comment by Sahasrara** [comment]
Oh wow, thank you very much! That fixed it. I'm using this now:

`import { getCurrent } from '@tauri-apps/api/window';`

**Comment by shenjiangqiu** [comment]
```
const InputView = () => {
    const [text, setText] = useState<string>('');
    const [file_text, setFileText] = useState<string>('');
    const handleClick = () => {
        // invoke<string>('read_file', { path: `${text}` }).then(tauriResponse =>
        //     setFileText(tauriResponse)
        // ).catch(setFileText);


    };

    return (
        <div>
            <input

                type="text"
                value={text}
                onChange={(e) => setText(e.target.value)}
            />
            <button onClick={handleClick}>Submit</button>
            <p>{file_text}</p>
        </div>
    );
};
```
when comment out the invoke call. it compiles

**Comment by dodderss** [comment]
Hi, I still have this issue using:
"@tauri-apps/api": "^2.0.0-rc.0", 
"@tauri-apps/cli": "^2.0.0-rc.0",

My web browser has the errors:
`Cannot read properties of undefined (reading 'metadata')
TypeError: Cannot read properties of undefined (reading 'metadata')
    at getCurrentWindow (http://localhost:3000/static/js/bundle.js:45508:48)
    at TopBar (http://localhost:3000/main.274f69e8b48895f5780b.hot-update.js:41:93)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:20921:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:24892:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:26195:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:11177:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:11221:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:11278:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:31176:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:30424:16)`

But the app still opens and works but no longer auto refreshes for some reason. I can refresh it by right clicking and doing refresh though but sometimes this breaks as well.

I am using a mac if that makes any difference.

**Comment by dodderss** [comment]
I fixed this error by putting the getCurrentWindow() inside a useEffect like this:

```tsx
const [appWindow, setAppWindow] = useState<Window | null>(null);

  useEffect(() => {
    async function fetchWindow() {
      const window = await getCurrentWindow();
      setAppWindow(window);
    }

    fetchWindow();
  }, []);
```
