### ISSUE TITLE
[bug] The generated Android debug program is running normally. There is an error in the publishing mode.

### ISSUE THREAD

**Issue by gyoyo** [tauri-apps/tauri#8569]
### Describe the bug

FATAL EXCEPTION: main
Process: com.gyoyo.okapp, PID: 12614
java.lang.NoSuchMethodError: no non-static method "Lcom/gyoyo/okapp/RustWebView;.evalScript(ILjava/lang/String;)V"
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 120.0.2210.121
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.20
    - tauri-build [RUST]: 2.0.0-alpha.13
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.24.0
    - tauri-cli [RUST]: 2.0.0-alpha.20
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.20

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

**Comment by sticknuder** [comment]
I got an identical error when using Tauri 2.0 Alpha. Just like gyoyo, it works when built in debug mode, but throws that error when in release mode.

The only thing I can think of that is noticeably different from a boilerplate Tauri 2 project is that I used the Store feature in my frontend code.

My codebase is small and I don't mind sharing it, so I'll do that along with `tauri info` and `tauri build --verbose` tomorrow.

**Comment by vinceTheProgrammer** [comment]
I got an identical error when using Tauri 2.0 Alpha. Just like gyoyo, it works when built in debug mode, but throws that error when in release mode.

The only thing I can think of that is noticeably different from a boilerplate Tauri 2 project is that I used the Store feature in my frontend code.

My codebase is small and I don't mind sharing it, so I'll do that along with `tauri info` and `tauri build --verbose` tomorrow.

Edit: I don't think I need to post my info after all, but let me know and I can post it anyway.

**Comment by vinceTheProgrammer** [comment]
Not necessarily sure if this is the right fix, but I found a workaround:

add the following to `src-tauri\gen\android\app\proguard-rules.pro`

```
-keep class <app identifier>.RustWebView {
    public void evalScript(int, java.lang.String);
} 
```

replace `<app identifier>` with your app's identifier. 

Example:
```
-keep class com.vincetheprogrammer.myapp.RustWebView {
    public void evalScript(int, java.lang.String);
} 
```

mentioning @gyoyo in case it might help.

**Comment by vinceTheProgrammer** [comment]
I found this workaround by reading this PR from the Wry repo: https://github.com/tauri-apps/wry/pull/927

**Comment by Legend-Master** [comment]
I believe this has been fixed already, let me know if it's not.
