### ISSUE TITLE
[bug] cannot build with tauri v2.0.0-beta.2

### ISSUE THREAD

**Issue by cathino** [tauri-apps/tauri#8791]
### Describe the bug

cannot build with tauri v2.0.0-beta.2

### Full `tauri info` output

```text
[✔] Environment
    - OS: Debian 12 X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.19.0
    - pnpm: 8.15.1
    - yarn: 1.22.19
    - npm: 9.2.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
RUST_BACKTRACE=full pnpm tauri dev

> name@0.1.0 tauri project
> tauri "dev"

     Running BeforeDevCommand (`pnpm dev`)

> name@0.1.0 dev project
> vite


  VITE v5.0.12  ready in 994 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: http://192.168.1.207:1420/
        Info Watching project/src-tauri for changes...
   Compiling tauri v2.0.0-beta.2
   Compiling pango v0.18.3
   Compiling gdk-pixbuf v0.18.5
error: failed to run custom build command for `tauri v2.0.0-beta.2`

Caused by:
  process didn't exit successfully: `project/src-tauri/target/debug/build/tauri-09d63e8454436581/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=dev
  cargo:rustc-cfg=desktop

  --- stderr
  thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.2/build.rs:359:25:
  failed to define permissions for path: failed to write file: Invalid argument (os error 22)
  stack backtrace:
     0:     0x55d70410188c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:     0x55d70410188c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55d70410188c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x55d70410188c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55d704126f60 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
     5:     0x55d704126f60 - core::fmt::write::h3a39390d8560d9c9
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
     6:     0x55d7040ff8ef - std::io::Write::write_fmt::h5fc9997dfe05f882
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
     7:     0x55d704101674 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x55d704101674 - std::sys_common::backtrace::print::h23a2d212c6fff936
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x55d704102b87 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
    10:     0x55d7041028ef - std::panicking::default_hook::h6038f2eba384e475
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
    11:     0x55d704103008 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
    12:     0x55d704102eee - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
    13:     0x55d704101d56 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
    14:     0x55d704102c52 - rust_begin_unwind
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
    15:     0x55d703f24455 - core::panicking::panic_fmt::hbf0e066aabfa482c
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
    16:     0x55d703f2d253 - build_script_build::define_permissions::{{closure}}::ha8e02928133e7d7d
                                 at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.2/build.rs:359:25
    17:     0x55d703f27969 - core::result::Result<T,E>::unwrap_or_else::h5c219b75d8bbee49
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1430:23
    18:     0x55d703f2cb44 - build_script_build::define_permissions::h9b410d9e87b0be5c
                                 at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.2/build.rs:351:23
    19:     0x55d703f2bc66 - build_script_build::main::h5bf25035d632333d
                                 at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.2/build.rs:306:3
    20:     0x55d703f26b2b - core::ops::function::FnOnce::call_once::h2732ce9346bc65e9
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
    21:     0x55d703f258fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h4a429ad8dcb3b1cd
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
    22:     0x55d703f25ab1 - std::rt::lang_start::{{closure}}::h55b3b73f3778f69f
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
    23:     0x55d7040fbd07 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
    24:     0x55d7040fbd07 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
    25:     0x55d7040fbd07 - std::panicking::try::h3a52eefe24fe3c29
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
    26:     0x55d7040fbd07 - std::panic::catch_unwind::h24c28c23c02c3841
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
    27:     0x55d7040fbd07 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
    28:     0x55d7040fbd07 - std::panicking::try::do_call::ha21f52ba13158470
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
    29:     0x55d7040fbd07 - std::panicking::try::h5581346bf6aeb1f8
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
    30:     0x55d7040fbd07 - std::panic::catch_unwind::h7919645a6b72e25b
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
    31:     0x55d7040fbd07 - std::rt::lang_start_internal::h12de51168669836e
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
    32:     0x55d703f25a8a - std::rt::lang_start::h72bb2bde1c24601d
                                 at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
    33:     0x55d703f2d6de - main
    34:     0x7fb480f9524a - <unknown>
    35:     0x7fb480f95305 - __libc_start_main
    36:     0x55d703f24d51 - _start
    37:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
 ELIFECYCLE  Command failed.
 ELIFECYCLE  Command failed with exit code 101.
```
```


### Additional context

_No response_

**Comment by amrbashir** [comment]
Can you share a reproduction or steps to reproduce?

**Comment by drl990114** [comment]
I also encountered the problem of build failure on the `WindowsOS` of the `aarch` chip.

```bash

error[E0412]: cannot find type `size_t` in the crate root
   --> C:\Users\dongruilin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.2.8\src\ws2def.rs:274:19
    |
274 |     ai_bloblen: ::size_t,
    |                   ^^^^^^ help: a type alias with a similar name exists: `SIZE_T`
    |
   ::: C:\Users\dongruilin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.2.8\src\basetsd.rs:86:1
    |
86  | pub type SIZE_T = ULONG_PTR;
    | ---------------------------- similarly named type alias `SIZE_T` defined here
    |
note: found an item that was configured out
   --> C:\Users\dongruilin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.2.8\src\lib.rs:366:10
    |
366 | pub type size_t = c_uint;
    |          ^^^^^^
    = note: the item is gated behind the `x86` feature
note: found an item that was configured out
   --> C:\Users\dongruilin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.2.8\src\lib.rs:368:10
    |
368 | pub type size_t = __uint64;
    |          ^^^^^^
    = note: the item is gated behind the `x86_64` feature

   Compiling futures-task v0.3.30
   Compiling regex-syntax v0.8.2
   Compiling futures-util v0.3.30
For more information about this error, try `rustc --explain E0412`.
error: could not compile `winapi` (lib) due to 285 previous errors
```

**Comment by JosephKrusling** [comment]
@newproplus I'm experiencing the same issue with windows on arm. How did you manage to resolve it?
