### ISSUE TITLE
promise callback thread panics when calling execute_promise through WebviewMut.dispatch

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#898]
**Describe the bug**
if you call `tauri::execute_promise` through `webview.as_mut().dispatch`, it causes panic at unnamed thread, probably due to the pointer getting dropped before spawned thread for promise actually executes given callback.

This bug appeared right after I updated tauri to latest version, and fixed my code which used `web_view::Handle` to `webview_official::WebviewMut`.

This is probably a really weird bug (or maybe it isn't even a bug) and I know this isn't not how everyone does things,
but I thought it's better to report this just in case if someone else encounters the same bug.

**To Reproduce**
put this code in `main.rs` and compile, then send command `panic` through promise using `promisified` function.

<details>
<summary>Repro code</summary>

```rust
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]
use serde::{Deserialize};
use webview_official::{Webview, WebviewMut};

#[derive(Debug, Deserialize)]
#[serde(tag = "cmd", rename_all = "camelCase")]
enum Command {
    Panic {
        callback: String,
        error: String
    }
}

fn handle(webview: &mut Webview, cmd: Command) -> Result<(), String>{
    match cmd {
        Command::Panic { callback, error } => 
        {
            let mut mutable_pointer = webview.as_mut();
            mutable_pointer.dispatch(move |new_webview| {  // <- this new_webview is a brand new instance of Webview

                // inside this execute_promise, it creates new WebviewMut that points to a new_webview,
                // and then it spawns a thread which will try to evaluate callback using WebviewMut.
                tauri::execute_promise(new_webview, || { 
                    Ok("this may get sent correctly, or causes panic.".to_string())
                }, callback, error);

            // But the new_webview will get dropped right here before the thread evaluates given callback,
            // which causes panic inside the thread.
            }); 
        }
    }
    Ok(())
}

fn main() {
    tauri::AppBuilder::new()
        .invoke_handler(move |webview, arg| {
            match serde_json::from_str(arg) {
                Err(e) => Err(e.to_string()),
                Ok(command) => handle(webview, command),
            }
        })
        .build()
        .run();
}
```

</details>

**Expected behavior**
Promise gets rejected properly.

**Screenshots**

**Platform and Versions (please complete the following information):**

<details>
<summary>Info</summary>

Operating System - Linux(5.6.13-arch1-1) - linux/x64

Node.js environment
  Node.js - 14.5.0
  tauri.js - 0.11.0

Rust environment
  rustc - 1.45.0
  cargo - 1.45.0
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.6
  yarn - 1.22.4

App directory structure
/.git
/.idea
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.0
  mode - no-server
  build-type - build
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:4000

</details>

**Additional context**
You can workaround this bug by replacing `execute_promise` to `execute_promise_sync`,
or just pass normal `&mut Webview` straight up instead of using `WebviewMut.dispatch`.

**Stack Trace**
```
thread '<unnamed>' panicked at 'Failed to dispatch promise callback: WebviewNull', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.9.0/src/lib.rs:97:7
```

<details>
<summary>RUST_BACKTRACE=1</summary>

```
[1] thread '<unnamed>' panicked at 'Failed to dispatch promise callback: WebviewNull', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.9.0/src/lib.rs:97:7
[1] stack backtrace:
[1]    0: backtrace::backtrace::libunwind::trace
[1]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
[1]    1: backtrace::backtrace::trace_unsynchronized
[1]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
[1]    2: std::sys_common::backtrace::_print_fmt
[1]              at src/libstd/sys_common/backtrace.rs:78
[1]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
[1]              at src/libstd/sys_common/backtrace.rs:59
[1]    4: core::fmt::write
[1]              at src/libcore/fmt/mod.rs:1076
[1]    5: std::io::Write::write_fmt
[1]              at src/libstd/io/mod.rs:1537
[1]    6: std::sys_common::backtrace::_print
[1]              at src/libstd/sys_common/backtrace.rs:62
[1]    7: std::sys_common::backtrace::print
[1]              at src/libstd/sys_common/backtrace.rs:49
[1]    8: std::panicking::default_hook::{{closure}}
[1]              at src/libstd/panicking.rs:198
[1]    9: std::panicking::default_hook
[1]              at src/libstd/panicking.rs:218
[1]   10: std::panicking::rust_panic_with_hook
[1]              at src/libstd/panicking.rs:486
[1]   11: rust_begin_unwind
[1]              at src/libstd/panicking.rs:388
[1]   12: core::panicking::panic_fmt
[1]              at src/libcore/panicking.rs:101
[1]   13: core::option::expect_none_failed
[1]              at src/libcore/option.rs:1272
[1]   14: core::result::Result<T,E>::expect
[1]              at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:963
[1]   15: tauri::execute_promise::{{closure}}::{{closure}}
[1]              at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.9.0/src/lib.rs:97
[1]   16: <F as threadpool::FnBox>::call_box
[1]              at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:95
[1]   17: threadpool::spawn_in_pool::{{closure}}
[1]              at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:769
[1] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by nklayman** [comment]
The next Tauri version removes `WebviewMut` in favor of a more robust interface, so this issue will be resolved automatically.
