### ISSUE TITLE
[bug] Compiling on Ubuntu with Tauri 2.0 results in segfault: 'main' panicked at src/cargo/core/compiler/fingerprint/mod.rs:1111:13

### ISSUE THREAD

**Issue by ebenoist** [tauri-apps/tauri#9001]
### Describe the bug

Running dev results in the following stack trace.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.42.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 21.6.1
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.6
    - tauri-build [RUST]: 2.0.0-beta.4
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.4

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
[main+][.]❥ RUST_BACKTRACE=full make run
npm run tauri dev

> meltmobile@0.0.0 tauri
> tauri dev

     Running BeforeDevCommand (`npm run dev`)

> meltmobile@0.0.0 dev
> vite


  VITE v5.1.4  ready in 83 ms

  ➜  Local:   http://localhost:1420/
        Info Watching /home/erik/dev/melt-sounds/melt-tauri/src-tauri for changes...
warning: output filename collision.
The lib target `melt_tauri_lib` in package `melt-tauri v0.0.0 (/home/erik/dev/melt-sounds/melt-tauri/src-tauri)` has the same output filename as the lib target `melt_tauri_lib` in package `melt-tauri v0.0.0 (/home/erik/dev/melt-sounds/melt-tauri/src-tauri)`.
Colliding filename is: /home/erik/dev/melt-sounds/melt-tauri/src-tauri/target/debug/deps/libmelt_tauri_lib.rlib
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
thread 'main' panicked at src/cargo/core/compiler/fingerprint/mod.rs:1111:13:
assertion failed: mtimes.insert(output.clone(), mtime).is_none()
stack backtrace:
   0:     0x555e35c39d16 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x555e35c39d16 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555e35c39d16 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x555e35c39d16 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x555e35c6e990 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x555e35c6e990 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x555e35c333ff - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x555e35c39af4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x555e35c39af4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x555e35c3bbd7 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x555e35c3b939 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x555e35c3c0d8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x555e35c3bf79 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  13:     0x555e35c3a216 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x555e35c3bd10 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x555e35c6bcf5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x555e35c6bdb3 - core::panicking::panic::hb837a5ebbbe5b188
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  17:     0x555e350265fe - <cargo[99583b5eb2a894ba]::core::compiler::fingerprint::Fingerprint>::check_filesystem
  18:     0x555e3502c1f5 - cargo[99583b5eb2a894ba]::core::compiler::fingerprint::calculate
  19:     0x555e3502a806 - <cargo[99583b5eb2a894ba]::core::compiler::fingerprint::DepFingerprint>::new
  20:     0x555e3502b08e - cargo[99583b5eb2a894ba]::core::compiler::fingerprint::calculate
  21:     0x555e35023337 - cargo[99583b5eb2a894ba]::core::compiler::fingerprint::prepare_target
  22:     0x555e35072931 - cargo[99583b5eb2a894ba]::core::compiler::compile
  23:     0x555e3500d23b - <cargo[99583b5eb2a894ba]::core::compiler::context::Context>::compile
  24:     0x555e35160e5e - cargo[99583b5eb2a894ba]::ops::cargo_compile::compile_ws
  25:     0x555e35160b7b - cargo[99583b5eb2a894ba]::ops::cargo_compile::compile
  26:     0x555e34b6eeed - cargo[79c452f2c6e80547]::commands::build::exec
  27:     0x555e34b4b3a0 - cargo[79c452f2c6e80547]::cli::main
  28:     0x555e34b87a7a - cargo[79c452f2c6e80547]::main
  29:     0x555e34b0b6a3 - std[79729d9c385e1623]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  30:     0x555e34b1a1a9 - std[79729d9c385e1623]::rt::lang_start::<()>::{closure#0}
  31:     0x555e35c28851 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  32:     0x555e35c28851 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  33:     0x555e35c28851 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  34:     0x555e35c28851 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  35:     0x555e35c28851 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  36:     0x555e35c28851 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  37:     0x555e35c28851 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  38:     0x555e35c28851 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  39:     0x555e35c28851 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  40:     0x555e34b8dd55 - main
  41:     0x7f9d66429d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  42:     0x7f9d66429e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  43:     0x555e34aec029 - <unknown>
  44:                0x0 - <unknown>
make: *** [Makefile:10: run] Error 101
```

**Comment by amrbashir** [comment]
This looks like an error in [cargo](https://github.com/rust-lang/cargo), don't think we can do anything about it, so try reaching out to them. 

Also try running `cargo clean` inside `src-tauri` and try again.
