### ISSUE TITLE
iOS fails to compile with v2.0.0-beta.12

### ISSUE THREAD

**Issue by Zack-Xb** [tauri-apps/tauri#9228]
### Describe the bug

Tauri app fails to compile after upgrading to `2.0.0-beta.12`.

```
Compiling tauri v2.0.0-beta.12
error: failed to run custom build command for `tauri v2.0.0-beta.12`
 --- stderr
  error: 'ios-api': Invalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/qv/qfq938bd5bl1521dwvl_0v300000gn/T/TemporaryDirectory.MjS8jO/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk", "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk", "-package-description-version", "5.3.0", "/Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.12/mobile/ios-api/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/qv/qfq938bd5bl1521dwvl_0v300000gn/T/TemporaryDirectory.hLdkMi/ios-api-manifest"])
  sandbox-exec: sandbox_apply: Operation not permitted
  thread 'main' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.6/src-rs/build.rs:276:17:
  Failed to compile swift package Tauri
stack backtrace:
     0: rust_begin_unwind
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
     2: swift_rs::build::SwiftLinker::link
               at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.6/src-rs/build.rs:276:17
     3: tauri_utils::build::link_swift_library
               at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-2.0.0-beta.10/src/build.rs:15:3
     4: build_script_build::main
               at ./build.rs:311:7
     5: core::ops::function::FnOnce::call_once
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    Error [tauri_cli] Failed to run `cargo build`: command ["cargo", "build", "--package", "avail_wallet", "--manifest-path", "/Users/user/Avail/avail-wallet/src-tauri/Cargo.toml", "--target", "aarch64-apple-ios-sim", "--features", "tauri/rustls-tls", "--lib", "--no-default-features"] exited with code 101
 ```

### Expected behavior

Successfully compiles and builds for `iOS`.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.1.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.7.1
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.12
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.0
    - tauri-cli [RUST]: 2.0.0-beta.10
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.10

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

[-] iOS
    - Developer Teams: None
```

**Comment by Zack-Xb** [comment]
Update: This still fails on Tauri v2.0.0-beta.13

**Comment by Zack-Xb** [comment]
Dependency issue resolved.

**Comment by maiertech** [comment]
What was the issue?

**Comment by thewh1teagle** [comment]
I had the same issue on macos. executing `cargo update` solved it.
