### ISSUE TITLE
[bug] HMR crashes when `@tauri-apps/api/path` is imported

### ISSUE THREAD

**Issue by rtbo** [tauri-apps/tauri#9324]
### Describe the bug

I'm building an app with SvelteKit and Tauri.
In `+page.ts` I declare
```ts
export const prerender = true;
export const ssr = false;
```

Simple reloads (e.g. adding a class to an element) work without problem.
But If e.g. I add a JS function in the `<script>` section (page reload ?), I get an Error and the app turns in `500 | Internal Error`.

The crashing function is `isWindows` (`@tauri-apps/api/helpers/os-check.js`):
```js
function isWindows() {
    return navigator.appVersion.includes('Win');
}
```
In the context of HMR, `navigator.appVersion` is undefined.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 23.10.0 X64
    ✔ webkit2gtk-4.0: 2.42.5
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.5.0
    - pnpm: 8.15.5
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.1 (no manifest)
    - tauri-build [RUST]: 1.5.1 (no manifest)
    - wry [RUST]: 0.24.7 (no manifest)
    - tao [RUST]: 0.16.7 (no manifest)
    - tauri-cli [RUST]: 1.5.11
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: build
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
10:58:13 [vite] hmr update /src/routes/nav/[instanceName]/+page.svelte, /src/app.css (x4)
10:58:13 [vite] Error when evaluating SSR module /src/lib/model.ts: failed to import "@tauri-apps/api"
|- TypeError: Cannot read properties of undefined (reading 'includes')
    at isWindows (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/@tauri-apps+api@1.5.3/node_modules/@tauri-apps/api/helpers/os-check.js:6:33)
    at file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/@tauri-apps+api@1.5.3/node_modules/@tauri-apps/api/path.js:624:13
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55044:17)
    at async ssrImport (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:24)
    at async eval (/home/remi/dev/fsync/clients/ui/src/lib/model.ts:3:44)
    at async instantiateModule (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9)

10:58:13 [vite] Error when evaluating SSR module /src/routes/nav/[instanceName]/+page.ts: failed to import "/src/lib/model.ts"
|- TypeError: Cannot read properties of undefined (reading 'includes')
    at isWindows (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/@tauri-apps+api@1.5.3/node_modules/@tauri-apps/api/helpers/os-check.js:6:33)
    at file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/@tauri-apps+api@1.5.3/node_modules/@tauri-apps/api/path.js:624:13
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55044:17)
    at async ssrImport (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:24)
    at async eval (/home/remi/dev/fsync/clients/ui/src/lib/model.ts:3:44)
    at async instantiateModule (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9)

TypeError: Cannot read properties of undefined (reading 'includes')
    at isWindows (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/@tauri-apps+api@1.5.3/node_modules/@tauri-apps/api/helpers/os-check.js:6:33)
    at file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/@tauri-apps+api@1.5.3/node_modules/@tauri-apps/api/path.js:624:13
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55044:17)
    at async ssrImport (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:24)
    at async eval (/home/remi/dev/fsync/clients/ui/src/lib/model.ts:3:44)
    at async instantiateModule (file:///home/remi/dev/fsync/clients/ui/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9)
```

**Comment by FabianLars** [comment]
This was fixed in v2 by removing all the variable exports (only relying on functions). This would be a breaking change in v1 so we can't backport this.

Try using dynamic imports for modules that cause issues (the `await import("")` syntax)
