### ISSUE TITLE
[bug] Barcode Scanner Local module descriptor class for com.google.mlkit.dynamite.barcode not found

### ISSUE THREAD

**Issue by TZDXF** [tauri-apps/tauri#9397]
### Describe the bug

Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
Waiting for the barcode module to be downloaded. Please wait.

### Full `tauri info` output

```text
tauri android dev
```

### Stack trace

```text
04-07 14:18:28.599 18765 18965 W DynamiteModule: Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
04-07 14:18:28.618 18765 18765 E MobileVisionBase: Error preloading model resource
04-07 14:18:28.618 18765 18765 E MobileVisionBase: com.google.mlkit.common.MlKitException: Waiting for the barcode module to be downloaded. Please wait.
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.vision.barcode.internal.zzl.zzc(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:10)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.vision.barcode.internal.zzi.load(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:1)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.5.0:4)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.5.0:2)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.5.0:4)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.5.0:1)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.5.0:2)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
04-07 14:18:28.618 18765 18765 E MobileVisionBase:      at java.lang.Thread.run(Thread.java:1012)
```

**Comment by FabianLars** [comment]
Is this on an emulator or a real device?

If it's an emulator, can you make sure it has the play store enabled? In the list of devices there's an icon for that:
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/75816c77-8551-42f1-801e-3bd4990bd4fb)

**Comment by MoYuan-CN** [comment]
Hello. I'm currently developing app with this feature.
As I started the dev process and tap the button that start to scan code, the following lines continue "spam" my console:

```
02-06 00:34:27.682 32268 32669 W DynamiteModule: Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
02-06 00:34:27.686 32268 32268 E Tauri   : Waiting for the barcode module to be downloaded. Please wait.
```

For me, it is the real device. I'm sure that it has GMS and Play Store installed and enabled.

I could remember that if I turn on my VPN (I'm from China) sometimes it could be downloaded and function normally, but sometimes it does not. 

Is there anyway to bundle the `com.google.mlkit.dynamite.barcode` with tauri android app or install it manually as an "app" or "package" to my device?

btw, if any one need more detail, feel free to contact me via this issue ticket.

---

<details>
<summary> `tauri info` detail </summary>

```
[✘] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 144.0.3719.104
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.93.0-nightly (82ae0ee64 2025-10-31)
    ✔ cargo: 1.93.0-nightly (6c1b61003 2025-10-28)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 22.12.0
    - pnpm: 10.24.0
    - npm: 10.9.0
    - bun: 1.3.5

[-] Packages
    - tauri 🦀: 2.9.5, (outdated, latest: 2.10.2)
    - tauri-build 🦀: 2.5.3, (outdated, latest: 2.5.5)
    - wry 🦀: 0.53.5, (outdated, latest: 0.54.1)
    - tao 🦀: 0.34.5
    - @tauri-apps/api  ⱼₛ: 2.9.1 (outdated, latest: 2.10.1)
    - @tauri-apps/cli  ⱼₛ: 2.9.6 (outdated, latest: 2.10.0)

[-] Plugins
    - tauri-plugin-barcode-scanner 🦀: 2.4.3, (outdated, latest: 2.4.4)
    - @tauri-apps/plugin-barcode-scanner  ⱼₛ: 2.4.3 (outdated, latest: 2.4.4)
    - tauri-plugin-fs 🦀: 2.4.5
    - @tauri-apps/plugin-fs  ⱼₛ: 2.4.5
    - tauri-plugin-opener 🦀: 2.5.3
    - @tauri-apps/plugin-opener  ⱼₛ: 2.5.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
 ```

</details>

**Comment by MoYuan-CN** [comment]
Update: 

According to [Barcode API libbarhopper.so](https://stackoverflow.com/questions/47368195/barcode-api-libbarhopper-so), a post from stackoverflow, 
it does work if I clear the cache of the Google Play Service on my device.

Now after a few seconds my barcode class was completely loaded and working normally.

---

Even through the problem was (temporarily) solved, do any one still have ideas of the causes?
