### ISSUE TITLE
[bug] can't build for. universal mac on intel mac

### ISSUE THREAD

**Issue by ralyodio** [tauri-apps/tauri#9635]
### Describe the bug

node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: Request is not defined
    at visit (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:202:45)
    at Object.fn (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:184:22)
    at dequeue (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:40:42)
    at Object.add (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:67:4)
    at enqueue (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:184:12)
    at prerender (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:452:6)
    at async MessagePort.<anonymous> (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:290:10)
    at Worker.[kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
       Error beforeBuildCommand `npm run build` failed with exit code 1
➜  sentinel git:(master) ✗ 
$ 

### Expected behavior

node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: Request is not defined
    at visit (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:202:45)
    at Object.fn (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:184:22)
    at dequeue (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:40:42)
    at Object.add (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:67:4)
    at enqueue (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:184:12)
    at prerender (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:452:6)
    at async MessagePort.<anonymous> (file:///Users/ettinger/src/sentinel/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:290:10)
    at Worker.[kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
       Error beforeBuildCommand `npm run build` failed with exit code 1
➜  sentinel git:(master) ✗ 
$ 

### Full `tauri info` output

```text
$ npx tauri info 

[✔] Environment
    - OS: Mac OS 12.7.4 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09) (Homebrew)
    ✔ cargo: 1.77.2
    ✔ rustup: 1.27.0 (2024-03-08)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.17.0
    - npm: 8.15.0

[-] Packages
    - tauri [RUST]: 1.6.2
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.8
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.5.4
    - @tauri-apps/cli [NPM]: 1.5.12

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Rollup
```

### Additional context

trying to build a unverisal app for macos.

`    "build:mac:universal": "npm run tauri build -- --target universal-apple-darwin",`

**Comment by FabianLars** [comment]
This is your sveltekit frontend failing to build, not tauri. If you run `npm run tauri build` it should fail in the same way so you probably have a better chance of getting help if you ask the sveltekit community instead 🤔

**Comment by ralyodio** [comment]
but it works fine with intel mac build.

**Comment by FabianLars** [comment]
Hmm, that makes no sense to me since beforeBuildCommad only runs once and it _should_ run in the same way no matter the target. Do you have a minimal reproduction repo you can share with us?

p.s. i saw a similar error when someone used a nodejs version that was too old but i assume you're using the same machine here so that wouldn't make sense to me either 🤔

**Comment by ralyodio** [comment]
i'm using v20 on node.  Let me try it again. I have kind of an old intel macbook air, so maybe that could be why? idk. does `--universal` flag need an arm laptop?

**Comment by FabianLars** [comment]
No, the universal flag should work on Intel too (it did in GitHub's CI at least before they switched to arm). The build is failing before the logic for the universal target starts though.

**Comment by ralyodio** [comment]
ok let me dig into it a bit more on my end.
