### ISSUE TITLE
creating property on toml not working in dev or build

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#99]
**Describe the bug**
```
$ RUST_BACKTRACE=1 node node_modules/tauri/bin/tauri build
[tauri]: running build
(node:14442) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'features' on string '0.1.0'
    at Runner.__whitelistApi (/[redacted]/tauri-latest/cli/tauri.js/runner.js:191:48)
    at __manipulateToml.toml (/[redacted]/tauri-latest/cli/tauri.js/runner.js:86:12)
```
**To Reproduce**
1. Go to `examples/vanillajs/monolith`
2. Run the command as above.

**Platform (please complete the following information):**
OS: Mac

My hunch is that this has something to do with the rust workspace configuration.

**Comment by nothingismagick** [comment]
Its resolved.
